feat(core): toolbar horizon update
SAP/fundamental-ngx pull request #10314
Opened 2023-08-07 06:51 UTC by N1XUS

closes #9824
BREAKING CHANGE:
Removed inner `<div class="fd-toolbar">...</div>`.
Now classes and other attributes applied to the root `fd-toolbar` element.

2023-08-08 16:59 UTC, mikerodonnell89 commented on libs/core/src/lib/toolbar/toolbar.component.ts
> +    // get elementRef(): ElementRef {
Can just delete this i think

2023-08-08 17:02 UTC, mikerodonnell89 requested changes
The popover body has lost its padding


Before:
<img width="321" alt="Screenshot 2023-08-08 at 11 00 59 AM" src="https://github.com/SAP/fundamental-ngx/assets/2471874/54920456-e961-43a5-83ed-a6f0f7a630cb">

After:
<img width="297" alt="Screenshot 2023-08-08 at 11 00 12 AM" src="https://github.com/SAP/fundamental-ngx/assets/2471874/a6b6eebf-7797-45ab-9187-de4a14e6d8ef">

2023-08-09 15:39 UTC, mikerodonnell89 requested changes
Popover has some padding now but is missing any sort of border. Looking at other menus, it's not unique to the toolbar overflow
<img width="340" alt="Screenshot 2023-08-09 at 9 38 54 AM" src="https://github.com/SAP/fundamental-ngx/assets/2471874/083936c3-50ea-4e8f-b155-71650a1ed29a">

2023-08-09 20:03 UTC, N1XUS commented
> Popover has some padding now but is missing any sort of border. Looking at other menus, it's not unique to the toolbar overflow <img alt="Screenshot 2023-08-09 at 9 38 54 AM" width="340" src="https://user-images.githubusercontent.com/2471874/259464844-083936c3-50ea-4e8f-b155-71650a1ed29a.png">

That will be fixed with popover update

2023-08-09 20:03 UTC, merged