fix(core): improved multi-input a11y
SAP/fundamental-ngx pull request #10676
Opened 2023-10-05 15:47 UTC by mikerodonnell89

fixes #10622

2023-10-09 11:20 UTC, g-cheishvili requested changes
Please use AI or google translate at least. We're losing completeness with languages

2023-10-16 11:18 UTC, N1XUS commented on libs/i18n/src/lib/translations/translations_uk-UA.json
> +    "coreMultiInput.noResults": "No results.",
Немає результатів

2023-10-16 11:20 UTC, N1XUS commented on libs/i18n/src/lib/translations/translations_uk-UA.json
> +    "coreMultiInput.navigateSelectionsWithArrows": "Navigate selections with the up and down arrows.",
Навігація здійснюється за допомогою клавіш зі стрілками "вгору" та "вниз"

2023-10-16 11:21 UTC, N1XUS commented on libs/i18n/src/lib/translations/translations_uk-UA.json
> +    "coreMultiInput.escapeNavigateTokens": "Press escape to exit the input field and use the left and right arrow keys to navigate through the selected options.",
Натисніть клавішу "Escape", щоб вийти з поля введення, і використовуйте клавіші зі стрілками "вліво" та "вправо" для навігації між вибраними параметрами.

2023-10-20 10:55 UTC, g-cheishvili commented on libs/core/src/lib/multi-combobox/multi-announcer/multi-announcer.directive.ts
> +    }
No need for this in ng16 anymore, check out i18n docs

2023-10-20 10:57 UTC, g-cheishvili commented on libs/core/src/lib/multi-combobox/multi-announcer/multi-announcer.directive.ts
> +    }
This is not type-safe in terms of i18n keys usage

2023-10-24 15:05 UTC, g-cheishvili requested changes

2023-10-24 15:05 UTC, g-cheishvili commented on libs/core/src/lib/multi-combobox/multi-announcer/multi-announcer.directive.ts
> +    private resolveTranslation = resolveTranslationSyncFn();
```suggestion
    private _resolveTranslation = resolveTranslationSyncFn();
```

2023-10-24 15:05 UTC, g-cheishvili commented on libs/core/src/lib/multi-combobox/multi-announcer/multi-announcer.directive.ts
> +    private resolveTranslation = resolveTranslationSyncFn();
references neeed to be renamed as well

2023-10-24 15:05 UTC, g-cheishvili commented on libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts
> +        ContentDensityModule,
You can use it directly here

2023-10-24 18:24 UTC, g-cheishvili approved these changes

2023-10-25 20:00 UTC, merged