[WIP] fix(platform): add validator input for p13 filter component
SAP/fundamental-ngx pull request #11520
Opened 2024-03-06 21:44 UTC by mikerodonnell89

WIP for #11400 

WIP because, as the fundamental-ngx team discussed, we'd like to provide the application developer with the means of handling their own validation for the filter rules. However while implementing this, I do think we could easily do a comparison on our end of contradictory include/exclude rules and disable the "ok" button, with some sort of message alerting the user of the problem. Looking for opinions on this

2024-03-12 19:20 UTC, droshev requested changes
Can you add an example where the user has the choice (like in value-help dialog) where they can return back to the dialog and correct the input or cancel the change from the dialog?

2024-03-15 11:58 UTC, droshev commented
> https://deploy-preview-11520--fundamental-ngx.netlify.app

@mikerodonnell89 I meant something like in the value help with 2 options
<img width="323" alt="Screenshot 2024-03-15 at 07 57 34" src="https://github.com/SAP/fundamental-ngx/assets/4380815/0282979e-4e04-4ade-812c-5d15dd9510e3">

2024-03-18 20:46 UTC, mikerodonnell89 commented
> > https://deploy-preview-11520--fundamental-ngx.netlify.app
> 
> @mikerodonnell89 I meant something like in the value help with 2 options <img alt="Screenshot 2024-03-15 at 07 57 34" width="323" src="https://private-user-images.githubusercontent.com/4380815/313184173-0282979e-4e04-4ade-812c-5d15dd9510e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTQ5ODQsIm5iZiI6MTcxMDc5NDY4NCwicGF0aCI6Ii80MzgwODE1LzMxMzE4NDE3My0wMjgyOTc5ZS00ZTA0LTRhZGUtODEyYy01ZDE1ZGQ5NTEwZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMjA0NDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDM0ZDcxZTczZTQzNmUzOThiMzNjMTc1NzBmYTk3MjZlZGFlMDhhZDFjNjc1NTQ0OWM0NzNhMzBjMzNjOTkwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2bOLfTcCsAK_dJfEZR8-Z2HrMNRr9__vnpexh2dstu0">

Well that is up to the application developer, and it doesn't even make sense from a UX perspective to have these two different buttons, they do the same thing which is simply dismissing the dialog

2024-03-21 13:08 UTC, droshev approved these changes

2024-03-21 15:15 UTC, merged