fix(platform): add fix for breadcrumb template not being rendered in Dynamic Page component
SAP/fundamental-ngx pull request #11676
Opened 2024-04-01 17:11 UTC by InnaAtanasova

## Related Issue(s)

closes https://github.com/SAP/fundamental-ngx/issues/11613

## Description
The problem was that the screenreader was reading "breadcrumb" word when no breadcrumb was displayed. It was because of 2 reasons:
1. The template was read as a ViewChild, but should be a ContentChild
2. The documentation was not passing the correct markup

2024-04-01 18:08 UTC, mikerodonnell89 requested changes
"Breadcrumbs" is still being read out in this example despite no breadcrumbs (platform/dynamic page with facets)
![Screenshot 2024-04-01 at 2 06 20 PM](https://github.com/SAP/fundamental-ngx/assets/2471874/87b867bb-3f3c-4753-97ce-9f08c7507e73)

2024-04-01 19:24 UTC, InnaAtanasova commented
@mikerodonnell89 it's being fixed now

2024-04-02 14:02 UTC, mikerodonnell89 commented
> @mikerodonnell89 it's being fixed now

I'm seeing that the breadcrumbs are now rendered in the example, but if the breadcrumb element is removed from the template, the phrase "Breadcrumb" is still read by the screenreader. My understanding of the original filing of the issue was that there may be instances where dynamic page is used but the breadcrumbs are not, and the screenreader shouldn't be announcing it in this case

2024-04-04 16:00 UTC, mikerodonnell89 approved these changes

2024-04-04 16:46 UTC, merged