fix(core): fixed missing role on focusable dynamic page element
SAP/fundamental-ngx pull request #11680
Opened 2024-04-02 17:33 UTC by g-cheishvili

## Related Issue(s)

closes #11253

## Description

- Removed tabindex from the header
- Added tabindex to the title element and the role of heading to it. When it gets focus through mouse or the tab it will activate the focus design to not break the styling
- Removed h2 and used div instead, because aria-level and heading is now the actual title that is in it

2024-04-02 21:59 UTC, mikerodonnell89 approved these changes

2024-04-02 22:05 UTC, mikerodonnell89 commented on libs/core/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.html
> +                        aria-level="2"
I think this probably needs to be either aria-level 1 (assuming the page will be fullscreen), or, configurable via input by the dev

2024-04-02 22:05 UTC, mikerodonnell89 requested changes
See my comment about aria-level, thanks!

2024-04-04 13:11 UTC, droshev commented
We need to handle the markup/styling changes in styles first.

2024-04-04 13:11 UTC, closed without merging