docs(btp,i18n): add license link in i18n and btp packages' README.md
SAP/fundamental-ngx pull request #11923
Opened 2024-05-17 21:24 UTC by droshev

fixes #11900

2024-05-21 13:52 UTC, InnaAtanasova requested changes

2024-05-21 22:24 UTC, droshev commented on libs/btp/README.md
> +Additionally, it contains injectable helpers to easily control the `rxjs` subscriptions in your components, focusable/selectable list helpers and many more.
pushed an update

2024-05-21 22:25 UTC, droshev commented on libs/btp/README.md
> +The `@fundamental-ngx/btp` library is a set of utilities and [Angular](https://angular.io/) directives aimed to help developers build custom UI components with common interaction patterns.
pushed an update

2024-05-21 22:25 UTC, droshev commented on libs/btp/README.md
> +To download and use Fundamental Library for Angular, you will first need to install the [node package manager](https://www.npmjs.com/get-npm).
pushed an update

2024-05-21 22:25 UTC, droshev commented
@InnaAtanasova Thank you for the review, you made very good points. I have updated the file

2024-05-22 13:15 UTC, InnaAtanasova approved these changes

2024-05-22 15:59 UTC, merged