11966 support for angular 18
SAP/fundamental-ngx pull request #12003
Opened 2024-06-14 11:59 UTC by dpavlenishvili

## Related Issue(s)

closes #11966, #11967 

## Description

## Screenshots

### Before:

### After:

#### Please check whether the PR fulfills the following requirements

##### During Implementation

1. Visual Testing:

-   [ ] visual misalignments/updates
-   [ ] check Light/Dark/HCB/HCW themes
-   [ ] RTL/LTR - proper rendering and labeling
-   [ ] responsiveness(resize)
-   [ ] Content Density (Cozy/Compact/(Condensed))
-   [ ] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [ ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [ ] Mouse vs. Keyboard support
-   [ ] Text Truncation

2. API and functional correctness

-   [ ] check for console logs (warnings, errors)
-   [ ] API boundary values
-   [ ] different combinations of components - free style
-   [ ] change the API values during testing

3. Documentation and Example validations

-   [ ] missing API documentation or it is not understandable
-   [ ] poor examples
-   [ ] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [ ] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [ ] tests for the changes that have been done
-   [ ] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [ ] Run npm run build-pack-library and test in external application
-   [ ] update `README.md`
-   [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

2024-06-14 14:16 UTC, droshev approved these changes

2024-06-18 15:02 UTC, mikerodonnell89 requested changes

2024-06-28 06:44 UTC, ffeldmann commented on libs/docs/core/combobox/examples/combobox-search-field-example.component.html
> -<small>Search Field Term: {{ searchTerm }}</small>
Hi @mikerodonnell89, seems like the issue is resolved. When do you plan to merge this PR? Thanks!

2024-07-02 13:26 UTC, InnaAtanasova approved these changes

2024-07-03 14:25 UTC, mikerodonnell89 reviewed
Scrolling through the components, I occasionally see the warning message below:

![Screenshot 2024-07-03 at 10 23 31 AM](https://github.com/SAP/fundamental-ngx/assets/2471874/5651700a-217e-480e-9015-eb62c4406e11)

This one specifically on core's standard list.  Some more info here: https://angular.dev/errors/NG0955

2024-07-03 15:37 UTC, mikerodonnell89 commented
Also seeing https://angular.dev/errors/NG0955

2024-07-16 20:19 UTC, merged