fix(core): Remove redundant api calls on dynamic page
SAP/fundamental-ngx pull request #12125
Opened 2024-07-16 17:11 UTC by CSEHoangV

## Related Issue(s)

closes https://github.com/SAP/fundamental-ngx/issues/12035

## Description

The fix from https://github.com/SAP/fundamental-ngx/pull/10762 handles content body with static height and when there is a new item being added asynchronously. However, it created a side effect which triggers many calls on `onScroll` from scroll-spy directive even when there is no change to dynamic content body.

The scenario mentioned above has only handled if there is a new change to tab list. Therefore, this fix will add a check if there is a change to the size of tab list and will only execute `onScroll` from scroll-spy directive if that is a case.

After fix:

Remove redundant calls and regression check on previous fix:

 

https://github.com/user-attachments/assets/3507b243-6a3d-408a-801f-9330654b6a6c

2024-07-16 18:43 UTC, yixuan-liu approved these changes

2024-07-16 22:27 UTC, dpavlenishvili approved these changes

2024-07-19 16:38 UTC, mikerodonnell89 requested changes
I think this is more of a band-aid solution, the fix should be coming from the scroll spy directive itself. A scroll on a scrollable child shouldn't trigger the scroll spy logic on the parent component that actually has the directive applied to it. And the scroll event listener definitely shouldn't be called when a child item is clicked, I have no clue why that is happening here but we need to investigate 

**EDIT** - The more I look in to this it does make sense to have a check for this in the tab-list. But in the future - may be good to address what I've mentioned above

2024-07-19 19:52 UTC, mikerodonnell89 approved these changes

2024-07-19 20:10 UTC, merged