feat(core): add font family support to product switch component
SAP/fundamental-ngx pull request #12141
Opened 2024-07-19 08:27 UTC by khotcholava

## Related Issue(s)

closes https://github.com/SAP/fundamental-ngx/issues/12130

## Description

This commit introduces support for setting icons with custom font families in the Product Switch component.

2024-07-19 08:49 UTC, g-cheishvili requested changes

2024-07-19 08:49 UTC, g-cheishvili commented on libs/core/product-switch/product-switch-body/product-switch-body.component.ts
> +    readonly FD_DEFAULT_ICON_FONT_FAMILY = FD_DEFAULT_ICON_FONT_FAMILY;
This should be protected

2024-07-19 15:41 UTC, g-cheishvili approved these changes

2024-07-19 18:00 UTC, droshev requested changes
the examples need to be updates as some don't render icons

2024-07-22 10:28 UTC, khotcholava commented
@droshev Documentation example is updated.

2024-07-22 12:21 UTC, droshev approved these changes

2024-07-22 12:34 UTC, merged