fix(core): resolve issue with alerts not displaying
SAP/fundamental-ngx pull request #12177
Opened 2024-07-25 10:31 UTC by khotcholava

closes  [#12139](https://github.com/SAP/fundamental-ngx/issues/12139)

## Description
Message strip alerts are now shown depending on its positions and  placements

2024-07-25 19:08 UTC, mikerodonnell89 approved these changes

2024-07-25 19:27 UTC, droshev requested changes

2024-07-25 19:27 UTC, droshev commented on libs/core/message-strip/alert/message-strip-alert-container/message-strip-alert-container.component.scss
> +    position: fixed;
I would prefer to move that in styles

2024-07-29 13:55 UTC, InnaAtanasova approved these changes

2024-07-29 17:47 UTC, merged