Fix(platform 12095)/filtering sorting overlapping dialogs
SAP/fundamental-ngx pull request #12211
Opened 2024-08-01 09:43 UTC by dreamweiver

## Related Issue(s)

closes [#12095](https://github.com/SAP/fundamental-ngx/issues/12095)

## Description

When the filter/sort/group settings dialog is triggered multiple times(only happens when the component is busy with other functionality), the settings dialogs are rendered in a stacked order multiple times.

below is the link to the stackblitz, where the problem can be reproduced(click on reload multiple times and then click the sorting button on the header multiple times, after a few seconds multiple sort settings dialog is rendered on the screen)
https://stackblitz.com/edit/6vfrhd-4ghmut?file=src%2Fapp%2Fplatform-table-sortable-example.component.ts

## Screenshots

### Before:

https://github.com/user-attachments/assets/bfc80b68-afd2-4758-814f-f85b38d6f6e8

### After:

https://github.com/user-attachments/assets/b500d2f9-bcd3-40e5-9191-ce60892a253d

#### Please check whether the PR fulfills the following requirements

##### During Implementation

1. Visual Testing:

-   [ ] visual misalignments/updates
-   [ ] check Light/Dark/HCB/HCW themes
-   [ ] RTL/LTR - proper rendering and labeling
-   [ ] responsiveness(resize)
-   [ ] Content Density (Cozy/Compact/(Condensed))
-   [ ] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [ ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [ ] Mouse vs. Keyboard support
-   [ ] Text Truncation

2. API and functional correctness

-   [ ] check for console logs (warnings, errors)
-   [ ] API boundary values
-   [ ] different combinations of components - free style
-   [ ] change the API values during testing

3. Documentation and Example validations

-   [ ] missing API documentation or it is not understandable
-   [ ] poor examples
-   [ ] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [ ] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [ ] tests for the changes that have been done
-   [ ] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [ ] Run npm run build-pack-library and test in external application
-   [ ] update `README.md`
-   [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

2024-08-01 10:20 UTC, Lucifer3009 commented
@InnaAtanasova  @droshev , could you review this PR :)

2024-08-02 14:41 UTC, mikerodonnell89 requested changes
The user could be potentially leaving some other dialog open in the corner of the app or something, so I think rather than `this._dialogService.dismissAll();` let's just store a DialogRef on the component when they open it, and call dismiss on the DialogRef when they attempt to open a new one

2024-08-04 13:00 UTC, droshev commented
@dreamweiver Can you open a PR from a branch instead of a fork(you should be able now)?

2024-08-05 08:33 UTC, dreamweiver commented
closing this PR and will open a new one against the main repo

2024-08-05 08:33 UTC, closed without merging