fix(core): grid list keyboard support
SAP/fundamental-ngx pull request #12288
Opened 2024-08-21 12:49 UTC by khotcholava

fix(core): Enhance keyboard navigation and accessibility

closes [#11968](https://github.com/SAP/fundamental-ngx/issues/11968) 

## Description
- Implemented keyboard navigation for the grid list using arrow keys, Tab, F2, and F7 keys.
- Added Tab navigation to move focus between grid items, similar to arrow key navigation.
- Ensured proper handling of child item selection within the grid list using Tab.
- Enabled exiting the grid list when a child item is selected by pressing the Tab key.

2024-08-26 07:04 UTC, dpavlenishvili commented on libs/core/grid-list/components/grid-list-item/grid-list-item.component.ts
>      get selectionMode(): GridListSelectionMode | undefined {
create selectionMode enum too and use instead of strings

2024-08-26 17:34 UTC, droshev commented
1. focus on the first item from the grid list
2. press F2 (it moves the focus on the first focusable element)
3. press F2 - it doesn't go back to the focusing the whole grid list item

2024-08-26 17:38 UTC, droshev requested changes
see my comments

2024-09-03 16:56 UTC, mikerodonnell89 requested changes
Looking good, two things I noticed during testing: 

1. In the "delete" mode, if you focus the grid list, and then move focus from item to item, then go back and delete the first item, I cannot use tab to focus any items in the grid list. See video

https://github.com/user-attachments/assets/56dca8d1-ccc5-4e7d-9f52-427bd174f919

2. Would be nice if an Escape key press moved focus from child items back to the parent, similar to what we have for table, list etc

2024-09-04 14:45 UTC, mikerodonnell89 approved these changes

2024-09-05 17:39 UTC, dpavlenishvili commented on libs/core/grid-list/components/grid-list/grid-list.component.ts
<img width="1245" alt="image" src="https://github.com/user-attachments/assets/cc195889-65ed-446d-a2b0-552edb7f4b7c">


unit test is failing

2024-09-13 19:50 UTC, dpavlenishvili approved these changes

2024-09-13 22:10 UTC, merged