fix(platform): fdp-table sorting visible columns state get lost
SAP/fundamental-ngx pull request #12429
Opened 2024-09-16 12:54 UTC by khotcholava

closes (#12397)[https://github.com/SAP/fundamental-ngx/issues/12397]

## Description
Ensures the sort order of visible columns is maintained within the customization visible columns dialog of the fdp-table component. This fix prevents the columns from reverting to their original order when the dialog is reopened.

2024-09-17 14:09 UTC, dpavlenishvili commented on libs/platform/table/components/table-p13-dialog/columns/columns.component.ts
> +                        .sort((a, b) => a.order - b.order)
i think instead of sort it you can sort it inside _initiateColumns method, with that way you can reduce manipulation on array.

2024-09-19 15:34 UTC, mikerodonnell89 commented on libs/platform/table/components/table-p13-dialog/columns/columns.component.ts
> +        console.log(this.availableColumns);
Can remove this

2024-09-19 15:36 UTC, mikerodonnell89 approved these changes

2024-09-19 15:37 UTC, mikerodonnell89 requested changes
Just need to remove a console.log but looks good

2024-09-19 15:37 UTC, mikerodonnell89 commented on libs/platform/table/components/table-p13-dialog/columns/columns.component.ts
> +        console.log(this.availableColumns);
Works well, just pull this console log out before merging

2024-09-23 07:22 UTC, dpavlenishvili approved these changes

2024-09-24 16:24 UTC, mikerodonnell89 approved these changes

2024-09-25 12:48 UTC, merged