fix(core): more customization of aria attributes for multi-input
SAP/fundamental-ngx pull request #12437
Opened 2024-09-17 19:13 UTC by mikerodonnell89

fixes #12434

2024-09-18 09:33 UTC, khotcholava approved these changes

2024-09-19 09:55 UTC, dpavlenishvili commented on libs/core/multi-input/multi-input.component.html
> +            [addonButtonAriaHidden]="addonButtonAriaHidden"
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/ef32abf8-cf98-4a66-a788-db9dea02c369">

We have a common issue throughout the application where we use aria-hidden on focusable elements or elements with focusable children, which isn't allowed. In this case, the button is focusable and causes the error shown in the screenshot. I fixed a similar issue in my PR: https://github.com/SAP/fundamental-ngx/pull/12445.
<img width="806" alt="image" src="https://github.com/user-attachments/assets/6d8609f1-ce95-4277-965c-85e514e5d6cd">

2024-09-19 10:01 UTC, dpavlenishvili requested changes
please see comment

2024-09-19 13:20 UTC, droshev commented
@mikerodonnell89 Can you ask ariba's team to validate the change before merging it?

2024-09-23 12:58 UTC, dpavlenishvili approved these changes

2024-09-24 16:18 UTC, merged