11430 fix select form message
SAP/fundamental-ngx pull request #12596
Opened 2024-10-17 22:42 UTC by khotcholava

fix(core) Select Form Message

closes [#11430](https://github.com/SAP/fundamental-ngx/issues/11430)

## Description
Fix select form message styling in select component

### Before
<img width="855" alt="Screenshot 2024-10-18 at 02 39 19" src="https://github.com/user-attachments/assets/663119c2-7962-4fad-8922-fbf454a6b9bd">

***

### After 

<img width="712" alt="Screenshot 2024-10-18 at 02 39 57" src="https://github.com/user-attachments/assets/10d77a33-4937-4ed9-bfe8-cd515e143a70">

2024-10-18 19:09 UTC, droshev requested changes
the PR title is not well written and the PR fields are not set

2024-10-21 15:53 UTC, mikerodonnell89 approved these changes

2024-11-06 21:18 UTC, merged

2024-12-04 07:21 UTC, LukasHeimann commented
Is it intentional that this change introduces additional whitespace when there is no value state text at all? https://github.com/SAP/fundamental-ngx/issues/12810

2025-03-19 15:34 UTC, droshev commented
there should not be any extra space