fix(platform): form generator - fix form generator button group alignment
SAP/fundamental-ngx pull request #12700
Opened 2024-11-07 14:50 UTC by khotcholava

fix(platform): fix form generator button group alignment

closes [#11003](https://github.com/SAP/fundamental-ngx/issues/11003)

## Description 

- Fixed radio button alignment 
- Updated fundamental styles version to the latest

## Snapshots

### Before 

![Screenshot 2024-11-07 at 18 47 46](https://github.com/user-attachments/assets/c0b565e1-dc1c-430f-a87a-eb827120760d)

### After 

![Screenshot 2024-11-07 at 18 47 55](https://github.com/user-attachments/assets/f7442570-952c-4eb6-a7f5-960c623cb83c)

2024-11-12 16:32 UTC, InnaAtanasova requested changes
You need to rebase main so that the latest theming-base-content (11.22.0) kicks in and you won't have missing borders for the radio buttons 
<img width="530" alt="Screenshot 2024-11-12 at 11 30 43 AM" src="https://github.com/user-attachments/assets/012a986e-374b-48cd-ae68-31f2ac2e90bb">

Also, I am blocking the PR as it's using the RC version of fund-styles. We need a non-RC version so that it goes to main.

2024-11-20 14:43 UTC, droshev commented
@khotcholava to investigate why e2e are failing.

2024-11-21 13:42 UTC, dpavlenishvili approved these changes

2024-11-26 15:22 UTC, droshev commented
@khotcholava to investigate why e2e are still failing.

2024-12-02 08:05 UTC, khotcholava commented
@droshev The failing e2e test in this PR is unrelated to the changes here. I tested it on the main branch, and it fails there as well. 

I'll continue investigating the cause of the failing e2e test, but it shouldn't prevent us from merging this PR. 

The only blocker for this PR, as Inna mentioned in her comment, is the use of a non-RC version.

2024-12-18 15:17 UTC, droshev commented
@khotcholava remove the RC styles dependencies, copy over the CSS in the component.scss file as a temp solution, resolve the conflicts, make sure e2e/unit are passing. Then we would need to review it quickly.

2024-12-20 14:38 UTC, droshev commented
@droshev to take over.

2025-03-07 18:01 UTC, droshev commented
moved to [PR](https://github.com/SAP/fundamental-ngx/pull/13096)

2025-03-07 18:45 UTC, mikerodonnell89 commented
closing in favor of #13096

2025-03-07 18:45 UTC, closed without merging