fix(core): enable segmented button
SAP/fundamental-ngx pull request #12808
Opened 2024-12-03 18:19 UTC by droshev

fixes #12675

fix enable segmented button

2024-12-04 16:19 UTC, mikerodonnell89 requested changes
This does allow the segmented button to be focused again, however I can no longer use the arrow keys to change the selected segment. Still working for the other examples, I'm just seeing this problem on the newly modified example

2024-12-04 18:27 UTC, InnaAtanasova commented
> This does allow the segmented button to be focused again, however I can no longer use the arrow keys to change the selected segment. Still working for the other examples, I'm just seeing this problem on the newly modified example

I can confirm the same thing. The arrow keys are not working. Also, I would suggest an improvement for the example. Add a button that programatically disables and enables the Segmented button. Additionally, explain in a 2-3 short sentences what this example is doing. Right now, with the short timeout, for people that don't have an idea what the issue is, it's not very clear why we have this example.

2024-12-05 23:59 UTC, droshev commented
> so, I would suggest an improvement for the example. Add a button that programatically disables and enables the Segmented button. Additionally, e

fixed!

2024-12-23 21:33 UTC, mikerodonnell89 commented
> > so, I would suggest an improvement for the example. Add a button that programatically disables and enables the Segmented button. Additionally, e
> 
> fixed!

I am not seeing an update regarding Inna's documentation suggestions

Also, while I am seeing the arrow key focus problem is fixed, I can no longer use enter/space to change the selection on this example

2025-01-21 21:35 UTC, alexhristov14 commented
like @mikerodonnell89 said, enter/space does not change the selection in the reactive form. Also, clicking it with a mouse only focuses it but doesn't change the value/selection.

2025-02-05 14:55 UTC, InnaAtanasova requested changes
Complex example doesn't work as expected. 
To reproduce the problem:
- click on the first button. It gets selected state, the value is updated to `value: first`
- click on the second button. The value is updated to `value: first,second`, but the segmented button doesn't show selection.
<img width="719" alt="Screenshot 2025-02-05 at 9 55 21 AM" src="https://github.com/user-attachments/assets/73303d3a-66dd-478f-8cbf-41c44771f4f4" />

2025-02-05 14:56 UTC, InnaAtanasova commented on libs/core/segmented-button/segmented-button.component.spec.ts
> +    @ViewChild(SegmentedButtonComponent) segmentedButton: SegmentedButtonComponent;
these can be signal based

2025-02-05 15:01 UTC, InnaAtanasova requested changes
https://github.com/user-attachments/assets/a6fdcf5c-08a4-4890-acc1-76cb515fa82c

There's hover state on the selected button and using arrow keys focus the entire segmented button.

2025-02-05 15:19 UTC, mikerodonnell89 approved these changes

2025-02-05 15:38 UTC, merged