feat(core): dialog focus trap
SAP/fundamental-ngx pull request #12831
Opened 2024-12-09 09:37 UTC by khotcholava

closes [#12768](https://github.com/SAP/fundamental-ngx/issues/12768)

Ensure the button does not lose focus after the dialog is closed, improving usability and navigation flow.

Uploading Screen Recording 2024-12-09 at 13.36.32.mov…

2024-12-18 15:21 UTC, droshev commented
@dpavlenishvili can you review it? thanks

2024-12-20 16:03 UTC, alexhristov14 requested changes

2024-12-20 16:03 UTC, alexhristov14 commented on libs/core/dialog/dialog-service/dialog.service.ts
> +            console.log(dialogConfig.focusTrapped);
Remove console.log

2025-01-15 02:10 UTC, mikerodonnell89 approved these changes

2025-01-15 02:11 UTC, merged