fix: add flags to combobox and multiinput to hide addon button
SAP/fundamental-ngx pull request #3062
Opened 2020-08-20 19:38 UTC by mikerodonnell89

fixes #3004 

adds the input [displayAddonButton] (default value true) to combobox and multiinput

2020-08-24 11:52 UTC, salarenko requested changes

2020-08-24 11:52 UTC, salarenko commented on apps/docs/src/app/core/component-docs/combobox/examples/combobox-example.component.html
> +    [dropdownValues]="dropdownValues"
Please use static string bindings when possible.

2020-08-24 11:52 UTC, salarenko commented on libs/core/src/lib/combobox/combobox.component.ts
> +    displayAddonButton = true;
I think in this context our input should be named `showDropdownButton`

2020-08-25 09:27 UTC, JKMarkowski approved these changes
LGTM

2020-08-25 22:28 UTC, merged