fix: multi input should attach to body
SAP/fundamental-ngx pull request #3193
Opened 2020-09-03 22:02 UTC by mikerodonnell89

fixes #3000

2020-09-04 13:21 UTC, salarenko requested changes

2020-09-04 13:21 UTC, salarenko commented on libs/core/src/lib/multi-input/multi-input.component.html
> +            [appendTo]="'body'"
Switch to static string binding

2020-09-07 07:18 UTC, salarenko approved these changes

2020-09-07 07:44 UTC, JKMarkowski approved these changes

2020-09-08 15:01 UTC, merged