chore: migrate from CLA to DCO
SAP/fundamental-ngx pull request #3194
Opened 2020-09-03 23:42 UTC by droshev

#### Please provide a link to the associated issue.
fixes: #3017

2020-09-04 15:55 UTC, jessmetivier requested changes
Just a few kinks to irons out!

2020-09-04 15:55 UTC, jessmetivier commented on CONTRIBUTING.md
> +1.  You must be aware of the Apache License (which describes contributions) and **accept the Developer Certificate of Origin**. This is common practice in major Open Source projects. To make this pro
1. You must be familiar with the Apache License (that describes contributions) and **accept the Developer Certificate of Origin**. This is a common practice in major open source projects. To make this process as simple as possible, we are using *[CLA assistant](https://cla-assistant.io/)* for individual contributions. CLA assistant is an open source tool that integrates well with GitHub, providing users with an easy one-click experience when accepting the CLA. For company contributors, special rules apply. See the respective section below for details.

2020-09-04 15:55 UTC, jessmetivier commented on .reuse/dep5
> + that governs this project grant any rights in or to any External Products,or
Space comma after Products,

2020-09-04 15:55 UTC, jessmetivier commented on .reuse/dep5
> + a particular SAP External Product, then you may only make use of any API Calls
Rearranged sentence for better clarity: "Then you may only make use of this project's API Calls for internal, non-productive, and non-commercial test and evaluation of such API Calls for that SAP External Product."

2020-09-04 15:55 UTC, jessmetivier commented on .reuse/dep5
> + parties the right to use of access any SAP External Product, through API Calls.
use or access* 
SAP External Products*

2020-09-04 15:55 UTC, jessmetivier commented on .reuse/dep5
> + you any rights to use or access any SAP External Product, or provide any third
SAP External Products*

2020-09-04 15:55 UTC, jessmetivier commented on .reuse/dep5
> + parties the right to use of access any SAP External Product, through API Calls.
no comma after Products

2020-09-04 15:55 UTC, jessmetivier commented on CONTRIBUTING.md
> +Due to legal reasons, contributors will be asked to accept a DCO before they submit the first pull request to this projects, this happens in an automated fashion during the submission process. SAP us
before they submit **their** first pull request*

2020-09-04 15:55 UTC, jessmetivier commented on CONTRIBUTING.md
> +Due to legal reasons, contributors will be asked to accept a DCO before they submit the first pull request to this projects, this happens in an automated fashion during the submission process. SAP us
to this project* (singular)

2020-09-04 15:55 UTC, jessmetivier commented on CONTRIBUTING.md
> +Due to legal reasons, contributors will be asked to accept a DCO before they submit the first pull request to this projects, this happens in an automated fashion during the submission process. SAP us
"Due to legal reasons, contributors will be asked to accept a DCO before they submit their first pull request to this project. This process will happen in an automated fashion during a submission."

2020-09-09 16:12 UTC, jessmetivier approved these changes

2020-09-09 16:17 UTC, Vanessa-Cusmich approved these changes
LGTM

2020-09-09 16:19 UTC, merged