fix: fixing info label Defects raised issue id 3086
SAP/fundamental-ngx pull request #3246
Opened 2020-09-10 14:01 UTC by Lokanathan-k

fixing infolabel Defects raised

#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/3086

#### Please provide a brief summary of this pull request.

<img width="853" alt="Screenshot 2020-09-10 at 7 30 27 PM" src="https://user-images.githubusercontent.com/53534379/92741319-1b7f5980-f39c-11ea-89be-fbe5381b9ee1.png">

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

2020-09-10 14:21 UTC, KevinOkamoto approved these changes
Looks good.

2020-09-10 14:24 UTC, KevinOkamoto requested changes
Looks like there are compilation errors:
```
ERROR in libs/core/src/lib/info-label/info-label.component.spec.ts:45:9 - error TS2322: Type '"only-icon"' is not assignable to type 'LabelType'.
45         component.type = 'only-icon';
           ~~~~~~~~~~~~~~
```

Look at the Travis build errors.

2020-09-10 16:37 UTC, KevinOkamoto approved these changes

2020-09-10 19:58 UTC, InnaAtanasova requested changes
<img width="1177" alt="Screen Shot 2020-09-10 at 3 57 58 PM" src="https://user-images.githubusercontent.com/39598672/92795510-6ee2af00-f37e-11ea-945e-82c62c883ced.png">

Please update the doc part, it still says `icon-only`

2020-09-11 14:41 UTC, salarenko reviewed
Fix formatting and LGTM

2020-09-11 14:41 UTC, salarenko commented on apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-docs.component.html
> +<description
Format

2020-09-11 14:41 UTC, salarenko commented on apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-docs.component.html
> +<description
Format

2020-09-11 14:41 UTC, salarenko commented on apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-docs.component.html
> +<description
Format

2020-09-11 16:03 UTC, InnaAtanasova approved these changes

2020-09-11 16:31 UTC, merged