fix: (platform) Remove Invalid examples from menu button Documentation
SAP/fundamental-ngx pull request #3363
Opened 2020-09-22 13:48 UTC by DeepakSap14

#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/3357

#### Please provide a brief summary of this pull request.
This PR fixes first issue defined in Issue.
2nd issue is related to Platform Menu. will raise separate issue for handling compact in Menu.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2020-09-22 14:03 UTC, sKudum approved these changes
LGTM

2020-09-22 15:07 UTC, KevinOkamoto approved these changes
Looks good.

2020-09-24 19:21 UTC, InnaAtanasova approved these changes

2020-09-25 00:33 UTC, droshev submitted a review, later dismissed
The second issue is still not solved - the compact menu button has cozy menu
![Screen Shot 2020-09-24 at 8 31 41 PM](https://user-images.githubusercontent.com/4380815/94213572-24485300-fea5-11ea-841a-f72105a2e751.png)

2020-09-25 04:34 UTC, DeepakSap14 commented
> The second issue is still not solved - the compact menu button has cozy menu
> ![Screen Shot 2020-09-24 at 8 31 41 PM](https://user-images.githubusercontent.com/4380815/94213572-24485300-fea5-11ea-841a-f72105a2e751.png)

@droshev for this i have raised separate issue to track. https://github.com/SAP/fundamental-ngx/issues/3364
It relates to Platform menu, currently platform menu is not supporting compact density.

2020-09-25 07:31 UTC, DeepakSap14 commented
I have included fix for Menu compact density. and modified example for compact menu button.

2020-09-25 12:48 UTC, Betrozov requested changes

2020-09-25 12:48 UTC, Betrozov commented on libs/platform/src/lib/components/menu/menu.component.html
> +        <nav class="fd-menu" [ngClass]="contentDensity==='compact'? 'fd-menu--compact': ''" tabindex="0" role="menu"
plz use `[class.fd-menu--compact]="contentDensity === 'compact'"`

2020-09-25 13:06 UTC, DeepakSap14 commented on libs/platform/src/lib/components/menu/menu.component.html
> +        <nav class="fd-menu" [ngClass]="contentDensity==='compact'? 'fd-menu--compact': ''" tabindex="0" role="menu"
Done

2020-09-25 14:46 UTC, KevinOkamoto approved these changes
Looks good!

2020-09-29 14:11 UTC, DeepakSap14 commented
will wait till https://github.com/SAP/fundamental-ngx/pull/3400/ is merged.
Have to implement breaking changes.

2020-09-30 11:55 UTC, dimamarksman commented on libs/platform/src/lib/components/menu/menu.component.ts
> +    contentDensity: ContentDensity
Should not we have a default value?

2020-09-30 15:20 UTC, DeepakSap14 commented on libs/platform/src/lib/components/menu/menu.component.ts
> +    contentDensity: ContentDensity
fixed. included default as 'cozy'.

2020-10-01 04:35 UTC, DeepakSap14 commented
This can be reviewed now.
@JKMarkowski

2020-10-01 04:35 UTC, DeepakSap14 commented
@dimamarksman

2020-10-01 08:00 UTC, dimamarksman approved these changes
LGTM

2020-10-01 15:54 UTC, JKMarkowski approved these changes

2020-10-01 16:13 UTC, merged