WIP fix: migrate buttons 0.12.0
SAP/fundamental-ngx pull request #3400
Opened 2020-09-25 13:07 UTC by JKMarkowski

#### Please provide a link to the associated issue.

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2020-09-28 10:23 UTC, JKMarkowski commented
![image](https://user-images.githubusercontent.com/26483208/94421127-66171900-0185-11eb-87d8-6f6270d79cac.png)

2020-09-28 10:32 UTC, salarenko commented on libs/core/src/lib/button/button.component.ts
> +    textElementRef: ElementRef;
Is this needed?

2020-09-28 10:32 UTC, salarenko commented on libs/core/src/lib/button/button.component.html
> +        role="presentation"
`fd-icon` by default provides `role="presentation"`

2020-09-28 10:33 UTC, JKMarkowski commented
Time increase/decrease button doesn't have icon
![image](https://user-images.githubusercontent.com/26483208/94422085-cf4b5c00-0186-11eb-84ce-0e16b988158f.png)

2020-09-28 10:34 UTC, JKMarkowski commented on libs/core/src/lib/button/button.component.ts
> +    textElementRef: ElementRef;
It should be removed

2020-09-28 19:47 UTC, mikerodonnell89 commented
Dialogs do have buttons now but they are not centered

![Screen Shot 2020-09-28 at 1 46 23 PM](https://user-images.githubusercontent.com/2471874/94478795-0161bb80-0191-11eb-9e94-d73d8fabc097.png)

2020-09-29 08:10 UTC, JKMarkowski commented
@mikerodonnell89 Dialog close button has been fixed

2020-09-29 14:31 UTC, mikerodonnell89 approved these changes

2020-09-29 14:47 UTC, InnaAtanasova approved these changes

2020-09-29 15:06 UTC, salarenko requested changes

2020-09-29 15:06 UTC, salarenko commented on apps/docs/src/app/core/component-docs/menu/examples/menu-separator-example.component.html
> +    <button fd-button label="Menu" [fdMenu]="true" [fdMenuTrigger]=""></button>
You broke menu example here `[fdMenuTrigger]=""`

2020-09-29 15:14 UTC, salarenko approved these changes

2020-09-29 16:24 UTC, merged