fix: add fix for ShellBar user menu button using Avatar
SAP/fundamental-ngx pull request #3468
Opened 2020-09-29 19:36 UTC by InnaAtanasova

#### Please provide a link to the associated issue.
Part of https://github.com/SAP/fundamental-ngx/issues/3420

#### Please provide a brief summary of this pull request.
Add glyph to Avatar inside user menu button.

2020-09-30 13:49 UTC, JKMarkowski approved these changes

2020-09-30 15:19 UTC, salarenko requested changes
This is not the fix! There is no reason to import Avatar styles into Shellbar, Avatar provides the styles by itself.

Here is the problem:
![image](https://user-images.githubusercontent.com/17496353/94705273-25fc9580-0341-11eb-8af8-27553ee438e0.png)

1. Avatar has icon class on its main element
2. Avatar is placed inside the button
3. Button selector is targeting the avatar as an icon and overriding its styles with icon styles

2020-10-01 12:22 UTC, salarenko approved these changes

2020-10-01 12:27 UTC, salarenko approved these changes

2020-10-01 20:05 UTC, merged