fix: Update Table example
SAP/fundamental-ngx pull request #3505
Opened 2020-09-30 09:01 UTC by salarenko

#### Please provide a link to the associated issue.
Part of: #3420 

#### Please provide a brief summary of this pull request.
This PR:
- Updates Table Dialog with proper selection list markup

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2020-09-30 13:10 UTC, InnaAtanasova approved these changes

2020-09-30 13:10 UTC, InnaAtanasova commented
Renamed to `docs` as it's only touching the docs files

2020-09-30 14:33 UTC, JKMarkowski requested changes
![image](https://user-images.githubusercontent.com/26483208/94699234-6278c300-033a-11eb-8f56-2e6b39588090.png)
Could you use list selection markup from ?
https://fundamental-ngx.netlify.app/#/core/list#selection-list

2020-09-30 14:55 UTC, salarenko commented
@JKMarkowski I've added missing title for list elements.

2020-09-30 23:08 UTC, droshev approved these changes

2020-10-01 08:23 UTC, JKMarkowski approved these changes

2020-10-01 08:32 UTC, merged