[WIP]feat: Platform object marker documentation and platform library changes
SAP/fundamental-ngx pull request #3525
Opened 2020-10-02 05:31 UTC by Lokanathan-k

#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/2601

#### Please provide a brief summary of this pull request.

This indicates the technical status of an object.
It is enabled for the dynamic page layout, snapping header, object page header, upload collection, and object list item.
The technical status can be represented as and icon, with an icon and text, or as text only, depending on the screen size.
Currently, the following technical statuses can be visualized by the object marker:

Flag
Favorite
Editing Status (Draft, Locked, Unsaved Changes)
The editing status is part of the draft handling concept.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2020-10-05 07:23 UTC, sKudum requested changes
It does not have breaking changes, we can remove the selected option PR description.

2020-10-05 07:23 UTC, sKudum commented on libs/platform/src/lib/components/object-marker/object-marker.component.spec.ts
> +  });
having style class check will help to cover a few tests senarios

2020-10-06 10:27 UTC, Betrozov approved these changes

2020-10-06 18:53 UTC, KevinOkamoto approved these changes
Looks good.

2020-10-07 10:04 UTC, sKudum commented
Hi Lok, 
I am approving it, please address API issues before proceeding further that will help.

2020-10-07 10:06 UTC, sKudum approved these changes

2020-10-08 19:48 UTC, InnaAtanasova approved these changes
Please remove the focus from the test. The rest looks good.

2020-10-08 19:48 UTC, InnaAtanasova commented on libs/platform/src/lib/components/object-marker/object-marker.component.spec.ts
> +fdescribe('PlatformObjectMarkerComponent', () => {
Please remove the focus

2020-10-09 07:08 UTC, Lokanathan-k commented
@InnaAtanasova @sKudum  done with the code change will be merging the code.

2020-10-09 07:08 UTC, merged