feat: new object identifier
SAP/fundamental-ngx pull request #3526
Opened 2020-10-02 09:03 UTC by JKMarkowski

#### Please provide a link to the associated issue.
closes https://github.com/SAP/fundamental-ngx/issues/3425
#### Please provide a brief summary of this pull request.
There is included `ObjectIdentifier` component
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2020-10-02 18:36 UTC, InnaAtanasova reviewed
Could you add an example with no description?
I think it's a good idea to copy the documentation part from fund-styles and if needed to add ngx specific stuff. We should be unifying our documentations. 
The rest looks good

2020-10-05 10:10 UTC, Betrozov requested changes

2020-10-05 10:10 UTC, Betrozov commented on apps/docs/src/app/core/component-docs/object-identifier/object-identifier-docs.component.html
> +<fd-docs-section-title [id]="'default'" [componentName]="'objectIdentifier'">
unnecessary binding
plz check the whole file

2020-10-05 10:10 UTC, Betrozov commented on libs/core/src/lib/object-identifier/object-identifier.component.ts
> +           [ngClass]="{'fd-object-identifier__title--bold': bold}">
[class.fd-object-identifier__title--bold]="bold"

2020-10-05 10:10 UTC, Betrozov commented on libs/core/src/lib/object-identifier/object-identifier.component.ts
> +        if (changes && changes['large']) {
plz move to variable `changes['large']`

2020-10-05 16:54 UTC, mikerodonnell89 requested changes
Looks great, just remove fdescribe from test

2020-10-05 16:54 UTC, mikerodonnell89 commented on libs/core/src/lib/object-identifier/object-identifier.component.spec.ts
> +fdescribe('ObjectIdentifierComponent', () => {
fdescribe

2020-10-06 07:55 UTC, JKMarkowski commented
@InnaAtanasova , @mikerodonnell89, @Betrozov, Thanks for taking a look :) You comments has been addressed, so it's ready for rereview

2020-10-06 10:29 UTC, Betrozov approved these changes

2020-10-06 13:13 UTC, InnaAtanasova approved these changes

2020-10-06 14:10 UTC, mikerodonnell89 approved these changes

2020-10-06 16:47 UTC, merged