feat: (core) introduce object number component
SAP/fundamental-ngx pull request #3567
Opened 2020-10-07 12:24 UTC by IlyaSurmay

#### Please provide a link to the associated issue.

closes https://github.com/SAP/fundamental-ngx/issues/3284

#### Please provide a brief summary of this pull request.

Introduce core object number component

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2020-10-07 12:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/fundamental-ngx?pullRequest=3567) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/fundamental-ngx?pullRequest=3567) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/fundamental-ngx?pullRequest=3567) it.</sub>

2020-10-07 13:00 UTC, InnaAtanasova approved these changes
LGTM

2020-10-09 10:57 UTC, Betrozov commented on libs/core/src/lib/object-number/object-number.component.ts
> +    onChanges(): void {
seems it should be private

2020-10-09 10:57 UTC, Betrozov commented on libs/core/src/lib/object-number/object-number.component.ts
> +    buildNumberPipeConfig(): void {
the same

2020-10-12 11:45 UTC, Betrozov requested changes

2020-10-12 11:45 UTC, Betrozov commented on libs/core/src/lib/object-number/object-number.component.ts
> +    private onChanges(): void {
all private methods should be with the prefix `_`

2020-10-12 11:47 UTC, mykolavorobiov approved these changes

2020-10-12 12:06 UTC, Betrozov approved these changes

2020-10-12 12:11 UTC, JKMarkowski approved these changes
LGTM

2020-10-13 07:27 UTC, merged