fix: Combobox improvements
SAP/fundamental-ngx pull request #3663
Opened 2020-10-21 15:35 UTC by JKMarkowski

#### Please provide a link to the associated issue.
part of: https://github.com/SAP/fundamental-ngx/issues/3641
#### Please provide a brief summary of this pull request.
There is:
- fixed enter on autofill
- fixed strange bug with button, so now it's not focusable even after click
- fixed compact mode
- added space key support.
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

2020-10-21 16:24 UTC, InnaAtanasova approved these changes

2020-10-22 01:41 UTC, droshev approved these changes

2020-10-23 09:09 UTC, salarenko requested changes

2020-10-23 09:09 UTC, salarenko commented on libs/core/src/lib/combobox/auto-complete.directive.ts
> +                event.preventDefault();
What are the reasons to mute the event here?

2020-10-23 09:09 UTC, salarenko commented on libs/core/src/lib/combobox/auto-complete.directive.ts
> +    private _moveIndicatorToLastLetter(): void {
I think the name of the method does not match what the function is actually doing. It's moving the cursor after the last character not "to the last letter".

2020-10-23 20:34 UTC, mikerodonnell89 commented
These improvements look good but I just noticed this problem which appears to be pre-existing https://github.com/SAP/fundamental-ngx/issues/3687

2020-10-23 20:34 UTC, mikerodonnell89 approved these changes

2020-10-24 13:48 UTC, merged