fix: (Core) cursor on disabled Switch should not be pointer
SAP/fundamental-ngx pull request #3769
Opened 2020-11-06 08:17 UTC by olshansky

#### Please provide a link to the associated issue.
Closes https://github.com/SAP/fundamental-ngx/issues/3720
#### Please provide a brief summary of this pull request.
![switch-disabled](https://user-images.githubusercontent.com/14160094/98342438-13990a00-2019-11eb-9c52-7a03dad03caa.gif)

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2020-11-06 10:46 UTC, JKMarkowski commented on libs/core/src/lib/switch/switch.component.html
> +<label class="fd-switch__label" (click)="focus()" [ngStyle]="{ cursor: disabled ? 'not-allowed' : 'pointer'}">
I think this cursor should be auto

2020-11-06 10:56 UTC, salarenko requested changes
We should just patch the styles here:
```
.fd-switch.is-disabled {
    cursor: not-allowed;
}
```

2020-11-06 12:52 UTC, olshansky commented
> We should just patch the styles here:
> 
> ```
> .fd-switch.is-disabled {
>     cursor: not-allowed;
> }
> ```

@salarenko unfortunately, it won't work
![switch-disabled](https://user-images.githubusercontent.com/14160094/98368102-6e455c80-203f-11eb-9504-5e563869075e.gif)

2020-11-06 12:55 UTC, olshansky commented on libs/core/src/lib/switch/switch.component.html
> +<label class="fd-switch__label" (click)="focus()" [ngStyle]="{ cursor: disabled ? 'not-allowed' : 'pointer'}">
@JKMarkowski fixed

2020-11-09 09:13 UTC, salarenko approved these changes

2020-11-09 18:09 UTC, droshev approved these changes

2020-11-09 18:17 UTC, merged