fix: (Core) add delete button support in tokenizer
SAP/fundamental-ngx pull request #3907
Opened 2020-11-20 10:44 UTC by JKMarkowski

#### Please provide a link to the associated issue.
part of: #3786

#### Please provide a brief summary of this pull request.
There is added `delete` button support for tokenizer

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

2020-11-20 14:09 UTC, InnaAtanasova requested changes
Deleting tokens with the `delete` key works only in Multi Input. In the Token documentation (Tokenizer including) it's not working. 
Also, I believe Deno wanted to have the option to delete a Token once you click in the input field where you create new tokens. Expected behaviour: in Tokenizer, click to create a new Token, press `delete`, the last token is focused, press `delete` again and the token will be deleted. The focus is now on the next token and it can be deleted by a single `delete` press.

2020-11-23 17:42 UTC, InnaAtanasova commented
Looks great now! Thanks for fixing it

2020-11-23 17:42 UTC, InnaAtanasova approved these changes

2020-11-23 18:17 UTC, Betrozov approved these changes

2020-11-24 08:57 UTC, merged