fix: (Core) Throw error on theme switcher via url, when router is not imported
SAP/fundamental-ngx pull request #3962
Opened 2020-11-30 13:41 UTC by JKMarkowski

#### Please provide a brief summary of this pull request.
There is a need to handle lack of router module import, when theme switching via url is enabled
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

2020-11-30 17:07 UTC, InnaAtanasova requested changes

2020-11-30 17:07 UTC, InnaAtanasova commented on libs/core/src/lib/utils/consts/error-messages.ts
> +export const THEME_SWITCHER_ROUTER_MISSING_ERROR = `You need to import RouterModule, to enable setting theme via url.`
Discussed with Jessie and it should be `You need to import RouterModule to enable theme settings via the url.`

2020-12-01 00:59 UTC, droshev commented
@JKMarkowski do you think it is worth mentioning on the doc example too?

2020-12-01 08:13 UTC, salarenko approved these changes

2020-12-01 13:00 UTC, katekozlowska approved these changes
LGTM

2020-12-01 14:00 UTC, InnaAtanasova approved these changes

2020-12-01 15:04 UTC, merged