fix: (Platform) Position of context menu on ActionBar doc page
SAP/fundamental-ngx pull request #4005
Opened 2020-12-02 20:42 UTC by KevinOkamoto

#### Please provide a link to the associated issue.

#3977

#### Please provide a brief summary of this pull request.

Added CDK overlay CSS required for the menu dropdowns used in the ActionBar.

<img width="1179" alt="Screen Shot 2020-12-02 at 12 42 14 PM" src="https://user-images.githubusercontent.com/48103491/100928999-d569fb80-349b-11eb-963e-cf87ed43395e.png">

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

2020-12-02 22:35 UTC, InnaAtanasova approved these changes

2020-12-03 07:59 UTC, olshansky approved these changes

2020-12-03 09:07 UTC, Betrozov requested changes

2020-12-03 09:07 UTC, Betrozov commented on apps/docs/src/styles.scss
> +@import '~@angular/cdk/overlay-prebuilt.css';
already fixed in this [PR](https://github.com/SAP/fundamental-ngx/pull/3985)

2020-12-03 14:49 UTC, KevinOkamoto commented
Closing this PR as it has already been addressed in PR #3985.

2020-12-03 14:49 UTC, closed without merging