fix: add action sheet to wizard
SAP/fundamental-ngx pull request #4007
Opened 2020-12-03 01:14 UTC by mikerodonnell89

#### Please provide a link to the associated issue.

fixes #3751 

#### Please provide a brief summary of this pull request.

This PR adds the action sheet to the wizard when the wizard width is small, causing the steps to stack.  Action sheet currently does not open if none of the stacked items have been previously visited - will address that in another ticket

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2020-12-03 09:10 UTC, Betrozov approved these changes

2020-12-03 16:54 UTC, InnaAtanasova approved these changes

2020-12-04 09:22 UTC, salarenko requested changes
- [ ] When resizing the wizard, wizard step marked as selected is changing
![selection-changed-resize](https://user-images.githubusercontent.com/17496353/101145316-e6407b80-3619-11eb-9a91-ae07ce7389fe.gif)

- [ ] No step change when clicking on step subtitle
![clicking-subtitle](https://user-images.githubusercontent.com/17496353/101145447-14be5680-361a-11eb-94ee-fe023ad6da0f.gif)

- [ ] Should collapsed steps look like that?
![image](https://user-images.githubusercontent.com/17496353/101145492-24d63600-361a-11eb-9a13-597180d0ae2a.png)

Docs show something like:
![image](https://user-images.githubusercontent.com/17496353/101145815-98784300-361a-11eb-9c51-7eb42ea007e5.png)

2020-12-04 09:22 UTC, salarenko commented on libs/core/src/lib/wizard/wizard.component.ts
> +                        top:
Do you mind moving `this._elRef.nativeElement.querySelector('.' + WIZARD_NAVIGATION_CLASS)` to separate variable and:
``` 
this.wrapperContainer.nativeElement.scrollTo({ top: child.offsetTop - navigation.clientHeight, behavior: 'smooth' });
```

2020-12-04 16:11 UTC, mikerodonnell89 commented
> * [ ]  When resizing the wizard, wizard step marked as selected is changing
>   ![selection-changed-resize](https://user-images.githubusercontent.com/17496353/101145316-e6407b80-3619-11eb-9a91-ae07ce7389fe.gif)

@salarenko Are you sure you're not accidentally touching the mouse wheel here? That is the only way I have been able to recreate this.  Maybe the content height changing causes the div to scroll itself, those focusing the other step

2020-12-04 16:12 UTC, mikerodonnell89 commented
> * [ ]  No step change when clicking on step subtitle
>   ![clicking-subtitle](https://user-images.githubusercontent.com/17496353/101145447-14be5680-361a-11eb-94ee-fe023ad6da0f.gif)

Can't recreate this either

2020-12-04 16:13 UTC, mikerodonnell89 commented
> * [ ]  Should collapsed steps look like that?
>   ![image](https://user-images.githubusercontent.com/17496353/101145492-24d63600-361a-11eb-9a13-597180d0ae2a.png)

Are you talking about the centered text? That is coming directly from a recent change in action sheet so maybe that needs to get fixed there

2020-12-04 16:40 UTC, mikerodonnell89 commented
> Docs show something like:
> ![image](https://user-images.githubusercontent.com/17496353/101145815-98784300-361a-11eb-9c51-7eb42ea007e5.png)

This does happen too, it depends on # of steps, how they have been collapsed, which one you're on etc

![Screen Shot 2020-12-04 at 9 39 49 AM](https://user-images.githubusercontent.com/2471874/101189798-bfcc1180-3614-11eb-8afe-bd1937f21104.png)

2020-12-07 15:14 UTC, salarenko approved these changes

2020-12-07 15:27 UTC, merged