[WIP] fix - Programmatic selection
SAP/fundamental-ngx pull request #4055
Opened 2020-12-09 09:42 UTC by katekozlowska

#### Please provide a lignk to the associated issue.

closes: https://github.com/SAP/fundamental-ngx/issues/3976

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

2020-12-09 20:55 UTC, InnaAtanasova approved these changes

2020-12-10 00:58 UTC, droshev requested changes
@katekozlowska can you update all labels of the PR?

2020-12-11 08:35 UTC, salarenko approved these changes

2020-12-11 12:11 UTC, JKMarkowski approved these changes

2020-12-11 14:47 UTC, droshev approved these changes
@katekozlowska at the end Inna did them

2020-12-14 14:02 UTC, merged