fix: Addressing Accessibility issue for the Object marker component
SAP/fundamental-ngx pull request #4081
Opened 2020-12-10 16:45 UTC by Lokanathan-k

fixing the Accessibility issue for the Object marker component

#### Please provide a link to the associated issue.

https://github.com/SAP/fundamental-ngx/issues/3558
https://github.com/SAP/fundamental-ngx/issues/3557
https://github.com/SAP/fundamental-ngx/issues/3821

#### Please provide a brief summary of this pull request.

fixed the tab index and Accessibility issues.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/master/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples

2020-12-10 17:07 UTC, KevinOkamoto requested changes
I think you need to edit the title of this PR to be in compliance with guidelines. You don't have a "(scope)" in your title.

2020-12-10 17:07 UTC, KevinOkamoto commented on apps/docs/src/app/core/component-docs/object-marker/examples/object-marker-example.component.html
> +<span fd-object-marker glyph="private" title="Private" aria-label="Favorite Private" aria-hidden="true"></span>
I think you need to set `aria-hidden=false` or else the screen reader will skip these.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute

2020-12-11 08:26 UTC, salarenko requested changes

2020-12-11 08:26 UTC, salarenko commented on .vscode/settings.json
> +}
Revert

2020-12-11 08:26 UTC, salarenko commented on apps/docs/src/app/core/component-docs/object-marker/examples/object-marker-example.component.html
> +<span fd-object-marker glyph="add-favorite" title="Favorite" aria-label="Favorite Icon" aria-hidden="false"></span>
Why are you using `aria-hidden` here?

2020-12-11 08:26 UTC, salarenko commented on apps/docs/src/app/core/component-docs/object-marker/examples/object-marker-text-example.component.html
> +    tabindex="0"
Isn't this weird that you need to explicitly add tabindex? It should not be like that, anchor tag is tabbable by default.

2020-12-14 11:08 UTC, Betrozov approved these changes

2020-12-14 13:35 UTC, salarenko approved these changes

2020-12-14 14:07 UTC, InnaAtanasova approved these changes

2020-12-14 16:19 UTC, KevinOkamoto approved these changes

2020-12-14 16:20 UTC, merged