test: file uploader component e2e-tests
SAP/fundamental-ngx pull request #4158
Opened 2020-12-21 13:47 UTC by nikvalor

#### Please provide a brief summary of this pull request.
Added file uploader component e2e-tests
#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2020-12-21 13:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/fundamental-ngx?pullRequest=4158) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/SAP/fundamental-ngx?pullRequest=4158) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: Seamoo13<br/>:x: anton<br/>:x: AntonOlkhovskyi<br/><hr/>**anton** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/fundamental-ngx?pullRequest=4158) it.</sub>

2020-12-21 16:32 UTC, AntonOlkhovskyi requested changes

2020-12-21 16:32 UTC, AntonOlkhovskyi commented on e2e/wdio/platform/pages/step-input.po.ts
> +        driver.keys(['Enter']);
please use sendKeys and for other places.

2020-12-21 16:32 UTC, AntonOlkhovskyi commented on e2e/wdio/platform/tests/combobox.e2e-spec.ts
> +describe('Combobox test suite', () => {
function ?

2020-12-22 08:22 UTC, nikvalor commented on e2e/wdio/driver/wdio.ts
> +        $$(selector)[index].clearValue();
It wasn't working in my case

2020-12-22 10:48 UTC, valorkin requested changes
please make specs more expressive and contain AAA notation
keep `expect`s and expected values in specs not in PO

2020-12-22 10:48 UTC, valorkin commented on e2e/wdio/platform/tests/combobox.e2e-spec.ts
> +        comboBoxPage.verifyComboBoxComponents(ComboboxData.activeTypeNames, ComboboxData.notActiveTypeNames);
this is over encapsulation, spec files should be readable in terms of `AAA`
where Arange is `open` in 90% of its

2020-12-22 10:48 UTC, valorkin commented on e2e/wdio/platform/tests/combobox.e2e-spec.ts
> +        comboBoxPage.verifyComboBoxComponents(ComboboxData.activeTypeNames, ComboboxData.notActiveTypeNames);
methods should makes sense only if they are used several times mostly

2020-12-22 10:48 UTC, valorkin commented on e2e/wdio/helper/assertion-helper.ts
> +export function compareDropDownOptions(firstOptionValue: string, inputOptionValue: string): void {
specific to dropdown, in global helper only global methods should be

2020-12-22 10:48 UTC, valorkin commented on e2e/wdio/platform/pages/step-input.po.ts
> +        webDriver.clearValue(input);
```        
webDriver.clearValue(input);
webDriver.setValue(input, 'invalid');
webDriver.sendKeys(['Enter']);
webDriver.waitForDisplayed(this.errorMessage);```

this is a good of reusable code to become method

2020-12-22 10:48 UTC, valorkin commented on e2e/wdio/platform/pages/step-input.po.ts
> +        checkTextValueContain(formStatusText, 'INVALID')
`INVALID` should be in spec as `expected` value

2020-12-22 14:40 UTC, Seamoo13 approved these changes

2020-12-23 08:45 UTC, AntonOlkhovskyi commented
@nikvalor Please reopen using SAP/fundamentals-ngx after comments fix, to make CI work for this PR.

2021-01-14 14:59 UTC, nikvalor commented
It was merged as part of https://github.com/SAP/fundamental-ngx/pull/4159/
Closed this one

2021-01-14 14:59 UTC, closed without merging