[WIP] Bug: (core) accessibility changes for object status.
SAP/fundamental-ngx pull request #4176
Opened 2020-12-22 12:17 UTC by Lokanathan-k

accessibility changes for object status

#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/3445
https://github.com/SAP/fundamental-ngx/issues/3447
https://github.com/SAP/fundamental-ngx/issues/3446
https://github.com/SAP/fundamental-ngx/issues/3444
https://github.com/SAP/fundamental-ngx/issues/3448
https://github.com/SAP/fundamental-ngx/issues/3449

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2020-12-23 04:00 UTC, DeepakSap14 approved these changes
LGTM

2020-12-23 04:07 UTC, sKudum approved these changes

2020-12-24 09:06 UTC, Betrozov requested changes

2020-12-24 09:06 UTC, Betrozov commented on apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-generic-text-example.component.html
> +        indicationColor="{{ item }}"
`indicationColor="{{ item }}"` => `[indicationColor]="item"`
`label="Indication Color{{ item }}"` => `[label]="'Indication Color' + item"`

2020-12-24 11:40 UTC, Betrozov approved these changes

2021-01-04 05:16 UTC, merged