fix: Deprecate popperjs, refactor menu component
SAP/fundamental-ngx pull request #4214
Opened 2020-12-30 13:08 UTC by JKMarkowski

#### Please provide a link to the associated issue.
closes: https://github.com/SAP/fundamental-ngx/issues/4203
#### Please provide a brief summary of this pull request.

There is added deprecation of popover directive. now simple popover can easly replace it. 
Also menu component
- Now uses popover service with CDK Overlay, instead of popover directive with popper.js.
- Mobile mode (false|true) can't be dynamically changed - I don't see any reason of having it

#### BREAKING CHANGES:
- Removed `[options]` from menu component

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-01-04 18:03 UTC, stefanoScalzo commented
When clicking on a menu item the popover stays in the upper left
![Uploading Screen Shot 2021-01-04 at 1.03.45 PM.png…]()

2021-01-04 18:05 UTC, stefanoScalzo commented
When clicking on the menu item once the options do not get shown. Only on the second click are they shown

2021-01-04 18:52 UTC, Betrozov approved these changes

2021-01-04 18:52 UTC, Betrozov commented on apps/docs/src/app/core/component-docs/popover-directive/popover-directive-header/popover-directive-header.component.html
> +    <fd-message-strip [type]="'warning'" [dismissible]="false">
`[type]="'warning'"` => `type="warning"`

2021-01-05 15:28 UTC, JKMarkowski commented
> When clicking on a menu item the popover stays in the upper left

Thanks for catching it

2021-01-06 21:48 UTC, InnaAtanasova requested changes
EDIT: Can't reproduce the first issue anymore, prob some bug with Netlify preview or cache
For the second issue I agree it's Popover related and can be addressed in a separate PR


1. Menu component:
when the menu from the first example is open and it reaches the bottom of the page it stops the page scrolling. Is it supposed to be like this?
<img width="1653" alt="Screen Shot 2021-01-06 at 4 41 00 PM" src="https://user-images.githubusercontent.com/39598672/103822467-31e1ad00-503e-11eb-89ff-68f2f3e3b0f3.png">

2. Popover body changes the position on detecting window ends. Is it supposed to be like this?:
<img width="1329" alt="Screen Shot 2021-01-06 at 4 39 04 PM" src="https://user-images.githubusercontent.com/39598672/103822566-67869600-503e-11eb-8d91-0b54cb6f4aae.png">
<img width="1269" alt="Screen Shot 2021-01-06 at 4 38 57 PM" src="https://user-images.githubusercontent.com/39598672/103822569-681f2c80-503e-11eb-9a66-c1e013dd803f.png">
<img width="1362" alt="Screen Shot 2021-01-06 at 4 36 17 PM" src="https://user-images.githubusercontent.com/39598672/103822571-68b7c300-503e-11eb-96a7-c2156fb2eb2d.png">
<img width="1328" alt="Screen Shot 2021-01-06 at 4 36 07 PM" src="https://user-images.githubusercontent.com/39598672/103822572-68b7c300-503e-11eb-8c5b-2b03a4544579.png">

3. Menu with submenu: click on the button, then hover the Vegetables list item and click on Onion. This happens: (happens for any item from the list, just provided the path to reproduce the image below)
<img width="840" alt="Screen Shot 2021-01-06 at 4 47 16 PM" src="https://user-images.githubusercontent.com/39598672/103822861-e1b71a80-503e-11eb-8f35-d00076e8ac11.png">

2021-01-08 19:35 UTC, mikerodonnell89 requested changes
If I open a menu, scroll to a different menu and try to open that popover, I scroll back to the first menu control (appears to be unique to menu, can't recreate on popover examples page. Possibly a result of automatically closing popover 1?)

![menuscroll](https://user-images.githubusercontent.com/2471874/104056488-cd456000-51ad-11eb-93c0-117fd7411e8c.gif)

2021-01-11 08:49 UTC, JKMarkowski commented
@mikerodonnell89 It happens, because when you close menu, trigger element is focused. Focusing element forces browser to scroll focused element.

2021-01-12 09:35 UTC, JKMarkowski commented
@mikerodonnell89 This issue has been fixed, thanks for noticing it

2021-01-12 15:45 UTC, InnaAtanasova approved these changes

2021-01-12 18:12 UTC, mikerodonnell89 approved these changes

2021-01-13 10:20 UTC, merged