fix: (Core|Platform) change image service
SAP/fundamental-ngx pull request #4215
Opened 2020-12-30 14:41 UTC by Betrozov

#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/4137
#### Please provide a brief summary of this pull request.
Image service changed
#### Please check whether the PR fulfills the following requirements

- [X] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [X] tests for the changes that have been done
- [X] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [X] update `README.md`
- [X] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [X] Documentation Examples
- [X] Stackblitz works for all examples

2020-12-30 14:46 UTC, IlyaSurmay requested changes

2020-12-30 14:46 UTC, IlyaSurmay commented on package.json
> +    "start": "node --max_old_space_size=12288 ./node_modules/@angular/cli/bin/ng serve",
plz revert

2020-12-30 14:46 UTC, IlyaSurmay commented on apps/docs/src/app/core/component-docs/tile/examples/launch-tile-example.component.html
> +        <span fd-tile-profile-img [backgroundImage]="'https://picsum.photos/id/1043/60/60'" aria-label="Profile Image"></span>
unnecessary binding

2020-12-30 14:46 UTC, IlyaSurmay commented on apps/docs/src/app/core/component-docs/tile/examples/launch-tile-example.component.html
> +        <span fd-tile-profile-img [backgroundImage]="'https://picsum.photos/id/1044/60/60'" aria-label="Profile Image"></span>
same

2020-12-30 14:46 UTC, IlyaSurmay commented on apps/docs/src/app/core/component-docs/tile/examples/slide-tile-example.component.html
> +    <div fd-tile-background-img [backgroundImage]="'https://picsum.photos/id/1015/200/200'"></div>
same

2020-12-30 16:09 UTC, IlyaSurmay approved these changes

2021-01-04 08:43 UTC, olshansky approved these changes

2021-01-04 08:51 UTC, kavya-b approved these changes

2021-01-04 18:42 UTC, stefanoScalzo approved these changes
LGTM

2021-01-05 15:14 UTC, merged