fix: (Platform) fix combobox styles
SAP/fundamental-ngx pull request #4278
Opened 2021-01-06 14:09 UTC by Betrozov

#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/4251
#### Please provide a brief summary of this pull request.
Fixed 2d part of issue `Combobox is missing styles`
Added `overlay-prebuilt.css` and `popover.css`
#### Please check whether the PR fulfills the following requirements

- [X] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [X] tests for the changes that have been done
- [X] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [X] update `README.md`
- [X] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [X] Documentation Examples
- [X] Stackblitz works for all examples

2021-01-06 14:59 UTC, olshansky approved these changes

2021-01-06 15:03 UTC, sKudum approved these changes

2021-01-06 15:03 UTC, sKudum commented on libs/platform/src/lib/components/form/combobox/combobox/combobox.component.scss
> +@import "~@angular/cdk/overlay-prebuilt";
Are we suppose to use fiori specifications for styles. Is it temporary import?

2021-01-06 15:09 UTC, sKudum commented on libs/platform/src/lib/components/form/combobox/combobox/combobox.component.scss
> +@import "~@angular/cdk/overlay-prebuilt";
Please ignore, I got it why we have this import. Thank You.approved

2021-01-07 09:29 UTC, fkolar requested changes

2021-01-07 09:29 UTC, fkolar commented on libs/platform/src/lib/components/form/combobox/combobox/combobox.component.scss
> +@import "~@angular/cdk/overlay-prebuilt";
This shoudl not be part of the component, overlay is used on other places, it should be some global imports

2021-01-07 09:31 UTC, fkolar commented
@JKMarkowski 
how do we work with this global style overlay for cdk ? Do we import this on some global level?

2021-01-08 10:24 UTC, JKMarkowski commented
> @JKMarkowski
> how do we work with this global style overlay for cdk ? Do we import this on some global level?


Hi @fkolar, we used to force users to import `@import "~@angular/cdk/overlay-prebuilt";` inside `angular.json`, but now it's in `popover-body.component.scss`. I see that combobox in platform doesn't use core's popover, so there is no other way, than just adding it into `combobox.component.scss`
Popover component has been improved it be used with diverged control/body [example](https://fundamental-ngx.netlify.app/#/core/popover#trigger). I encourage to use it - it's very flexible and uses cdk's overlay

2021-01-11 13:01 UTC, fkolar commented
> > @JKMarkowski
> > how do we work with this global style overlay for cdk ? Do we import this on some global level?
> 
> Hi @fkolar, we used to force users to import `@import "~@angular/cdk/overlay-prebuilt";` inside `angular.json`, but now it's in `popover-body.component.scss`. I see that combobox in platform doesn't use core's popover, so there is no other way, than just adding it into `combobox.component.scss`
> Popover component has been improved. It can be used with diverged control/body [example](https://fundamental-ngx.netlify.app/#/core/popover#trigger). I encourage to use this component - it's very flexible and uses cdk's overlay

@JKMarkowski ComboBox should be really performance driven component and I am not sure how this popover structure woudl be the overhead to this. Compared to using overlay directly. 

@Betrozov Any idea? Can we use pop over directly, isnt to big overhead?

2021-01-11 13:37 UTC, Betrozov commented
> > > @JKMarkowski
> > > how do we work with this global style overlay for cdk ? Do we import this on some global level?
> > 
> > 
> > Hi @fkolar, we used to force users to import `@import "~@angular/cdk/overlay-prebuilt";` inside `angular.json`, but now it's in `popover-body.component.scss`. I see that combobox in platform doesn't use core's popover, so there is no other way, than just adding it into `combobox.component.scss`
> > Popover component has been improved. It can be used with diverged control/body [example](https://fundamental-ngx.netlify.app/#/core/popover#trigger). I encourage to use this component - it's very flexible and uses cdk's overlay
> 
> @JKMarkowski ComboBox should be really performance driven component and I am not sure how this popover structure woudl be the overhead to this. Compared to using overlay directly.
> 
> @Betrozov Any idea? Can we use pop over directly, isnt to big overhead?

Hi @fkolar
I need to figure out how long it takes to switch to using the popup.
I'll back when the investigation will be done.

2021-01-26 19:00 UTC, fkolar approved these changes
Lets merge this and create Separate ISSUE where we can discuss how to integrate common component for CDK, its not that straight forward and simply replace this. We can also investigate as part of the ticket if the popover has all the required functionality or we need to extend it. 

Let' not get stuck and find out that we need to enhance one component before merging this PR.

2021-01-26 21:28 UTC, KevinOkamoto approved these changes

2021-01-28 09:51 UTC, JKMarkowski approved these changes

2021-01-28 18:05 UTC, Betrozov commented
The issue for discussion here - https://github.com/SAP/fundamental-ngx/issues/4513

2021-01-28 18:06 UTC, merged