fix (Core): multi-input and combobox filtering should use startsWith
SAP/fundamental-ngx pull request #4288
Opened 2021-01-08 00:20 UTC by mikerodonnell89

fixes #3532 

Updates multi-input and combobox so these components use `startsWith` filtering by default, rather than the previous `includes`.  Also updates docs

2021-01-08 10:15 UTC, Betrozov approved these changes

2021-01-08 15:45 UTC, InnaAtanasova requested changes
As per Fiori3 the default option should be `startsWith` but we need to keep both options and provide an option to the user to choose which one to use.

2021-01-11 12:55 UTC, JKMarkowski commented on apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-filter-example/multi-input-filter-example.component.ts
> +        return content.filter((item) => item.toLocaleLowerCase().includesWith(search));
I guess it should be `includes`

2021-01-11 12:56 UTC, JKMarkowski commented
@InnaAtanasova 

> As per Fiori3 the default option should be `startsWith` but we need to keep both options and provide an option to the user to choose which one to use.

I think this is what this PR brings, by default it's `startsWith`, but user can change is easily by writing his own compare method.

2021-01-11 13:35 UTC, InnaAtanasova commented
> @InnaAtanasova
> 
> > As per Fiori3 the default option should be `startsWith` but we need to keep both options and provide an option to the user to choose which one to use.
> 
> I think this is what this PR brings, by default it's `startsWith`, but user can change is easily by writing his own compare method.

If I remember correctly from the discussion we agreed to provide both options where the second option is given by a parameter. All other possible options can be implemented by the user.

2021-01-11 18:06 UTC, InnaAtanasova approved these changes

2021-01-12 09:34 UTC, JKMarkowski approved these changes

2021-01-14 01:34 UTC, merged