fix: (platform) asterisk not in a proper place in IE11 for form field
SAP/fundamental-ngx pull request #4291
Opened 2021-01-08 08:58 UTC by Lokanathan-k

asterisk not in a proper place in IE11 for form field

#### Please provide a link to the associated issue.

https://github.com/SAP/fundamental-ngx/issues/4234

#### Please provide a brief summary of this pull request.

<img width="832" alt="Screenshot 2021-01-08 at 2 26 17 PM" src="https://user-images.githubusercontent.com/53534379/103994805-87909380-51bd-11eb-90ed-95a17a399ae6.png">

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-01-08 10:16 UTC, Betrozov approved these changes

2021-01-08 16:05 UTC, InnaAtanasova requested changes
The PR title says Platform but the code you change is in Core.
You are fixing the IE11 issue but are introducing a bigger problem:
This is a very long text before your change:
<img width="2535" alt="Screen Shot 2021-01-08 at 11 02 05 AM" src="https://user-images.githubusercontent.com/39598672/104036364-51451b00-51a1-11eb-8351-696bf006ccd1.png">

This is the same case AFTER your change:
<img width="2552" alt="Screen Shot 2021-01-08 at 11 02 19 AM" src="https://user-images.githubusercontent.com/39598672/104036426-615cfa80-51a1-11eb-96c3-41d30342fada.png">


The overflowing rules are not applying and you can't see the `...` and the * anymore

2021-01-11 08:14 UTC, Lokanathan-k commented
> The PR title says Platform but the code you change is in Core.
> You are fixing the IE11 issue but are introducing a bigger problem:
> This is a very long text before your change:
> <img alt="Screen Shot 2021-01-08 at 11 02 05 AM" width="2000" src="https://user-images.githubusercontent.com/39598672/104036364-51451b00-51a1-11eb-8351-696bf006ccd1.png">
> 
> This is the same case AFTER your change:
> <img alt="Screen Shot 2021-01-08 at 11 02 19 AM" width="2000" src="https://user-images.githubusercontent.com/39598672/104036426-615cfa80-51a1-11eb-96c3-41d30342fada.png">
> 
> The overflowing rules are not applying and you can't see the `...` and the * anymore

HI @InnaAtanasova 

the css is loaded from the core component,on Analysing the issue found that the issue is on the form label component from core so the change is required on the core component.

<img width="1115" alt="Screenshot 2021-01-11 at 1 35 27 PM" src="https://user-images.githubusercontent.com/53534379/104158270-fdda0380-5412-11eb-90e5-50d641c7fd09.png">

Solution: instead of inline i have changed it to inline-block. so it works expected in IE11 too.

2021-01-11 13:30 UTC, InnaAtanasova commented
> > The PR title says Platform but the code you change is in Core.
> > You are fixing the IE11 issue but are introducing a bigger problem:
> > This is a very long text before your change:
> > <img alt="Screen Shot 2021-01-08 at 11 02 05 AM" width="2000" src="https://user-images.githubusercontent.com/39598672/104036364-51451b00-51a1-11eb-8351-696bf006ccd1.png">
> > This is the same case AFTER your change:
> > <img alt="Screen Shot 2021-01-08 at 11 02 19 AM" width="2000" src="https://user-images.githubusercontent.com/39598672/104036426-615cfa80-51a1-11eb-96c3-41d30342fada.png">
> > The overflowing rules are not applying and you can't see the `...` and the * anymore
> 
> HI @InnaAtanasova
> 
> the css is loaded from the core component,on Analysing the issue found that the issue is on the form label component from core so the change is required on the core component.
> 
> <img alt="Screenshot 2021-01-11 at 1 35 27 PM" width="1115" src="https://user-images.githubusercontent.com/53534379/104158270-fdda0380-5412-11eb-90e5-50d641c7fd09.png">
> 
> Solution: instead of inline i have changed it to inline-block. so it works expected in IE11 too.

@Lokanathan-k so why the title still says (Platform)?

2021-01-11 16:35 UTC, KevinOkamoto approved these changes

2021-01-11 16:38 UTC, InnaAtanasova approved these changes

2021-01-12 05:10 UTC, merged