fix: (Core) fix card accessibility issue
SAP/fundamental-ngx pull request #4330
Opened 2021-01-13 12:45 UTC by DeepakSap14

#### Please provide a link to the associated issue.
#3545 #3546 #3547 #3560 #3811 #3813 #3817 #3818

#### Please provide a brief summary of this pull request.
1. Fixes tab issues
2. screen reader issues

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-01-13 15:36 UTC, Betrozov requested changes

2021-01-13 15:36 UTC, Betrozov commented on apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.html
> +                <fd-card-content [attr.tabIndex]="0">
`[attr.tabIndex]="0"` => `tabIndex="0"`

2021-01-13 15:36 UTC, Betrozov commented on apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.html
> +                            <tr fd-table-row [main]="true" [activable]="true" [attr.tabIndex]="0">
the same

2021-01-13 15:36 UTC, Betrozov commented on apps/docs/src/app/core/component-docs/fixed-card-layout/examples/disabled-drag-drop/fixed-card-layout-disabled-drag.component.html
> +            <fd-card-content [attr.tabIndex]="0">
the same

2021-01-13 15:36 UTC, Betrozov commented on apps/docs/src/app/core/component-docs/fixed-card-layout/examples/mobile/fixed-card-layout-mobile-examples.component.html
> +                    <fd-card-content [attr.tabIndex]="0">
the same

2021-01-13 15:36 UTC, Betrozov commented on libs/core/src/lib/card/card.component.html
> +    <div *ngIf="badge" class="fd-badge" [attr.tabindex]="0">{{ badge }}</div>
the same

2021-01-13 15:36 UTC, Betrozov commented on libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.html
> +                (cdkDragDropped)="dragDrop($event)" [attr.tabindex]="0">
the same

2021-01-13 17:09 UTC, InnaAtanasova reviewed
Same comment as Yury

2021-01-14 15:37 UTC, InnaAtanasova requested changes
is it `tabindex` or `tabIndex`? You are using both

2021-01-14 15:37 UTC, InnaAtanasova commented on apps/docs/src/app/core/component-docs/card/examples/card-kpi-example.component.html
> +    <fd-card-content tabindex="0">
Typo

2021-01-14 15:56 UTC, Betrozov approved these changes

2021-01-14 16:54 UTC, InnaAtanasova approved these changes

2021-01-15 04:27 UTC, DeepakSap14 commented on apps/docs/src/app/core/component-docs/card/examples/bar-chart-list-card/bar-chart-list-card-example.component.html
> +        <ul class="fd-list fd-list--byline" [attr.tabindex]="0">
using tabindex now. removed Typo.
replcaed [attr.tabindex] with "tabindex".

2021-01-15 06:34 UTC, merged