test: add e2e test for date picker component
SAP/fundamental-ngx pull request #4347
Opened 2021-01-15 10:58 UTC by nikvalor

Covered date picker component 
#### Please provide a link to the associated issue.
[4346](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/4346)
#### Please provide a brief summary of this pull request.
Added e2e test for date picker component 

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-01-15 11:01 UTC, Seamoo13 requested changes

2021-01-15 11:01 UTC, Seamoo13 commented on e2e/wdio/platform/tests/date-picker.e2e-spec.ts
> +
please add the retires like below:

beforeAll(() => {
        datePickerPage.open();
        waitForPresent(datePickerPage.inputDatePicker);
    }, 1);

    afterEach(() => {
        refreshPage();
        waitForPresent(datePickerPage.inputDatePicker);
    }, 1);

2021-01-15 11:01 UTC, Seamoo13 commented on e2e/wdio/platform/tests/date-picker.e2e-spec.ts
> +        waitForPresent(datePickerPage.inputDatePicker);
I think you could move this waitForPresent to the open method in the PO file; I did it like that for all other test specs.

2021-01-15 12:38 UTC, Seamoo13 approved these changes

2021-01-15 14:06 UTC, InnaAtanasova commented
@nikvalor please maintain the checkboxes in the PR template. `Mergeable` check will fail if not all checkboxes are checked.

2021-01-15 16:05 UTC, droshev approved these changes

2021-01-16 13:58 UTC, AntonOlkhovskyi requested changes

2021-01-16 13:58 UTC, AntonOlkhovskyi commented on e2e/wdio/platform/pages/date-picker.po.ts
> +    activeInputDatePicker = '[ng-reflect-is-disabled="false"][aria-label="Date input"]';
try to avoid binding to the name

2021-01-16 13:58 UTC, AntonOlkhovskyi commented on e2e/wdio/platform/pages/date-picker.po.ts
> +    buttonGerman = 'button[ng-reflect-label="German"]'
try to avoid binding to the name

2021-01-16 13:58 UTC, AntonOlkhovskyi commented on e2e/wdio/platform/pages/date-picker.po.ts
> +    buttonBulgarian = 'button[ng-reflect-label="Bulgarian"]';
same

2021-01-16 13:58 UTC, AntonOlkhovskyi commented on e2e/wdio/platform/pages/date-picker.po.ts
> +    buttonSelectYear = '[aria-label="Select year"]';
same

2021-01-16 13:58 UTC, AntonOlkhovskyi commented on e2e/wdio/platform/pages/date-picker.po.ts
> +    buttonSelectMonth = '[aria-label="Select month"]';
same

2021-01-16 13:58 UTC, AntonOlkhovskyi commented on e2e/wdio/platform/pages/date-picker.po.ts
> +    currentYear = '[aria-label="Select year"]';
try to avoid binding to the name

2021-01-16 13:58 UTC, AntonOlkhovskyi commented on e2e/wdio/platform/pages/date-picker.po.ts
> +    buttonFirstYear = '(//td[contains(@id,"year")]/child::span)[1]'
check formatting  (;)

2021-01-16 13:58 UTC, AntonOlkhovskyi commented on e2e/wdio/platform/pages/date-picker.po.ts
> +    datePickerInputByIndex = (index: string) => {
look like it is auto-generated  id's
maybe better use fd-popover tag with index?

2021-01-16 13:58 UTC, AntonOlkhovskyi commented on e2e/wdio/platform/pages/date-picker.po.ts
> +    filterCaledarValue = (name: string) => {
(name: string): string

2021-01-16 13:58 UTC, AntonOlkhovskyi commented on e2e/wdio/platform/tests/date-picker.e2e-spec.ts
> +    it('verify user is cannot select mutlitple dates', () => {
typo

2021-01-16 13:58 UTC, AntonOlkhovskyi commented on e2e/wdio/platform/pages/date-picker.po.ts
> +    filterCaledarValue = (name: string) => {
Caledar typo

2021-01-19 04:13 UTC, AntonOlkhovskyi approved these changes

2021-01-19 11:46 UTC, merged