Test/formatted text
SAP/fundamental-ngx pull request #4394
Opened 2021-01-19 23:11 UTC by AntonOlkhovskyi

#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/4313
#### Please provide a brief summary of this pull request.
e2e tests for the formatted text component
#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-01-20 08:33 UTC, Seamoo13 requested changes

2021-01-20 08:33 UTC, Seamoo13 commented on e2e/wdio/core/tests/formatted-text.e2e-spec.ts
> +import formattedTextData from '../fixtures/appData/formatted-text-content';
Please add the object destruction we discussed on the call today

2021-01-20 08:33 UTC, Seamoo13 commented on e2e/wdio/core/pages/formatted-text.po.ts
> +    root = '#page-content';
you aren't using 'root' anywhere, please delete it

2021-01-20 08:33 UTC, Seamoo13 commented on e2e/wdio/core/fixtures/appData/formatted-text-content.ts
> +    custom_style_2_FF: 'color:#1a0dab;font-size:14px;'
did you check that these custom_styles work on safari? Just thinking ahead, we won't have safari and IE skipped forever.

2021-01-20 09:45 UTC, nikvalor commented on e2e/wdio/helper/common-helper.ts
> +export function checkLinkTargetDestination(element, site: string): void {
element: string

2021-01-21 09:16 UTC, Betrozov approved these changes

2021-01-21 10:24 UTC, Seamoo13 approved these changes

2021-01-21 10:25 UTC, valorkin commented on e2e/wdio/core/tests/formatted-text.e2e-spec.ts
> +    const {
this can be done when you import

2021-01-21 10:29 UTC, valorkin commented on e2e/wdio/core/tests/formatted-text.e2e-spec.ts
> +        expect(true).toBe(false, 'Alert is present on the screen ');
why what and how?

2021-01-21 10:35 UTC, valorkin approved these changes
LGTM

2021-01-21 12:48 UTC, merged