feat: (Core) introduce ControlValueAccessor to SegmentedButton
SAP/fundamental-ngx pull request #4579
Opened 2021-02-04 14:59 UTC by JKMarkowski

#### Please provide a link to the associated issue.

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-02-12 11:15 UTC, Betrozov requested changes

2021-02-12 17:05 UTC, mikerodonnell89 commented
On the "pagination per page" example, I have to double-click the segmented button to show it as selected

2021-02-12 17:08 UTC, mikerodonnell89 requested changes

2021-02-12 17:08 UTC, mikerodonnell89 commented on apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-complex-i18n-example/date-picker-complex-i18n-example.component.html
> -        [class]="isSelected('bg')"
`isSelected` function can be removed from typescript as well

2021-02-12 17:08 UTC, mikerodonnell89 commented on apps/docs/src/app/core/component-docs/tabs/examples/tab-selection-example/tab-selection-example.component.html
> +    <button fd-button label="Tab 1" (click)="tab1.open(true)"></button>
missing `<fd-segmented-button>` element

2021-02-15 09:05 UTC, JKMarkowski commented on libs/core/src/lib/segmented-button/segmented-button.component.ts
> +            .subscribe(_ => {
@Betrozov `ViewChildren`/`ContentChildren` Queries are unsubscribed upon destroy undet the hood

2021-02-15 09:22 UTC, JKMarkowski commented on apps/docs/src/app/core/component-docs/tabs/examples/tab-selection-example/tab-selection-example.component.html
> +    <button fd-button label="Tab 1" (click)="tab1.open(true)"></button>
It's not needed there

2021-02-15 11:42 UTC, JKMarkowski commented on apps/docs/src/app/core/component-docs/segmented-button/examples/segmented-button-form-example/segmented-button-form-example.component.html
> +        <small>value: {{customForm.controls?.disabled.value}} </small>
Added

2021-02-15 11:43 UTC, JKMarkowski commented
> On the "pagination per page" example, I have to double-click the segmented button to show it as selected
Hi @mikerodonnell89 I'm not able to fix it, I guess it's because of lack of change detection on template passed to pagination, but this bug is stlil there, when changeDetection is manually forced.

2021-02-15 12:01 UTC, JKMarkowski commented
Hi @mikerodonnell89  and @Betrozov thanks for review. Your comments have been addressed

2021-02-15 12:30 UTC, Betrozov approved these changes

2021-02-17 23:10 UTC, mikerodonnell89 commented on apps/docs/src/app/core/component-docs/tabs/examples/tab-selection-example/tab-selection-example.component.html
> +    <button fd-button label="Tab 1" (click)="tab1.open(true)"></button>
Apologies, you are correct

2021-02-22 19:29 UTC, mikerodonnell89 approved these changes

2021-02-23 13:35 UTC, merged