fix: improvements to the wizard in dialog
SAP/fundamental-ngx pull request #4580
Opened 2021-02-04 17:38 UTC by mikerodonnell89

fixes #4342

2021-02-05 10:28 UTC, Betrozov requested changes

2021-02-05 10:28 UTC, Betrozov commented on apps/docs/src/app/core/component-docs/wizard/examples/wizard-dialog-example.component.html
> +            <div fd-bar [barDesign]="'floating-footer'">
unnecessary binding
`[barDesign]="'floating-footer'"` -> `barDesign="floating-footer"`

2021-02-05 10:28 UTC, Betrozov commented on apps/docs/src/app/core/component-docs/wizard/examples/wizard-mobile-example.component.ts
> +        }
please decrease nesting
```suggestion
        if (event !== 'current') {
            return;
        }

        if (exampleNumber === 1) {
            this.example1goToStep(stepNumber);
        } else if (exampleNumber === 2) {
            this.example2goToStep(stepNumber);
        }
```

2021-02-05 10:28 UTC, Betrozov commented on libs/core/src/lib/wizard/wizard.component.ts
> +            }
```suggestion
            const wizardTallContent = wizard.querySelector(`.${WIZARD_TALL_CONTENT_CLASS}`);
            const wizardContainerWrapper = wizard.querySelector(`.${WIZARD_CONTAINER_WRAPPER_CLASS}`);

            if (wizardTallContent.offsetHeight < wizardContainerWrapper.offsetHeight) {
                wizardTallContent.style.height = `calc(100vh - ${combinedHeight}px)`;
            } else {
                wizardTallContent.style.paddingBottom = '24px';
            }
```

2021-02-08 09:16 UTC, JKMarkowski reviewed
Hi @mikerodonnell89 check my comment regarding typing, also let's propagate it to any other example. Rest LGTM

2021-02-08 09:16 UTC, JKMarkowski commented on apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.ts
> +
Can this `event` have more specific type?

2021-02-08 09:16 UTC, JKMarkowski commented on apps/docs/src/app/core/component-docs/wizard/examples/wizard-customizable-example.component.ts
> +
Can this event have more specific type?

2021-02-10 12:44 UTC, Betrozov approved these changes

2021-02-10 20:26 UTC, InnaAtanasova approved these changes

2021-02-10 20:28 UTC, InnaAtanasova approved these changes

2021-02-11 11:27 UTC, JKMarkowski approved these changes
LGTM

2021-02-11 23:35 UTC, merged