fix: (Core) Select custom item styles
SAP/fundamental-ngx pull request #4603
Opened 2021-02-08 09:19 UTC by sKudum

#### Please provide a link to the associated issue.
closes #4596

#### Please provide a brief summary of this pull request.
Updating styles for custom example.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ n/a] update `README.md`
- [n/a ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-02-08 09:36 UTC, JKMarkowski requested changes
Hi @sKudum Could you rename this PR to `docs: (...`? It's related only to documentation. Rest LGTM

2021-02-08 17:11 UTC, KevinOkamoto requested changes
Instead of adding padding to both sides, I think you should add a conditional RTL selector rule. See https://github.com/SAP/fundamental-ngx/blob/main/libs/core/src/lib/tabs/tab-item-expand/tab-item-expand.component.scss

2021-02-09 00:05 UTC, mikerodonnell89 approved these changes

2021-02-09 14:45 UTC, KevinOkamoto approved these changes

2021-02-10 10:56 UTC, JKMarkowski approved these changes

2021-02-10 10:56 UTC, merged