test: (e2e) add quick view e2e tests
SAP/fundamental-ngx pull request #4606
Opened 2021-02-08 11:44 UTC by nikvalor

#### Please provide a link to the associated issue.

[4548](https://app.zenhub.com/workspaces/fundamental-library-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/4548)

#### Please provide a brief summary of this pull request.

Covered quick view component on Core

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-02-08 12:06 UTC, Seamoo13 requested changes

2021-02-08 12:06 UTC, Seamoo13 commented on e2e/wdio/core/tests/quick-view.e2e-spec.ts
> +    });
please add the retry to the afterEach hook

2021-02-08 12:06 UTC, Seamoo13 commented on e2e/wdio/core/tests/quick-view.e2e-spec.ts
> +        checkPopoverInfo()
missing ; in a couple places

2021-02-08 12:06 UTC, Seamoo13 commented on e2e/wdio/core/tests/quick-view.e2e-spec.ts
> +        checkPopoverInfo()
missing ; in a couple places

2021-02-08 16:06 UTC, valorkin approved these changes

2021-02-08 16:18 UTC, Seamoo13 approved these changes

2021-02-08 16:24 UTC, Betrozov approved these changes

2021-02-09 16:13 UTC, AntonOlkhovskyi approved these changes

2021-02-10 08:57 UTC, merged