fix: (Core) Add token validate function to MultiInput
SAP/fundamental-ngx pull request #4621
Opened 2021-02-09 11:21 UTC by JKMarkowski

#### Please provide a link to the associated issue.
part of https://github.com/SAP/fundamental-ngx/issues/4483
#### Please provide a brief summary of this pull request.
There is added multi input new token validation method.
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-02-10 12:47 UTC, Betrozov requested changes

2021-02-10 12:47 UTC, Betrozov commented on apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-new-tokens-example/multi-input-new-tokens-example.component.ts
> +        return value && value.length >= 3
```suggestion
        return value?.length >= 3
```

2021-02-10 12:47 UTC, Betrozov commented on libs/core/src/lib/multi-input/multi-input.component.ts
>      private defaultDisplay(str: string): string {
please add `_`

2021-02-10 12:47 UTC, Betrozov commented on libs/core/src/lib/multi-input/multi-input.component.ts
>      private defaultParse(str: string): string {
the same

2021-02-10 12:47 UTC, Betrozov commented on libs/core/src/lib/multi-input/multi-input.component.ts
> +    private defaultTokenValidate(str: string): boolean {
the same

2021-02-10 16:01 UTC, mikerodonnell89 approved these changes

2021-02-10 16:02 UTC, mikerodonnell89 commented
Looks good after addressing @Betrozov 's comments

2021-02-11 11:40 UTC, JKMarkowski commented
@Betrozov Thanks for comments, could you recheck it now?

2021-02-11 16:06 UTC, droshev approved these changes

2021-02-11 23:16 UTC, merged