fix: (Platform) Value help dialog - styles mismatching
SAP/fundamental-ngx pull request #4661
Opened 2021-02-15 00:33 UTC by mykolavorobiov

#### Please provide a link to the associated issue.

https://app.zenhub.com/workspaces/fundamental-library-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/4594

#### Please provide a brief summary of this pull request.

Fixed styles mismatching and related behaviour with conditions

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] Documentation Examples

2021-02-15 02:22 UTC, kavya-b commented on libs/platform/src/lib/components/value-help-dialog/components/define-tab/define-tab.component.ts
> +  _onSelectStrategy(): void {
`@hidden` and private may be needed?

2021-02-15 02:23 UTC, kavya-b commented on libs/platform/src/lib/components/value-help-dialog/components/select-tab/select-tab.component.scss
> +    // &__advanced-search {
can we remove this commented code?

2021-02-15 02:26 UTC, kavya-b commented on libs/platform/src/lib/components/value-help-dialog/value-help-dialog/value-help-dialog.component.scss
> +            padding-left: 2rem;
common values like 2rem here can be reused through a variable.

2021-02-15 02:34 UTC, kavya-b commented
On selecting all items in the table, the tokenizer overflows beyond the dialog:
![image](https://user-images.githubusercontent.com/53509521/107899479-64979300-6f64-11eb-91d6-97119dcbacf3.png)

2021-02-15 18:25 UTC, mykolavorobiov commented on libs/platform/src/lib/components/value-help-dialog/components/select-tab/select-tab.component.scss
> +    // &__advanced-search {
Removed

2021-02-15 18:25 UTC, mykolavorobiov commented on libs/platform/src/lib/components/value-help-dialog/components/define-tab/define-tab.component.ts
> +  _onSelectStrategy(): void {
Added

2021-02-16 04:07 UTC, kavya-b commented on libs/platform/src/lib/components/value-help-dialog/components/define-tab/define-tab.component.html
> +            <!-- <div fdLayoutGridRow> -->
can the commented code be removed?

2021-02-16 04:10 UTC, kavya-b approved these changes
minor comment, LGTM otherwise.

2021-02-16 17:45 UTC, mikerodonnell89 requested changes
Few things:

1. "hide all filters" button is misaligned with filter inputs, missing `0.25rem` padding bottom from the specs:
![Screen Shot 2021-02-16 at 10 16 56 AM](https://user-images.githubusercontent.com/2471874/108098233-5d45b780-7040-11eb-9353-fde7df03fd71.png)

2. Bottom right clear button should be compact, as well as the tokenizer
![Screen Shot 2021-02-16 at 10 39 36 AM](https://user-images.githubusercontent.com/2471874/108100574-52d8ed00-7043-11eb-8907-a30af8c0a7c8.png)

3. In the specs the table does not have vertical column borders, you can use `[noBorderY]` input for that

4. The linked issue says that the specs do not mention pagination but it is still present here... is infinite scroll supposed to be used instead?

5. I would think that these two need to be left aligned, not centered
![Screen Shot 2021-02-16 at 10 43 57 AM](https://user-images.githubusercontent.com/2471874/108101035-f0ccb780-7043-11eb-83b3-68c53ebeba57.png)

2021-02-24 09:11 UTC, Betrozov approved these changes

2021-02-25 10:54 UTC, JKMarkowski approved these changes
LGTM

2021-03-06 00:01 UTC, mikerodonnell89 approved these changes

2021-04-01 14:48 UTC, Seamoo13 commented
- [ ] 1. for define conditions tab and custom strategy labels examples, styles don't match. borders cutoff/hidden
![Screenshot at 2021-04-01 17-36-35](https://user-images.githubusercontent.com/47522152/113311046-8f218d80-9311-11eb-9058-ac8ab46f7705.png)
![2021-04-01_5](https://user-images.githubusercontent.com/47522152/113311050-9052ba80-9311-11eb-93b7-93d4abac849e.png)
![Screenshot at 2021-04-01 17-35-36](https://user-images.githubusercontent.com/47522152/113311052-9052ba80-9311-11eb-95a9-ed99588da007.png)
![2021-04-01_4](https://user-images.githubusercontent.com/47522152/113311058-90eb5100-9311-11eb-984b-f4fca604e96b.png)
![Screenshot at 2021-04-01 17-43-40](https://user-images.githubusercontent.com/47522152/113311282-d1e36580-9311-11eb-8dd6-c0d19d630465.png)

2021-04-02 12:27 UTC, Seamoo13 approved these changes

2021-04-02 14:03 UTC, merged