test(e2e): action bar core
SAP/fundamental-ngx pull request #4703
Opened 2021-02-16 19:18 UTC by AntonOlkhovskyi

#### Please provide a link to the associated issue.

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-02-17 14:45 UTC, Seamoo13 requested changes

2021-02-17 14:45 UTC, Seamoo13 commented on e2e/wdio/core/fixtures/appData/action-bar-contents.ts
> +export const
please use export const for each item as previously agreed on

2021-02-17 14:45 UTC, Seamoo13 commented on e2e/wdio/core/tests/action-bar.e2e-spec.ts
> +            checkButtonHoverState(actionBarBackButtonBackButton, backButtonExample + backButtonHoverState, 'Back');
let's make the button names variables too, you use them multiple times and they could change. 'back', 'cancel' etc.

2021-02-17 14:45 UTC, Seamoo13 commented on e2e/wdio/core/tests/action-bar.e2e-spec.ts
> +    } = new ActionBarPo();
why = new ActionBarPO() instead of actionBarPage? Is there a difference? My refactoring PR uses = actionBarPage

2021-02-17 14:47 UTC, Seamoo13 commented
Why are axe reports added here? Shouldn't they be in the accessibility PoC PR?

2021-02-18 09:30 UTC, Seamoo13 approved these changes

2021-02-23 09:18 UTC, nikvalor approved these changes

2021-02-26 20:45 UTC, InnaAtanasova approved these changes

2021-03-01 08:36 UTC, merged