fix: (Platform) defect hunting issues in approval flow
SAP/fundamental-ngx pull request #4753
Opened 2021-02-23 12:39 UTC by IlyaSurmay

#### Please provide a link to the associated issue.

fixes #4734

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-02-23 13:47 UTC, Betrozov approved these changes

2021-02-23 14:06 UTC, olshansky approved these changes

2021-02-23 14:48 UTC, kavya-b approved these changes

2021-02-23 17:26 UTC, mykolavorobiov requested changes

2021-02-23 17:26 UTC, mykolavorobiov commented on libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-node.component.html
> +                <div fd-menu-interactive i18n="@@platformApprovalFlowNodeDelete">Remove</div>
```suggestion
                <div fd-menu-interactive i18n="@@platformApprovalFlowNodeRemove">Remove</div>
```

2021-02-24 08:29 UTC, dimamarksman approved these changes

2021-02-24 11:56 UTC, mykolavorobiov approved these changes

2021-02-24 12:30 UTC, merged