fix: (platform) updating the documentation and addressing bug for compact
SAP/fundamental-ngx pull request #4764
Opened 2021-02-24 06:03 UTC by Lokanathan-k

updating the documentation and addressing bug for compact

#### Please provide a link to the associated issue.

https://github.com/SAP/fundamental-ngx/issues/4745

#### Please provide a brief summary of this pull request.

added autofocs to the input component to handling default focus on load.
fixed the compact issue.
removed the unwanted documentation in the file.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-02-24 09:48 UTC, manu-kr commented on libs/platform/src/lib/components/form/multi-input/multi-input.component.ts
> +    autofocus: boolean;
Add typedocs for the fields

2021-02-24 09:48 UTC, manu-kr commented on libs/platform/src/lib/components/form/multi-input/multi-input.component.ts
> +        /** @hidden */ readonly cd: ChangeDetectorRef,
Check code formatting, after '/**@hidden*/' there should be a new line.

2021-02-24 09:48 UTC, manu-kr commented on libs/platform/src/lib/components/form/multi-input/multi-input.component.html
> +                autofocus="autofocus"
arai-label and title is missing for the input field

2021-02-24 15:23 UTC, Betrozov approved these changes

2021-03-01 13:23 UTC, JKMarkowski commented
I see there are no hover effects and checkbox elements inside multi input - is it on purpose?

![Peek 2021-03-01 14-22](https://user-images.githubusercontent.com/26483208/109502670-95fe7b80-7a99-11eb-833f-00b0790e8ea7.gif)

2021-03-01 17:30 UTC, Lokanathan-k commented
> I see there are no hover effects and checkbox elements inside multi input - is it on purpose?
> 
> ![Peek 2021-03-01 14-22](https://user-images.githubusercontent.com/26483208/109502670-95fe7b80-7a99-11eb-833f-00b0790e8ea7.gif)

@JKMarkowski since core has the multi input with checkbox, as discussed on the tech spec we will concentrating only on the different type of list  option. addressed the hover effect to the list

2021-03-03 10:42 UTC, Betrozov approved these changes

2021-03-03 10:56 UTC, sKudum approved these changes

2021-03-05 11:20 UTC, nikvalor commented
Project: allure-results CORE 
 Url: https://allure-results--core-pr-4764-da40iudb.web.app 
 This link will expire at Sun 04 Apr 2021 11:20:48 AM GMT

2021-03-05 11:33 UTC, nikvalor commented
Project: allure-results Platform B
 Url: https://allure-results--platform-b-pr-4764-wu36oboo.web.app 
 This link will expire at Sun 04 Apr 2021 11:33:06 AM GMT

2021-03-05 12:50 UTC, nikvalor commented
Project: allure-results Platform A 
 Url: https://allure-results--platform-a-pr-4764-11m907un.web.app 
 This link will expire at Sun 04 Apr 2021 12:50:26 PM GMT

2021-03-06 05:09 UTC, nikvalor commented
Project: null CORE 
 Url: null 
 This link will expire at

2021-03-06 05:23 UTC, nikvalor commented
Project: null Platform A 
 Url: null 
 This link will expire at

2021-03-06 05:27 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-10 06:56 UTC, nikvalor commented
Project: null CORE 
 Url: null 
 This link will expire at

2021-03-10 07:00 UTC, nikvalor commented
Project: null Platform A 
 Url: null 
 This link will expire at

2021-03-10 07:10 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-10 08:11 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-10 08:19 UTC, nikvalor commented
Project: null Platform A 
 Url: null 
 This link will expire at

2021-03-10 09:49 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-10 13:45 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-10 18:18 UTC, nikvalor commented
Project: null CORE 
 Url: null 
 This link will expire at

2021-03-10 18:24 UTC, nikvalor commented
Project: null Platform A 
 Url: null 
 This link will expire at

2021-03-10 18:25 UTC, nikvalor commented
Project: null CORE 
 Url: null 
 This link will expire at

2021-03-10 18:27 UTC, nikvalor commented
Project: null Platform A 
 Url: null 
 This link will expire at

2021-03-10 18:28 UTC, nikvalor commented
Project: null Platform A 
 Url: null 
 This link will expire at

2021-03-10 18:29 UTC, nikvalor commented
Project: null CORE 
 Url: null 
 This link will expire at

2021-03-10 18:36 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-10 18:40 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-10 18:41 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-11 05:45 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-12 11:23 UTC, nikvalor commented
Project: null Platform A 
 Url: null 
 This link will expire at

2021-03-12 11:23 UTC, nikvalor commented
Project: null CORE 
 Url: null 
 This link will expire at

2021-03-12 11:34 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-12 13:01 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-12 15:05 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-12 15:12 UTC, nikvalor commented
Project: null Platform A 
 Url: null 
 This link will expire at

2021-03-12 15:59 UTC, nikvalor commented
Project: null CORE 
 Url: null 
 This link will expire at

2021-03-13 15:25 UTC, droshev requested changes
Can you update the title by writing what has been fixed (e.g. `fix: fix the compact bug in action bar`) ?

When you quote issues that you are fixing you need to write something like:
```
fixes: #1234
```

2021-03-15 11:02 UTC, JKMarkowski approved these changes

2021-03-16 17:33 UTC, KevinOkamoto approved these changes

2021-03-17 10:08 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-17 10:10 UTC, nikvalor commented
Project: null Platform A 
 Url: null 
 This link will expire at

2021-03-17 10:13 UTC, nikvalor commented
Project: null CORE 
 Url: null 
 This link will expire at

2021-03-17 10:13 UTC, nikvalor commented
Project: null Platform A 
 Url: null 
 This link will expire at

2021-03-17 10:14 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-17 10:16 UTC, nikvalor commented
Project: null CORE 
 Url: null 
 This link will expire at

2021-04-05 19:37 UTC, droshev requested changes
Looks like this PR is addressing different things. Can you keep the changes addressing the one issue at the time? otherwise it is not easy to track what this PR is about.

2021-04-05 19:37 UTC, droshev commented on libs/platform/src/lib/components/base.ts
> +        this._router?.events.subscribe((event) => {
not needed change

2021-04-05 19:37 UTC, droshev commented on libs/platform/src/lib/components/base.ts
> +            this._subscriptions.add(
can you revert this?

2021-04-05 19:37 UTC, droshev commented on libs/platform/src/lib/components/form/base.input.ts
> +export abstract class BaseInput
all those changes in this file should be done in a separate PR where the documentation/formatting is addressed

2021-04-05 19:37 UTC, droshev commented on libs/platform/src/lib/components/form/collection-base.input.ts
> +    /** @hidden */
same as above

2021-04-05 19:37 UTC, droshev commented on libs/platform/src/lib/components/form/multi-input/base-multi-input.ts
> +        /** @hidden */
same as above

2021-04-07 06:17 UTC, puru-hk commented
Focus for the input field is not as per the fiori3 spec 
screenshot : 
![image](https://user-images.githubusercontent.com/32538291/113819450-f4083800-9796-11eb-939c-0d50bd8ae55f.png)

Expected: 
![image](https://user-images.githubusercontent.com/32538291/113819527-126e3380-9797-11eb-93eb-d8e19d2c907e.png)

2021-04-08 02:30 UTC, droshev requested changes
few points

2021-04-08 02:30 UTC, droshev commented on libs/platform/src/lib/components/base.ts
> +            this._subscriptions.add(this._contentDensityService._contentDensityListener.subscribe((density) => {
I think this is just a code reformatting, isn't it? If so, could you revert it?

2021-04-08 02:30 UTC, droshev commented on libs/platform/src/lib/components/form/base.input.ts
> +
revert the file

2021-04-08 02:30 UTC, droshev commented on libs/platform/src/lib/components/form/multi-input/base-multi-input.ts
> -    /** Turns on/off Adjustable Width feature */
was this an intentional input remove? If so then it has to be a breaking change PR

2021-04-08 02:30 UTC, droshev commented on libs/platform/src/lib/components/form/multi-input/multi-input.component.ts
> +    /** @hidden
can we revert this change ?

2021-04-08 02:30 UTC, droshev commented on libs/platform/src/lib/components/form/multi-input/multi-input.component.ts
> +    /** @hidden */
and those below

2021-04-08 02:30 UTC, droshev commented on libs/platform/src/lib/components/form/multi-input/multi-input.component.ts
> +        /** @hidden */
...until here

2021-04-15 09:43 UTC, puru-hk commented
All the below issues is fixed 
#4745
#4781
#4988

2021-04-15 09:44 UTC, puru-hk approved these changes

2021-04-16 09:40 UTC, droshev approved these changes
next time create a PR for each issue

2021-04-16 09:42 UTC, merged