bug: (Core) File uploader accessibilty defect #3497 and #3498
SAP/fundamental-ngx pull request #4845
Opened 2021-03-03 16:36 UTC by manu-kr

#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/3497
https://github.com/SAP/fundamental-ngx/issues/3498

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [NA] update `README.md`
- [NA] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-03-03 17:42 UTC, InnaAtanasova commented on apps/docs/src/app/core/component-docs/file-uploader/examples/file-uploader-drag-disabled-example/file-uploader-drag-disabled-example.component.html
> +    buttonAriaLabel="Drag a .png file on me!"
"Drag a .png file OVER me!"

2021-03-03 17:43 UTC, InnaAtanasova commented
Maybe I am missing something but why is this PR starting with `bug`?

2021-03-03 22:49 UTC, droshev requested changes
Can you update the title following the semantic versioning - `fix: `

2021-03-04 09:45 UTC, manu-kr commented on apps/docs/src/app/core/component-docs/file-uploader/examples/file-uploader-drag-disabled-example/file-uploader-drag-disabled-example.component.html
> +    buttonAriaLabel="Drag a .png file on me!"
Modified.

2021-03-09 22:34 UTC, droshev requested changes
The PR title doesn't help us understand what it is fixing

2021-03-10 04:56 UTC, manu-kr commented
> The PR title doesn't help us understand what it is fixing

>Modified PR title.

2021-03-10 18:58 UTC, droshev requested changes
I am not sure what value brings to our users this title:
`fix: (Core) fixes defect #3497 and #3498....
`
Modified.

2021-03-16 14:47 UTC, InnaAtanasova approved these changes

2021-03-16 16:41 UTC, droshev approved these changes

2021-03-17 05:22 UTC, merged