Feature/add feed input e2e tests core
SAP/fundamental-ngx pull request #4921
Opened 2021-03-15 09:18 UTC by nikvalor

#### Please provide a link to the associated issue.
[4920](https://app.zenhub.com/workspaces/fundamental-library-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/4920)
#### Please provide a brief summary of this pull request.
Added feed input e2e tests core

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-03-15 10:00 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-15 10:02 UTC, nikvalor commented
Project: null Platform A 
 Url: null 
 This link will expire at

2021-03-15 10:09 UTC, nikvalor commented
Project: null CORE 
 Url: null 
 This link will expire at

2021-03-15 12:37 UTC, InnaAtanasova reviewed
Please fix your PR title

2021-03-15 17:34 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-15 17:38 UTC, nikvalor commented
Project: null Platform A 
 Url: null 
 This link will expire at

2021-03-15 17:41 UTC, nikvalor commented
Project: null CORE 
 Url: null 
 This link will expire at

2021-03-15 18:36 UTC, InnaAtanasova commented
@nikvalor please address the checkboxes in the PR Template. Mergeable will not pass without this.

2021-03-16 23:31 UTC, droshev commented
@nikvalor We would need a doc explaining how to:
- address and fix failing tests
- regenerate new snapshots
- what needs to be done if we bring markup changes
- how we handle fork PRs
without a doc explaining all above we should not accept new tests

2021-03-18 08:56 UTC, Seamoo13 requested changes

2021-03-18 08:56 UTC, Seamoo13 commented on e2e/wdio/core/fixtures/testData/feed-input-tags.ts
> +
please remove extra lines

2021-03-18 08:56 UTC, Seamoo13 commented on e2e/wdio/core/tests/feed-input.e2e-spec.ts
> +    const feedInputPage = new FeedInputPo();
please create PO first
const feedInputPage = new FeedInputPO;
const {} = feedInputPage

to keep the same style in the tests

2021-03-18 08:56 UTC, Seamoo13 commented on e2e/wdio/core/tests/feed-input.e2e-spec.ts
> +            expect(getAttributeByNameArr(feedInputTextArea, 'placeholder')).toEqual(placeholder_array);
this only checks index 0, need to do like this:
expect(getAttributeByNAmeArr(feedInputTextArea, 'placeholder', i)).toEqual(placeholder_array[i]);

2021-03-18 08:56 UTC, Seamoo13 commented on e2e/wdio/core/tests/feed-input.e2e-spec.ts
> +            expect(getAttributeByName(feedInputAvatar, 'image')).not.toBeNull();
only checking index 0 on assertions, need to add 3rd variable 'i'
(feedInputAvatar, 'image', i)

2021-03-18 08:56 UTC, Seamoo13 commented on e2e/wdio/core/tests/feed-input.e2e-spec.ts
> +            expect(getAttributeByName(feedInputButton, 'aria-disabled', i)).toBe('true');
same as above

2021-03-18 15:13 UTC, Seamoo13 approved these changes

2021-03-19 16:59 UTC, InnaAtanasova approved these changes

2021-03-24 15:51 UTC, AntonOlkhovskyi requested changes

2021-04-05 11:26 UTC, AntonOlkhovskyi approved these changes

2021-04-05 12:25 UTC, merged