fix: (platform) updating the fcousable object of status indicator and adding clickable
SAP/fundamental-ngx pull request #4942
Opened 2021-03-17 10:04 UTC by Lokanathan-k

#### Please provide a link to the associated issue.

https://github.com/SAP/fundamental-ngx/issues/4869

#### Please provide a brief summary of this pull request.
updating the focusable object of status indicator
Focusable applied to all the tab able component and adding click feature to the component with cursor-type as pointer.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-03-17 10:50 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-17 10:52 UTC, nikvalor commented
Project: null Platform A 
 Url: null 
 This link will expire at

2021-03-17 10:55 UTC, nikvalor commented
Project: null Platform A 
 Url: null 
 This link will expire at

2021-03-17 10:55 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-17 10:55 UTC, nikvalor commented
Project: null CORE 
 Url: null 
 This link will expire at

2021-03-17 10:57 UTC, nikvalor commented
Project: null CORE 
 Url: null 
 This link will expire at

2021-03-17 13:22 UTC, InnaAtanasova requested changes

2021-03-17 13:22 UTC, InnaAtanasova commented on apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-clickable-type.component.html
> +    (click)="onCick()"
there's a typo, also it's good to have a more meaningful name for this function

2021-03-17 13:22 UTC, InnaAtanasova commented on apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-clickable-type.component.ts
> +    fillePercentage = 35;
I think there's a typo?

2021-03-17 13:22 UTC, InnaAtanasova commented on apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-clickable-type.component.ts
> +    onCick(): void {
typo

2021-03-17 13:22 UTC, InnaAtanasova commented on libs/core/src/lib/status-indicator/status-indicator.component.scss
>  .fd-status-indicator--xl__text {
It was missed during the prev PR review, but this class makes no sense in BEM. You can't have .block--modifier__element like in your case. `.fd-status-indicator` is the block. Then it should be followed by an element, something like: `.fd-status-indicator__text` and the modifier comes last as it's modifying the default state of an element: `.fd-status-indicator__text--xl`.

2021-03-17 18:40 UTC, nikvalor commented
Project: null Platform A 
 Url: null 
 This link will expire at

2021-03-17 18:42 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-17 18:51 UTC, nikvalor commented
Project: null CORE 
 Url: null 
 This link will expire at

2021-03-18 04:31 UTC, puru-hk approved these changes

2021-03-18 14:20 UTC, KevinOkamoto approved these changes

2021-03-19 16:55 UTC, InnaAtanasova requested changes

2021-03-19 16:55 UTC, InnaAtanasova commented on libs/core/src/lib/status-indicator/status-indicator.component.scss
> +.fd-status-indicator__text--negative {
This is again the same discussion we have in fund-styles PR. 
You have the following markup:
```
<div class="fd-status-indicator fd-status-indicator--negative">
    <span class="fd-status-indicator__text--lg fd-status-indicator__text--negative">35% </span>
</div>
```
You have the `--negative` modifier applied on two places which is not ok. 
You need to set it only on the parent level and then use specificity to change the color. It's not the same as for the size, as size can be different from the size of the parent (which I doubt will happen) but the color of the label should be the same as the color of the status indicator.

So you need to have:
```
.fd-status-indicator--negative {
    .fd-status-indicator__text {
         color: #b00;
         color: var(--sapNegativeElementColor,#b00)
     }
}

.fd-status-indicator--positive {
    .fd-status-indicator__text {
         color: #107e3e;
         color: var(--sapPositiveElementColor,#107e3e)
     }
}
```

This way you will have a modifier only on the parent level:
```
<div class="fd-status-indicator fd-status-indicator--negative">
    <span class="fd-status-indicator__text--lg">35% </span>
</div>
```

2021-03-19 16:55 UTC, InnaAtanasova commented on libs/core/src/lib/status-indicator/status-indicator.component.scss
> +.fd-status-indicator__text--xl {
these were renamed in fund-styles to label and this should be reflected here

2021-03-22 18:50 UTC, InnaAtanasova requested changes

2021-03-22 18:50 UTC, InnaAtanasova commented on libs/core/src/lib/status-indicator/status-indicator.component.html
> +    [ngClass]="'fd-status-indicator__label--' + size"
missing `class="fd-status-indicator__label"`

2021-03-23 14:18 UTC, InnaAtanasova approved these changes

2021-03-24 03:56 UTC, merged