test: (e2e) adde datetime picker e2e tests core
SAP/fundamental-ngx pull request #4956
Opened 2021-03-18 11:06 UTC by nikvalor

#### Please provide a link to the associated issue.
[datetime-picker](https://app.zenhub.com/workspaces/fundamental-library-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/4811)
#### Please provide a brief summary of this pull request.
test: (e2e) adde datetime picker e2e tests core

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-03-18 11:48 UTC, nikvalor commented
Project: null Platform B
 Url: null 
 This link will expire at

2021-03-18 11:51 UTC, nikvalor commented
Project: null Platform A 
 Url: null 
 This link will expire at

2021-03-18 12:54 UTC, nikvalor commented
Project: null CORE 
 Url: null 
 This link will expire at

2021-03-18 15:31 UTC, nikvalor commented
Project: null CORE 
 Url: null 
 This link will expire at

2021-03-18 16:18 UTC, Seamoo13 requested changes

2021-03-18 16:18 UTC, Seamoo13 commented on e2e/wdio/core/tests/date-time-picker.e2e-spec.ts
> +            expect(isElementDisplayed(calendarExpanded)).toBe(true);
need to add 'i'

2021-03-18 16:18 UTC, Seamoo13 commented on e2e/wdio/core/tests/date-time-picker.e2e-spec.ts
> +            expect(isElementClickable(disabledDateTimePickerInput)).toBe(false);
need to add 'i' to both of these

2021-03-25 10:55 UTC, AntonOlkhovskyi requested changes

2021-03-25 10:55 UTC, AntonOlkhovskyi commented on e2e/wdio/core/tests/date-time-picker.e2e-spec.ts
> +    it('verify on click on the date picker button', () => {
could you be more specific, what should happen en on that click ?

2021-03-25 10:55 UTC, AntonOlkhovskyi commented on e2e/wdio/core/tests/date-time-picker.e2e-spec.ts
> +    it('verify simple datetime picker', () => {
...has correct default date

2021-04-07 09:02 UTC, Seamoo13 requested changes

2021-04-07 09:02 UTC, Seamoo13 commented on e2e/wdio/platform/tests/date-time-picker.e2e-spec.ts
> +    fit('Verify When the user selects cancel the action is aborted and the input field remains unchanged.', () => {
please remove 'f'

2021-04-09 06:21 UTC, Seamoo13 approved these changes

2021-04-13 11:53 UTC, AntonOlkhovskyi approved these changes

2021-04-13 18:34 UTC, InnaAtanasova approved these changes

2021-04-15 11:20 UTC, merged