feat: (Platform) search field improved to support aria label attribute
SAP/fundamental-ngx pull request #5064
Opened 2021-04-01 12:36 UTC by platon-rov

#### Please provide a link to the associated issue.

Closes #3843.

#### Please provide a brief summary of this pull request.

* Improves Search Field Platform component to support `ariaLabel` property which sets `aria-label` for search input element to specify what search field is. 
* `ariaLabel` property set for Table Toolbar component of the Platform Table component (fix).

#### Please check whether the PR fulfills the following requirements

- [X] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [X] tests for the changes that have been done
- [X] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [X] Run npm run build-pack-library and test in external application

Documentation checklist:
- [X] update `README.md`
- [X] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [X] Documentation Examples
- [X] Stackblitz works for all examples

2021-04-01 13:54 UTC, Betrozov approved these changes

2021-04-01 13:55 UTC, Betrozov commented
please fix Travis

2021-04-05 20:00 UTC, InnaAtanasova commented
There's something wrong with the focus. Type something in the field, press Tab. The "clear" button should be focused but it's not.

2021-04-06 08:20 UTC, dimamarksman requested changes
Please see my comment

2021-04-06 08:20 UTC, dimamarksman commented on libs/platform/src/lib/components/search-field/search-field.component.ts
> +    @Input() ariaLabel: string;
Let's add `aria-labelledby` option as well so it can be used with the table toolbar

2021-04-06 08:20 UTC, dimamarksman commented on libs/platform/src/lib/components/table/components/table-toolbar/table-toolbar.component.html
> +            [ariaLabel]="_getSearchAriaLabel(counter)"
Let's generate unique id for the current toolbar label and pass this id to the `fdp-search-field` as `aria-labelledby` option.
In this case we don't need `_getSearchAriaLabel()`

2021-04-06 08:39 UTC, dimamarksman commented
> There's something wrong with the focus. Type something in the field, press Tab. The "clear" button should be focused but it's not.

@InnaAtanasova looks like this issue comes from fundamental-styles itself
https://github.com/SAP/fundamental-styles/blob/8fe03ce3c9af67e791a0e4b12f507c5ce9b940f9/src/input-group.scss#L210

2021-04-06 14:12 UTC, droshev requested changes
see my comments

2021-04-07 06:30 UTC, platon-rov commented
> There's something wrong with the focus. Type something in the field, press Tab. The "clear" button should be focused but it's not.

As Dmitriy mentioned - its related to the fundamental styles, so I created the issue there.

2021-04-07 19:33 UTC, InnaAtanasova commented
> > There's something wrong with the focus. Type something in the field, press Tab. The "clear" button should be focused but it's not.
> 
> As Dmitriy mentioned - its related to the fundamental styles, so I created the issue there.

Thanks for investigating. I know the issue is not related to this PR, that's why I didn't request changes but I noticed it while code review and thought it's good to mention it. Thanks for creating the issue in fund-styles

2021-04-07 19:33 UTC, InnaAtanasova approved these changes

2021-04-08 06:07 UTC, puru-hk commented
It is working as expected.

2021-04-08 06:07 UTC, puru-hk approved these changes

2021-04-08 06:55 UTC, platon-rov commented
@puru-hk e2e fails, please [check](https://travis-ci.com/github/SAP/fundamental-ngx/jobs/496624931). I've tried to update screenshots to get visual regression tests passing - but it didn't help, I guess some tests needs changes.

2021-04-09 20:44 UTC, mikerodonnell89 approved these changes

2021-04-12 17:55 UTC, droshev approved these changes

2021-04-13 08:47 UTC, merged