test: (e2e) added feed list item e2e core
SAP/fundamental-ngx pull request #5096
Opened 2021-04-08 07:57 UTC by nikvalor

#### Please provide a link to the associated issue.
[feed-list-item](https://app.zenhub.com/workspaces/fundamental-library-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/4928)
#### Please provide a brief summary of this pull request.
Added feed list item e2e core

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-04-09 06:28 UTC, Seamoo13 requested changes

2021-04-09 06:28 UTC, Seamoo13 commented on e2e/wdio/core/tests/feed-list-item.e2e-spec.ts
> +            expect(feedListItemPage.compareWithBaseline()).toBeLessThan(1);
please increase from 1 to 5

2021-04-09 06:28 UTC, Seamoo13 commented on e2e/wdio/core/tests/feed-list-item.e2e-spec.ts
> +            checkElementHoverState(paragraphs, paragraphExtendsTag + '0-hover-state-', text, 0);
is index 0 needed for theses? should be 0 by default

2021-04-09 06:52 UTC, Seamoo13 approved these changes

2021-04-12 14:21 UTC, AntonOlkhovskyi approved these changes

2021-04-13 18:35 UTC, InnaAtanasova approved these changes

2021-04-13 18:36 UTC, InnaAtanasova approved these changes

2021-04-15 13:53 UTC, merged