fix: (Platform) i18n remove select, plurals
SAP/fundamental-ngx pull request #5109
Opened 2021-04-12 18:39 UTC by platon-rov

BREAKING CHANGE: due to needs of SAP's projects was removed support of select and plurals of i18n
It followed with changes in i18n markers in the next components:

* ApprovalFlow Platform Component
* Form Platform Component
* Table Platform Component
* UploadCollection Platform Component
* ValueHelpDialog Platform Component

If you're using internationalization with any of these components -
you need to re-extract translations (`ng extract-i18n`) and update corresponding strings.

#### Please provide a link to the associated issue.

Closes #5098.

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [X] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [X] tests for the changes that have been done
- [X] all items on the [PR Review Checklist](https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist) are addressed.
- [X] Run npm run build-pack-library and test in external application

Documentation checklist:
- [X] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [X] Documentation Examples
- [X] Stackblitz works for all examples

2021-04-13 08:09 UTC, platon-rov commented on libs/platform/src/lib/components/value-help-dialog/models/vhd-strategy.enum.ts
> -export enum VhdDefineStrategy {
@mykolavorobiov i see that you edited that file a week ago, I found an unneeded interface, removed it, but maybe it had the implicit sence, please take a look.

2021-04-13 09:50 UTC, dimamarksman requested changes
LGTM
Just one comment

2021-04-13 09:50 UTC, dimamarksman commented on libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.html
> +        {{ payload.to ? payload.to.name : 'All files' }}.
`All files` is out of i18n marker

2021-04-13 09:50 UTC, dimamarksman commented on libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.html
>          {{ payload.to ? payload.to.name : 'All files' }}.
`All files` is not marked for translation

2021-04-13 09:50 UTC, dimamarksman commented on libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.html
>          {{ payload.to ? payload.to.name : 'All files' }}.
out of i18n

2021-04-13 09:50 UTC, dimamarksman commented on libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.html
>          {{ payload.to ? payload.to.name : 'All files' }}.
out of i18n

2021-04-13 18:04 UTC, dimamarksman approved these changes

2021-04-14 13:25 UTC, InnaAtanasova approved these changes

2021-04-14 13:32 UTC, olshansky approved these changes

2021-04-16 12:50 UTC, merged