test(e2e): skip state checks
SAP/fundamental-ngx pull request #5124
Opened 2021-04-14 12:28 UTC by AntonOlkhovskyi

#### Please provide a link to the associated issue.

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-04-16 06:45 UTC, Seamoo13 requested changes
main thing is to revert config file back to run all tests.

2021-04-16 06:45 UTC, Seamoo13 commented on e2e/wdio/core/tests/object-number.e2e-spec.ts
>              expect(objectNumberPage.compareWithBaseline()).toBeLessThan(3);
maybe increase to 5?

2021-04-16 06:45 UTC, Seamoo13 commented on e2e/wdio/platform/tests/action-list-item.e2e-spec.ts
>              expect(actionListPage.compareWithBaseline()).toBeLessThan(3);
maybe increase to 5?

2021-04-16 06:45 UTC, Seamoo13 commented on e2e/wdio/platform/tests/object-list-item.e2e-spec.ts
>              expect(objListPage.compareWithBaseline()).toBeLessThan(3);
same, increase to 5

2021-04-16 06:45 UTC, Seamoo13 commented on wdio-local.conf.js
> +        './e2e/wdio/core/**/select.e2e-spec.ts'
need to change back to default value to run all tests.

2021-04-22 07:42 UTC, nikvalor approved these changes

2021-04-22 10:01 UTC, Seamoo13 approved these changes
Approved, but you need to mark the checkboxes in the PR description.

2021-04-22 13:20 UTC, closed without merging