test: (e2e) added text core e2e tests
SAP/fundamental-ngx pull request #5134
Opened 2021-04-15 11:05 UTC by nikvalor

#### Please provide a link to the associated issue.

#### Please provide a brief summary of this pull request.
Added text core e2e tests

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-04-22 15:20 UTC, AntonOlkhovskyi commented on e2e/wdio/core/tests/text.e2e-spec.ts
> +            expect(getText(linksExpandable)).toContain('MORE');
Maybe use variables for that.

2021-04-22 15:22 UTC, AntonOlkhovskyi approved these changes

2021-04-23 06:57 UTC, Seamoo13 requested changes

2021-04-23 06:57 UTC, Seamoo13 commented on e2e/wdio/core/tests/text.e2e-spec.ts
> +                    textPage.getScreenshotFolder(), 10)).toBeLessThan(5, `element item hover state mismatch`);
error message say's 'hover state' - please update for each of these paragraph checks

2021-04-28 09:13 UTC, Seamoo13 approved these changes

2021-04-28 18:33 UTC, InnaAtanasova approved these changes

2021-04-29 08:38 UTC, merged