test: (e2e) added notification core e2e tests
SAP/fundamental-ngx pull request #5135
Opened 2021-04-15 12:31 UTC by nikvalor

#### Please provide a link to the associated issue.

#### Please provide a brief summary of this pull request.
Added notification core e2e tests

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-04-16 00:27 UTC, droshev requested changes
We are about to refactor the components so let's hold on those tests

2021-04-23 07:04 UTC, Seamoo13 requested changes

2021-04-23 07:04 UTC, Seamoo13 commented on e2e/wdio/core/tests/notification.e2e-spec.ts
> +                expect(isElementClickable(buttonMoreInfo, i)).toBe(true, `button more with index ${i} not clickable`);
'button more with index..' is hard to understand. better: 'more info button with index... '

2021-04-23 07:04 UTC, Seamoo13 commented on e2e/wdio/core/tests/notification.e2e-spec.ts
> +            expect(isElementClickable(buttonMoreInfo)).toBe(true, `button more with index not clickable`);
same comment as above

2021-04-23 07:04 UTC, Seamoo13 commented on e2e/wdio/core/tests/notification.e2e-spec.ts
> +            expect(isElementClickable(buttonMoreInfo)).toBe(true, `button more with index not clickable`);
same as above

2021-04-23 07:04 UTC, Seamoo13 commented on e2e/wdio/core/tests/notification.e2e-spec.ts
> +            expect(isElementClickable(buttonMoreInfo)).toBe(true, `button more with index not clickable`);
same as above

2021-04-23 07:04 UTC, Seamoo13 commented on e2e/wdio/core/tests/notification.e2e-spec.ts
> +            expect(isElementClickable(buttonMoreInfo)).toBe(true, `button more with index not clickable`);
same as above

2021-04-26 07:16 UTC, AntonOlkhovskyi approved these changes

2021-05-20 07:24 UTC, Seamoo13 approved these changes

2021-05-20 18:14 UTC, InnaAtanasova commented
@nikvalor are these e2e tests for the updated Notifications?

2021-05-25 18:50 UTC, closed without merging