test: add illustrated-message core e2e tests
SAP/fundamental-ngx pull request #5171
Opened 2021-04-20 12:37 UTC by Seamoo13

#### Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/4850
#### Please provide a brief summary of this pull request.
add e2e tests for illustrated message (core)
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-04-22 09:35 UTC, nikvalor approved these changes

2021-04-23 17:50 UTC, InnaAtanasova approved these changes
you need `closes` or `fixes` keywords in your PR template to close the issue

2021-04-26 07:49 UTC, AntonOlkhovskyi requested changes

2021-04-26 07:49 UTC, AntonOlkhovskyi commented on e2e/wdio/core/tests/illustrated-message.e2e-spec.ts
> +            expect(checkElementScreenshot(dialogPopup, 'dialogPopup', illustratedMessagePage.getScreenshotFolder()))
Add save screenshot method

2021-04-28 12:20 UTC, Seamoo13 commented on e2e/wdio/core/tests/illustrated-message.e2e-spec.ts
> +            expect(checkElementScreenshot(dialogPopup, 'dialogPopup', illustratedMessagePage.getScreenshotFolder()))
done

2021-05-05 06:27 UTC, AntonOlkhovskyi approved these changes

2021-05-05 08:27 UTC, merged