test: (e2e) added multi input core e2e tests
SAP/fundamental-ngx pull request #5181
Opened 2021-04-21 13:56 UTC by nikvalor

#### Please provide a link to the associated issue.

#### Please provide a brief summary of this pull request.

added multi input core e2e tests

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-04-22 13:48 UTC, Seamoo13 requested changes

2021-04-22 13:48 UTC, Seamoo13 commented on e2e/wdio/core/fixtures/appData/multi-input-contents.ts
> +export const Arr = [
Could you please give this array a more meaningful name?

2021-04-22 13:48 UTC, Seamoo13 commented on e2e/wdio/core/pages/multi-input.po.ts
> +    hiddenAddonButtonInputOptions =  'fd-multi-input[inputid="noAddonMultiInput1"] .fd-token__text span';
seems like there's an extra space between the equals sign and selector

2021-04-22 13:48 UTC, Seamoo13 commented on e2e/wdio/core/tests/multi-input.e2e-spec.ts
> +    it('Verify inputs should have placeholder', () => {
Why are some test cases in describe blocks and others not? Maybe better to organize them all in the same pattern of describe -> it -> it -> it describe -> it -> it

2021-04-22 13:48 UTC, Seamoo13 commented on e2e/wdio/core/tests/multi-input.e2e-spec.ts
> +            if (i === 8) {
better not to use else if / else. 
if (i === 8) {
do this...
continue;
}
if (i === 9) {
do this...
continue;
}
do this

2021-04-22 15:23 UTC, AntonOlkhovskyi requested changes

2021-04-22 15:23 UTC, AntonOlkhovskyi commented on e2e/wdio/core/tests/multi-input.e2e-spec.ts
> +    it('verify Display Object Property', () => {
Could you please add a bit more specific descriptions for it's

2021-04-28 09:12 UTC, Seamoo13 approved these changes

2021-04-28 18:32 UTC, InnaAtanasova approved these changes

2021-05-05 06:26 UTC, AntonOlkhovskyi approved these changes

2021-05-05 09:33 UTC, merged