fixed display key value when value pre populated
SAP/fundamental-ngx pull request #5204
Opened 2021-04-26 15:21 UTC by Lokanathan-k

#### Please provide a link to the associated issue.
Closes :https://github.com/SAP/fundamental-ngx/issues/5147

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-04-26 16:39 UTC, Betrozov requested changes

2021-04-26 16:39 UTC, Betrozov commented on libs/platform/src/lib/components/form/multi-input/multi-input.component.ts
> +        this.inputText = this.displayValue(this._selected);
```suggestion
        setAsSelected(items: MultiInputOption[]): void {
            this._selected = items;
            this.inputText = '';
        }
```

2021-04-26 16:39 UTC, Betrozov commented on libs/platform/src/lib/components/form/multi-input/multi-input.component.ts
> +    _selected: any[] = [];
```suggestion
    _selected: MultiInputOption[] = [];
```

2021-04-26 16:39 UTC, Betrozov commented on libs/platform/src/lib/components/form/multi-input/multi-input.component.ts
> +        this._updateModel(this._selected);
same

2021-04-26 16:39 UTC, Betrozov commented on libs/platform/src/lib/components/form/multi-input/multi-input.component.ts
> +        if (this._selected && this.selectedValue.label === this.inputText) {
same

2021-04-28 12:45 UTC, droshev commented
@Lokanathan-k Can you check the title of your PR?
```
The commit contains the following structural elements, to communicate intent to the consumers of your library:

fix: a commit of the type fix patches a bug in your codebase (this correlates with PATCH in Semantic Versioning).
feat: a commit of the type feat introduces a new feature to the codebase (this correlates with MINOR in Semantic Versioning).
BREAKING CHANGE: a commit that has a footer BREAKING CHANGE:, or appends a ! after the type/scope, introduces a breaking API change (correlating with MAJOR in Semantic Versioning). A BREAKING CHANGE can be part of commits of any type.
types other than fix: and feat: are allowed, for example @commitlint/config-conventional (based on the the Angular convention) recommends build:, chore:, ci:, docs:, style:, refactor:, perf:, test:, and others.
footers other than BREAKING CHANGE: <description> may be provided and follow a convention similar to git trailer format.

```

2021-04-29 18:21 UTC, KevinOkamoto requested changes

2021-04-29 18:21 UTC, KevinOkamoto commented on libs/platform/src/lib/components/form/multi-input/multi-input.component.ts
> +    }
Do we need `selected` as an @Input when we already have `value` as an @Input from the parent class?
https://github.com/SAP/fundamental-ngx/blob/83d8d3d2ce78a2d0639c403346cbd3c914809824/libs/platform/src/lib/components/form/multi-input/base-multi-input.ts#L134-L147

2021-04-29 18:21 UTC, KevinOkamoto commented on libs/platform/src/lib/components/form/multi-input/multi-input.component.ts
> +    }
If we need to keep `selected` then can we just leverage `value` like this?
```ts
@Input()
get selected(): any[] {
    return this.value;
}
set selected(value: any[]) {
   this.value = value;
}
```

2021-05-04 05:05 UTC, KevinOkamoto approved these changes

2021-05-13 06:35 UTC, manu-kr approved these changes
LGTM

2021-05-13 08:41 UTC, merged