test: (e2e) added panel core e2e tests
SAP/fundamental-ngx pull request #5215
Opened 2021-04-28 14:12 UTC by nikvalor

#### Please provide a link to the associated issue.

#### Please provide a brief summary of this pull request.
added panel core e2e tests

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-04-29 06:50 UTC, Seamoo13 requested changes

2021-04-29 06:50 UTC, Seamoo13 commented on e2e/wdio/core/tests/panel.e2e-spec.ts
> +        expect(getAttributeByName(expandablePanel, 'ng-reflect-expanded')).toBe('false');
this 'ng-reflect-expanded' is one of those dev mod attributes which we shouldn't use. You can see from the netlify deploy that this attribute isn't there https://fundamental-ngx.netlify.app/#/core/panel 
please rework to not use dev mod attribute. (I think you'll need to change the selector to use the drop-down arrow button and get 'aria-expanded' attribute.

2021-05-05 06:24 UTC, AntonOlkhovskyi approved these changes

2021-05-05 11:59 UTC, Seamoo13 approved these changes

2021-05-12 17:07 UTC, InnaAtanasova approved these changes

2021-05-17 14:22 UTC, merged