chore: (platform)css cleanup hardcoded styles from feed input component
SAP/fundamental-ngx pull request #5221
Opened 2021-04-29 05:29 UTC by Lokanathan-k

css cleanup hardcoded styles from feed input component

#### Please provide a link to the associated issue.
part of: https://github.com/SAP/fundamental-ngx/issues/5025

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [NA] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-04-29 12:43 UTC, droshev requested changes
@Lokanathan-k if this is just replacing hardcoded styling then the UI should not change, no?

2021-04-29 16:32 UTC, Lokanathan-k commented
> @Lokanathan-k if this is just replacing hardcoded styling then the UI should not change, no?

hi @droshev there was no change in the UI look and feel, there was a test case fail so i have updated the but that was not necessary so reverted it.

2021-04-30 10:39 UTC, DeepakSap14 approved these changes

2021-05-03 20:25 UTC, InnaAtanasova approved these changes

2021-05-04 04:01 UTC, merged