fix: (core) adding links to the responsive breadcrumb section
SAP/fundamental-ngx pull request #5258
Opened 2021-04-30 12:34 UTC by Lokanathan-k

#### Please provide a link to the associated issue.
Closes: https://github.com/SAP/fundamental-ngx/issues/3114

#### Please provide a brief summary of this pull request.

adding links to the responsive breadcrumb section

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-05-03 00:25 UTC, droshev requested changes
I don't think this should be `fix:`

2021-05-03 20:19 UTC, InnaAtanasova commented on apps/docs/src/app/core/component-docs/breadcrumb/examples/breadcrumb-responsive-example.component.html
> +            <a fd-breadcrumb-link [attr.href]="'#'">Breadcrumb Level 1</a>
Shouldn't it be `attr.href="#"`?

2021-05-17 10:14 UTC, Betrozov commented on apps/docs/src/app/core/component-docs/breadcrumb/examples/breadcrumb-responsive-example.component.html
> +            <a fd-breadcrumb-link [attr.href]="'#'">Breadcrumb Level 1</a>
or just `href="#"`

2021-05-18 04:29 UTC, Lokanathan-k commented on apps/docs/src/app/core/component-docs/breadcrumb/examples/breadcrumb-responsive-example.component.html
> +            <a fd-breadcrumb-link [attr.href]="'#'">Breadcrumb Level 1</a>
fixed

2021-05-18 06:41 UTC, olshansky approved these changes

2021-05-18 08:55 UTC, Betrozov approved these changes

2021-05-18 15:36 UTC, InnaAtanasova approved these changes

2021-05-19 16:57 UTC, merged

2021-05-20 05:29 UTC, puru-hk commented
Tested it is working as expected.

2021-05-20 05:30 UTC, puru-hk reviewed
Looks good