fix: (Platform) adjust hint alignment as per UX designer specifications
SAP/fundamental-ngx pull request #5310
Opened 2021-05-06 15:54 UTC by sKudum

#### Please provide a link to the associated issue.
Closes #5155 

#### Please provide a brief summary of this pull request.
As hint alignment does not have Fiori specification. UX designers has suggested it has to be aligned as below.

Before:

<img width="583" alt="2021-05-06_21-23-55" src="https://user-images.githubusercontent.com/53487468/117328551-5e54eb00-aeb1-11eb-9d43-a22e1bab14cd.png">

After:

<img width="1149" alt="2021-05-05_20-16-35" src="https://user-images.githubusercontent.com/53487468/117328446-45e4d080-aeb1-11eb-9620-38e57863cccf.png">

#### Please check whether the PR fulfills the following requirements
- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [n/a ] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-05-06 16:03 UTC, KevinOkamoto commented on package.json
> +    "npm": "7.11.2",
Do we need `npm` as a dependency?

2021-05-06 16:15 UTC, sKudum commented on package.json
> +    "npm": "7.11.2",
Removed it

2021-05-06 22:07 UTC, droshev requested changes
Can you remove package-lock.json from the PR

2021-05-10 15:43 UTC, InnaAtanasova commented
I noticed a couple of styling problems:
1. In Core Textarea component the question mark icon is cut
<img width="589" alt="Screen Shot 2021-05-10 at 11 38 34 AM" src="https://user-images.githubusercontent.com/39598672/117686217-a6f7f700-b184-11eb-8e48-f1a4dc8caaf1.png">
2. Icon and text are not vertically aligned
<img width="809" alt="Screen Shot 2021-05-10 at 11 39 19 AM" src="https://user-images.githubusercontent.com/39598672/117686312-bd9e4e00-b184-11eb-9282-404909accd98.png">
3. When the text is very long, the icon is neever aligned with the right end of the textarea. There's some padding+margin spacing that prevents the icon reaching the end of the container.
<img width="2007" alt="Screen Shot 2021-05-10 at 11 40 37 AM" src="https://user-images.githubusercontent.com/39598672/117686364-cabb3d00-b184-11eb-880f-72a451bdcf94.png">

2021-05-12 12:07 UTC, sKudum commented
> I noticed a couple of styling problems:
> 
> 1. In Core Textarea component the question mark icon is cut
> 
> <img alt="Screen Shot 2021-05-10 at 11 38 34 AM" width="589" src="https://user-images.githubusercontent.com/39598672/117686217-a6f7f700-b184-11eb-8e48-f1a4dc8caaf1.png">
> 

==>Updated

> 2. Icon and text are not vertically aligned
> <img alt="Screen Shot 2021-05-10 at 11 39 19 AM" width="809" src="https://user-images.githubusercontent.com/39598672/117686312-bd9e4e00-b184-11eb-9282-404909accd98.png">
> Updated


> 3. When the text is very long, the icon is neever aligned with the right end of the textarea. There's some padding+margin spacing that prevents the icon reaching the end of the container.
> <img alt="Screen Shot 2021-05-10 at 11 40 37 AM" width="2000" src="https://user-images.githubusercontent.com/39598672/117686364-cabb3d00-b184-11eb-880f-72a451bdcf94.png">

This has been added explicitly as part of https://github.com/SAP/fundamental-ngx/pull/4061/..I have made them 0rem for now. Let me know do I need have it updated or not.

2021-05-12 13:44 UTC, mikerodonnell89 commented
Looks good, I'm wondering if because the text has some margin-right, I'm wondering if the icon should have some margin-right when the icon comes before the text.  Also wondering if the icon should be the same color as the label color

<img width="342" alt="Screen Shot 2021-05-12 at 7 42 30 AM" src="https://user-images.githubusercontent.com/2471874/117985060-9f0b9480-b2f5-11eb-88ab-051b39099433.png">

2021-05-12 14:50 UTC, sKudum commented
> Looks good, I'm wondering if because the text has some margin-right, I'm wondering if the icon should have some margin-right when the icon comes before the text. Also wondering if the icon should be the same color as the label color
> 
> <img alt="Screen Shot 2021-05-12 at 7 42 30 AM" width="342" src="https://user-images.githubusercontent.com/2471874/117985060-9f0b9480-b2f5-11eb-88ab-051b39099433.png">

Hi Mike, we don't have fiori specifications for it, so not sure what value i need to add exactly.

2021-05-12 15:15 UTC, InnaAtanasova approved these changes

2021-05-14 12:03 UTC, dimamarksman commented
@sKudum preview is broken

2021-05-17 07:38 UTC, dimamarksman commented
@sKudum e2e tests are failing, please take a look

2021-05-17 10:05 UTC, Betrozov approved these changes

2021-05-17 14:57 UTC, sKudum commented
Hi @droshev , @InnaAtanasova , @Betrozov , QA team has pushed e2e changes please do have a these are helping to resolve test case build issues. Please do provide your comments on it.

2021-05-18 13:35 UTC, droshev approved these changes

2021-05-18 13:46 UTC, merged