test(e2e): avatar group e2e
SAP/fundamental-ngx pull request #5327
Opened 2021-05-07 11:50 UTC by AntonOlkhovskyi

#### Please provide a link to the associated issue.
Closes SAP/fundamental-ngx#

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-05-07 11:56 UTC, Seamoo13 requested changes

2021-05-07 11:56 UTC, Seamoo13 commented on e2e/wdio/core/tests/avatar-group.e2e-spec.ts
> +
I think 1-2 more cases are needed
when you click on group type it opens a popup with individual users (you check this now), each user is clickable and opens an individual user card. Should check this. also back btn functionality on this user card

2021-05-07 11:56 UTC, Seamoo13 commented on e2e/wdio/core/pages/avatar-group.po.ts
> +    // usedDetailsPopup = '.fd-quick-view__content';
not needed?

2021-05-18 12:10 UTC, nikvalor commented on e2e/wdio/core/tests/avatar-group.e2e-spec.ts
> +        expect(doesItExist(avatarGroupPage.usedDetailsPopup)).toBe(true);
please message if the element is not exist

2021-05-18 12:10 UTC, nikvalor commented on e2e/wdio/core/tests/avatar-group.e2e-spec.ts
> +        expect(doesItExist(avatarGroupPage.usedGroupDetailsPopup)).toBe(true);
same as above

2021-05-21 22:05 UTC, InnaAtanasova approved these changes

2021-05-24 07:59 UTC, closed without merging

2021-05-24 08:22 UTC, Seamoo13 commented
reopened here https://github.com/SAP/fundamental-ngx/pull/5450