fix: (Core) multi-input defect hunting 62 bugs
SAP/fundamental-ngx pull request #5434
Opened 2021-05-20 20:58 UTC by mikerodonnell89

fixes two multi-input bugs as part of #5420:

- selecting a new item by clicking it anywhere other than the checkbox should close the popover (popover should stay open if checkbox is clicked)
- Tokenizer (and multiinput) - cmd/ctrl+A to select all tokens then you must press delete twice to delete - should only happen once

2021-05-27 12:25 UTC, Betrozov approved these changes

2021-05-27 12:25 UTC, Betrozov commented
@mikerodonnell89 please remove package-lock.json from this PR

2021-06-04 12:59 UTC, platon-rov commented on libs/core/src/lib/multi-input/multi-input.component.ts
> +    handleSelect(checked: any, value: any, event?: MouseEvent, fromCheckbox?: boolean): void {
`checked` should have boolean type.

2021-06-04 13:03 UTC, platon-rov commented
I'm not sure that it should be done in the scope of current PR but I see the component has a lot of `any[]` usage, which can be refactored to use `T[]` to have better type checking.

2021-06-08 09:57 UTC, Betrozov reviewed
also, please squash all your commits in this PR
and then rename your commit using the new format

2021-06-08 09:57 UTC, Betrozov commented on libs/core/src/lib/multi-input/multi-input.component.ts
> +            if (!fromCheckbox) {
please remove empty `if`

2021-06-08 09:59 UTC, Betrozov requested changes
also, please squash all your commits in this PR
and then rename your commit using the new format

2021-06-15 18:50 UTC, closed without merging