test: (e2e) add radio button e2e tests
SAP/fundamental-ngx pull request #5495
Opened 2021-05-26 12:23 UTC by nikvalor

#### Please provide a link to the associated issue.
Closes SAP/fundamental-ngx#5494

#### Please provide a brief summary of this pull request.
add radio button e2e tests

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-05-26 12:45 UTC, Seamoo13 requested changes

2021-05-26 12:45 UTC, Seamoo13 commented on e2e/wdio/core/tests/radio-button.e2e-spec.ts
> +            } else {
let's avoid using else, as discussed a couple months ago.

2021-06-01 12:01 UTC, Seamoo13 commented
Why is the status indicator e2e test in here too?

2021-06-04 11:16 UTC, nikvalor commented
Not actual.
https://github.com/SAP/fundamental-ngx/pull/5588

2021-06-04 11:16 UTC, closed without merging