fix(core): access popover on image using keyboard
SAP/fundamental-ngx pull request #5540
Opened 2021-06-01 16:46 UTC by sKudum

#### Please provide a link to the associated issue.
Closes SAP/fundamental-ngx #3139 

#### Please provide a brief summary of this pull request.

The ‘image’ buttons highlighted in popover will be reachable by keyboard as well.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [n/a] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-06-02 14:08 UTC, Betrozov requested changes

2021-06-02 14:08 UTC, Betrozov commented on libs/core/src/lib/popover/popover.component.ts
> +         (KeyUtil.isKeyCode(event, ENTER) || KeyUtil.isKeyCode(event, SPACE))) {
```suggestion
         KeyUtil.isKeyCode(event, [ENTER, SPACE])) {
```

2021-06-02 14:08 UTC, Betrozov commented on apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.scss
> +      outline-style: var(--sapContent_FocusStyle);
```suggestion
    outline-width: .0625rem;
    outline-width: var(--sapContent_FocusWidth, .0625rem);
    outline-color: #000;
    outline-color: var(--sapContent_FocusColor, #000);
    outline-style: dotted;
    outline-style: var(--sapContent_FocusStyle, dotted);
```

2021-06-02 14:08 UTC, Betrozov commented on apps/docs/src/app/core/component-docs/popover/examples/popover-programmatic/popover-programmatic-open-example.component.scss
> +      outline-style: var(--sapContent_FocusStyle);
```suggestion
    outline-width: .0625rem;
    outline-width: var(--sapContent_FocusWidth, .0625rem);
    outline-color: #000;
    outline-color: var(--sapContent_FocusColor, #000);
    outline-style: dotted;
    outline-style: var(--sapContent_FocusStyle, dotted);
```

2021-06-02 14:09 UTC, KevinOkamoto approved these changes

2021-06-03 15:15 UTC, Betrozov approved these changes

2021-06-04 07:45 UTC, Seamoo13 approved these changes

2021-06-04 13:33 UTC, InnaAtanasova requested changes
- `outline-offset` is not supported on IE11, we have another mixin for applying a fake focus (used in buttons and list)
- We agreed to not have css in Fundamental-ngx, I am not allowed to approve PRs with css code in this library.

2021-06-07 00:56 UTC, droshev commented
Closing old PRs - feel free to reopen it if/when needed

2021-06-07 13:52 UTC, sKudum commented
Reopening it to address reviewers comments.

2021-06-09 07:42 UTC, sKudum commented
> * `outline-offset` is not supported on IE11, we have another mixin for applying a fake focus (used in buttons and list).
          
   
Hi @InnaAtanasova , 
    1).As mentioned outline-offset is removed from styles.

   2).Tried using fake focus referring to list and button but look as feel is not as expected attached screen shots of out put by using fake focus.

<img width="306" alt="2021-06-09_12-34-41" src="https://user-images.githubusercontent.com/53487468/121313252-d59ff380-c923-11eb-95cd-223881e2888b.png">


Code sample:
<img width="373" alt="2021-06-09_12-35-07" src="https://user-images.githubusercontent.com/53487468/121313278-dd5f9800-c923-11eb-9e26-ae3fcea078c7.png">





> * We agreed to not have css in Fundamental-ngx, I am not allowed to approve PRs with css code in this library.

    These styles are added in documentation examples as a11y team is looking for these feature even though the respective components such as avatar and icon doesn't provide the focus (as per Fiori3 documents).

2021-06-09 17:22 UTC, InnaAtanasova commented
> > * `outline-offset` is not supported on IE11, we have another mixin for applying a fake focus (used in buttons and list).
> 
> Hi @InnaAtanasova ,
> 
> ```
> 1).As mentioned outline-offset is removed from styles.
> 
> 2).Tried using fake focus referring to list and button but look as feel is not as expected attached screen shots of out put by using fake focus.
> ```
> 
> <img alt="2021-06-09_12-34-41" width="306" src="https://user-images.githubusercontent.com/53487468/121313252-d59ff380-c923-11eb-95cd-223881e2888b.png">
> 
> Code sample:
> <img alt="2021-06-09_12-35-07" width="373" src="https://user-images.githubusercontent.com/53487468/121313278-dd5f9800-c923-11eb-9e26-ae3fcea078c7.png">
> 
> > * We agreed to not have css in Fundamental-ngx, I am not allowed to approve PRs with css code in this library.
> 
> ` These styles are added in documentation examples as a11y team is looking for these feature even though the respective components such as avatar and icon doesn't provide the focus (as per Fiori3 documents).`
> 
> Please do let me know your suggestions on this will update accordingly.Thank You.

In my opinion it makes no sense to make the components in the documentation accessible if they are not accessible by default. When the user uses these components in their applications they won't get the styling from our documentation example, which means that they won't be compliant to the a11y rules. Avatar and icons by default do not have focus because focus indicates some sort of an action associated with them.  The moment they are used as "controls" , in this case to open the popover body they should get a focus. Here are some examples from UI5:
<img width="234" alt="Screen Shot 2021-06-09 at 1 12 36 PM" src="https://user-images.githubusercontent.com/39598672/121400137-3845bf00-c925-11eb-9525-f54a61d639ec.png">
<img width="160" alt="Screen Shot 2021-06-09 at 1 13 28 PM" src="https://user-images.githubusercontent.com/39598672/121400149-3aa81900-c925-11eb-9501-aefd890e8279.png">
<img width="235" alt="Screen Shot 2021-06-09 at 1 12 40 PM" src="https://user-images.githubusercontent.com/39598672/121400150-3b40af80-c925-11eb-99ec-2623b57f2a92.png">

Check the last icon from here: https://sapui5.hana.ondemand.com/#/entity/sap.ui.core.Icon/sample/sap.ui.core.sample.Icon
and the first row of Avatars here: https://sapui5.hana.ondemand.com/#/entity/sap.f.Avatar/sample/sap.f.sample.Avatar

As for the focus line and the problem with focus line covering the avatar, this specific fake focus mixin was created for list and/or button, you can always create a new one for Avatar and play with the left, top, bottom, right position values.

2021-06-09 17:34 UTC, InnaAtanasova commented
In my opinion when Avatar is placed inside a popover control it should not have the `role="img"` but `role="button"`, because as per MDN:
 _"The button role should be used for clickable elements that trigger a response when activated by the user. Adding role="button" will make an element appear as a button control to a screen reader. This role can be used in combination with the aria-pressed attribute to create toggle buttons."_ 

More info here: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role

Same for icons, images, basically all the items that can become a trigger for action. You can use css specificity and add the focus outline and the pointer cursor when the class comes together with a role: 
```
.fd-avatar[role="button"] {...}
```

Hope this helps. Let me know if more info is required.

2021-06-10 13:55 UTC, sKudum commented
Hi @InnaAtanasova , will go with approach 2. 

Please suggest what should I do for now.
1). Until styles are published can I have styles in lib later will update styles.
2).Close this PR and reopen it once styles are published and do the required changes.

2021-06-10 14:13 UTC, InnaAtanasova commented
> Hi @InnaAtanasova , will go with approach 2.
> 
> Please suggest what should I do for now.
> 1). Until styles are published can I have styles in lib later will update styles.
> 2).Close this PR and reopen it once styles are published and do the required changes.

Hey Sushma,
you need to close this PR and open a PR in fund-styles. Once it's merged you can use the RC and continue in ngx.

2021-06-10 14:15 UTC, sKudum commented
Closing it as discussed mentioned above.

2021-06-10 14:15 UTC, closed without merging