fix: (Platform) add date picker hover tooltip
SAP/fundamental-ngx pull request #5572
Opened 2021-06-03 15:46 UTC by ASokolov22

#### Please provide a link to the associated issue.
Fixes https://github.com/SAP/fundamental-ngx/issues/5080

#### Please provide a brief summary of this pull request.
Fixes issue #4 about: add a mouse hover tooltip to date picker buttons

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-06-04 12:19 UTC, Betrozov requested changes

2021-06-04 12:19 UTC, Betrozov commented on libs/core/src/lib/calendar/calendar-header/calendar-header.component.html
> +                [title]="previousAriaLabel"
```suggestion
                [attr.title]="previousAriaLabel"
```

2021-06-04 12:19 UTC, Betrozov commented on libs/core/src/lib/calendar/calendar-header/calendar-header.component.html
> +                [title]="nextAriaLabel"
```suggestion
                [attr.title]="nextAriaLabel"
```

2021-06-04 12:19 UTC, Betrozov commented on libs/core/src/lib/date-picker/date-picker.component.html
> +                    [title]="displayCalendarToggleLabel"
```suggestion
                    [attr.title]="displayCalendarToggleLabel"
```

2021-06-07 11:56 UTC, Betrozov commented
@ASokolov22 your PR contains changes only to core not to platform
please change your PR title and commit message

2021-06-09 10:03 UTC, ASokolov22 commented on libs/core/src/lib/date-picker/date-picker.component.html
> +                    [title]="displayCalendarToggleLabel"
Done

2021-06-09 14:42 UTC, Betrozov approved these changes

2021-06-18 14:10 UTC, merged