fix(core,platform): updating file uploader examples to display valid error message, on selecting invalid file.
SAP/fundamental-ngx pull request #5629
Opened 2021-06-08 07:58 UTC by manu-kr

#### Please provide a link to the associated issue.
Closes #4468

#### Please provide a brief summary of this pull request.
 This PR contains changes to update the example for file uploader component, to display valid error message and correct aria-label value for button in platform file uploader component.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [NA] update `README.md`
- [NA] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-06-08 08:08 UTC, olshansky approved these changes

2021-06-09 05:56 UTC, kavya-b commented
after selecting invalid `jpeg` file, the placeholder should reset; instead it becomes blank:
<img width="400" src="https://user-images.githubusercontent.com/53509521/121301186-71763300-c915-11eb-8057-dfb13a6a65e2.png">

2021-06-09 08:14 UTC, manu-kr commented
> after selecting invalid `jpeg` file, the placeholder should reset; instead it becomes blank:
> <img alt="" width="400" src="https://user-images.githubusercontent.com/53509521/121301186-71763300-c915-11eb-8057-dfb13a6a65e2.png">

> Fixed now.

2021-06-09 09:31 UTC, kavya-b approved these changes

2021-06-09 17:24 UTC, KevinOkamoto approved these changes

2021-06-09 19:33 UTC, InnaAtanasova requested changes
It's not a docs PR

2021-06-10 13:23 UTC, InnaAtanasova approved these changes

2021-06-10 15:26 UTC, merged