fix(core): change styling tabs component
SAP/fundamental-ngx pull request #5674
Opened 2021-06-14 08:32 UTC by olshansky

#### Please provide a link to the associated issue.
Closes SAP/fundamental-ngx#5128 _(original PR https://github.com/OleksiyDrozdov/fundamental-ngx/pull/38)_

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-06-14 09:24 UTC, kavya-b commented
By default, the first tab is not appearing selected for all the examples that use `routerLink`. When we click on the tab, only then it gets selected. Maybe something needs to be changed with the actual routes path? I'm not sure.
<img width="435" alt="Screenshot 2021-06-14 at 2 47 11 PM" src="https://user-images.githubusercontent.com/53509521/121869273-812fb600-cd1f-11eb-8067-8641818dc44e.png">

2021-06-14 12:06 UTC, OleksiyDrozdov commented
![Screenshot 2021-06-14 145527](https://user-images.githubusercontent.com/53093915/121888477-555d0200-cd18-11eb-91a4-d976d6997d19.png)
Issue was when you created a new project and imported fundamental-ngx you couldn't see selected link (there was no underlying) after user clicks the link but now it is fixed.

2021-06-15 09:01 UTC, kavya-b approved these changes

2021-06-15 09:20 UTC, Betrozov approved these changes

2021-06-15 20:23 UTC, mikerodonnell89 approved these changes

2021-06-16 21:13 UTC, InnaAtanasova requested changes

2021-06-16 21:13 UTC, InnaAtanasova commented on libs/core/src/lib/tabs/tab-nav/tab-nav.component.scss
> +}
This needs to go in Fund-styles. We are no longer allowed to approve PRs with css that belongs in fund-styles.

2021-06-18 16:07 UTC, OleksiyDrozdov commented
https://github.com/OleksiyDrozdov/fundamental-styles/pull/1

2021-06-23 14:42 UTC, closed without merging