docs: (Core) add ariaLabelledby to the dialog header for screen reader
SAP/fundamental-ngx pull request #5682
Opened 2021-06-15 07:29 UTC by Lokanathan-k

#### Please provide a link to the associated issue.
Closes : https://github.com/SAP/fundamental-ngx/issues/3117

#### Please provide a brief summary of this pull request.

docs: (Core) add ariaLabelledby to the dialog header for screen reader

#### Please check whether the PR fulfills the following requirements

- [X] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [X] tests for the changes that have been done
- [X] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [X] Run npm run build-pack-library and test in external application

Documentation checklist:
- [x] update `README.md`
- [NA] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [X] Documentation Examples
- [X] Stackblitz works for all examples

2021-06-15 09:16 UTC, Betrozov requested changes
please update your branch with the latest main
and please make valid commit message

2021-06-16 15:28 UTC, olshansky commented on libs/core/src/lib/dialog/dialog.component.ts
> +        //this.dialogWindow.nativeElement.focus();
Please, remove it if it's unnecessary

2021-06-22 13:35 UTC, platon-rov approved these changes

2021-06-23 06:01 UTC, olshansky approved these changes

2021-06-23 08:07 UTC, Betrozov approved these changes

2021-06-25 07:30 UTC, puru-hk commented
Looks fine

2021-06-25 07:30 UTC, puru-hk approved these changes

2021-06-25 16:59 UTC, mikerodonnell89 approved these changes
LGTM

2021-06-29 13:20 UTC, merged