fix(platform): a11y issues fixed for slider
SAP/fundamental-ngx pull request #5683
Opened 2021-06-15 08:44 UTC by DeepakSap14

#### Please provide a link to the associated issue.
Closes SAP/fundamental-ngx#5582

#### Please provide a brief summary of this pull request.
This PR fixes following issues:
1. Announcement of minimum and maximum value of slider -- Not reproducible using chromevox, but not detected by JAWS.
   -- All required aria-tags are correctly assigned.
2.  slider values is read twice -- not reproducible in chromevox.
3.  incorrect 'has popup' announced - fixed 
4. custom lable in slider is not read -- not reproducible in chromevox.
5. single mode/rangemode is not announced - fixed.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [NA] update `README.md`
- [NA] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-06-15 09:31 UTC, Betrozov approved these changes

2021-06-15 10:22 UTC, kavya-b commented on apps/docs/src/app/platform/component-docs/platform-slider/examples/form-field/slider-form-field-example.component.html
> +        <fdp-slider name="value5" formControlName="value1" ariaLabel="Single mode"> </fdp-slider>
should `name` also be `value1`?

2021-06-15 10:24 UTC, kavya-b commented on apps/docs/src/app/platform/component-docs/platform-slider/examples/form-field/slider-form-field-example.component.html
> +        <fdp-slider name="value5" formControlName="value1" ariaLabel="Single mode"> </fdp-slider>
also PR title can be changed to `fix(platform): fix a11y issues for slider` in accordance with having only present tense in the message.

2021-06-15 19:35 UTC, mikerodonnell89 requested changes
Chrome screen reader is reading "min" as "minute" for me.  Also I think we should go with something more verbose to explain min/max to the user, what's currently being read would simply confuse me.  Maybe "Slider, current value is ____, min value is ____, max value is ____"

2021-06-17 16:38 UTC, DeepakSap14 commented
> Chrome screen reader is reading "min" as "minute" for me. Also I think we should go with something more verbose to explain min/max to the user, what's currently being read would simply confuse me. Maybe "Slider, current value is ____, min value is ____, max value is ____"

@mikerodonnell89 
verbose for reading min/max is fixed now.
for `Chrome screen reader is reading "min" as "minute"`,  I am not able to reduce reading speed, it may seem when it is trying to read "min is" very fast pace. also there is no way, it can be controlled. because it it coming from aria-valuemin.

2021-06-17 18:21 UTC, InnaAtanasova approved these changes

2021-06-17 18:22 UTC, InnaAtanasova submitted a review, later dismissed
.

2021-06-17 18:24 UTC, InnaAtanasova approved these changes

2021-06-25 09:59 UTC, puru-hk commented
Below are Comments from the ATL team 

Issue 1:

OB: The minimum and maximum value are not read.
EB: Ideally, the entire relevant information available should be read on navigating to the sliders. i.e. on navigating to the sliders the information regarding the maximum and minimum value available should be read.

issue 2:
OB: On accessing the slider, the values are read as '0' on changing the values.
![image](https://user-images.githubusercontent.com/78714518/123405942-ffb21080-d5c7-11eb-9c11-d85c2f238821.png)
EB: ideally, On changing the values the visible and changed values should be read on increasing and decreasing .

Issue 3:
OB: On accessing the slider, i can still able to reproduce the issue.
![image](https://user-images.githubusercontent.com/78714518/123405486-81ee0500-d5c7-11eb-98ba-73356989ec97.png)
EB: Ideally, on changing the values within a slider using up/down arrow keys, the information regarding the value should be read only once and no additional information should be read.

Issue 4:
EB: On Changing the values are not read  but read as 'Zero' value.
![image](https://user-images.githubusercontent.com/78714518/123406362-73ecb400-d5c8-11eb-8c28-cd32f6643e15.png)
EB: Ideally, on changing the value within the slider, the information regarding the focused value and the changed value should be read.

Issue 5:
OB: On changing the value read as '0' on increasing and decreasing the values.
![image](https://user-images.githubusercontent.com/78714518/123406779-e5c4fd80-d5c8-11eb-89ad-6dfc50f2db34.png)
EB: Ideally, the changed value must be read.

[Note: On increasing and Decreasing the value are read as '0'.
So please fix the issue

URL:https://deploy-preview-5683--fundamental-ngx.netlify.app
JAWS 2021

2021-07-01 10:30 UTC, kavya-b approved these changes

2021-07-06 08:53 UTC, platon-rov commented on libs/core/src/lib/slider/slider.component.html
> +            ariaLabel || 'slider minimum value is ' + minValue + ', maximum value is ' + maxValue
There should be i18n for the default label

2021-07-06 08:54 UTC, platon-rov approved these changes

2021-07-07 14:32 UTC, mikerodonnell89 approved these changes

2021-07-08 08:56 UTC, puru-hk commented
**Issue 5081:**

Issue 1: Fixed

Issue 2: 
![image](https://user-images.githubusercontent.com/78714518/124892921-ecf00080-dff7-11eb-902c-5dd1cde6c947.png)
OB: Throughout the control, on changing the values read thrice to the user.
EB: On changing the value using up/down arrow keys the changed value should be read once to the user.
Note: throughout the control

Issue 3: 
![image](https://user-images.githubusercontent.com/78714518/124892225-502d6300-dff7-11eb-9600-949c01856430.png)
OB: On accessing the slider as visually there is no pop up read as has pop up.
EB: ideally, such additional information such as 'Has pop up' should be removed.

Issue 4: Fixed

Issue 5: Fixed

Issue 6: Fixed

Issue 7: 
![image](https://user-images.githubusercontent.com/78714518/124892882-e2356b80-dff7-11eb-8856-4ab15f57aabd.png)
OB: on adapting the screen to320 CSS, the text gets truncated.
EB: Ideally, the texts shouldn't get truncated when screen is resized to 320 pixels. It should be clearly visible.

2021-07-08 08:59 UTC, puru-hk commented
**Issue 5582:**

Issue 1: Fixed

Issue 2: 
![image](https://user-images.githubusercontent.com/78714518/124883401-ea3cdd80-dfee-11eb-91c7-02c3b1bbe3f0.png)
The value being read thrice through out the application.

OB: On changing the values using up/down arrow key the values are read thrice to the user.
EB: Ideally, on changing the values within a slider using up/down arrow keys, the information regarding the value should be read only once.

Issue 3: 
![image](https://user-images.githubusercontent.com/78714518/124881940-85cd4e80-dfed-11eb-9f4b-742c63d8595a.png)

OB: On changing the values using up/down arrow key the values are read thrice to the user.
EB: Ideally, on changing the values within a slider using up/down arrow keys, the information regarding the value should be read only once.

Issue 4:

![image](https://user-images.githubusercontent.com/78714518/124883086-9cc07080-dfee-11eb-84ee-6650de62f4e0.png)
OB: On changing the values using up/down arrow key the values are read thrice to the user.
EB: Ideally, on changing the values within a slider using up/down arrow keys, the information regarding the value should be read only once. 
The Range value should be read to the user

Issue 5:
![image](https://user-images.githubusercontent.com/78714518/124882922-77cbfd80-dfee-11eb-85e7-0876439dd274.png)
OB: On changing the values using up/down arrow key the values are read thrice to the user.
EB: Ideally, on changing the values within a slider using up/down arrow keys, the information regarding the value should be read only once.

URL:https://deploy-preview-5683--fundamental-ngx.netlify.app
JAWS 2021

2021-07-12 10:18 UTC, puru-hk commented
Issue 5081:
Issue 7 I have tested in the real device. It is working properly. You can ignore

2021-07-13 05:09 UTC, DeepakSap14 commented
@puru-hk 
please re-verify this one more time. some improvements are done as we had discussed and issue were raised.
for issue #5081, issue 3('Has pop up' should be removed.), this is correct. As we have popup there at slider handle as tooltip. this information will be read. there is no way, we will be able to remove that.

2021-07-14 03:47 UTC, puru-hk commented
@DeepakSap14 Demo url is wrong. Could you please update the url..

2021-07-14 17:39 UTC, mikerodonnell89 commented
@DeepakSap14 e2e tests failing, looks like a legit error related to slider

2021-07-15 10:12 UTC, Betrozov approved these changes

2021-07-15 20:38 UTC, aberikashvili commented on libs/core/src/lib/slider/slider.component.ts
> +            this._rangeSliderHandle2CurrentValuePrefix = this.rangeSliderHandle2CurrentValuePrefix;
Please remove duplicated line

2021-07-15 20:54 UTC, aberikashvili commented on libs/core/src/lib/slider/slider.component.ts
> +            rangeHigherValue = rangeValue[1].label;
```suggestion
            const min = this.customValues[rangeValue[0]] || this.customValues[0];
            const max = this.customValues[rangeValue[1]] || this.customValues[this.customValues.length - 1];

            rangeLowerValue = min.label;
            rangeHigherValue = max.label;
```

2021-07-16 05:01 UTC, DeepakSap14 commented on libs/core/src/lib/slider/slider.component.ts
> +            this._rangeSliderHandle2CurrentValuePrefix = this.rangeSliderHandle2CurrentValuePrefix;
fixed

2021-07-19 08:24 UTC, puru-hk commented
On increasing and decreasing the changed values are read twice using up and down arrow key.
Its known JAWS issue. Rest all issues looks fine

2021-07-19 08:24 UTC, puru-hk approved these changes

2021-07-21 09:41 UTC, merged