fix(core): in reactive from disabling select component
SAP/fundamental-ngx pull request #5698
Opened 2021-06-17 11:57 UTC by sKudum

#### Please provide a link to the associated issue.
Closes SAP/fundamental-ngx #5562 

#### Please provide a brief summary of this pull request.
In reactive forms also select can be disabled with out displaying warning messages in console. Example is added for the same in documentation.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [n/a] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-06-17 12:11 UTC, Betrozov commented
if use tab navigation we can go to the disabled select but should not
<img width="212" alt="Screenshot 2021-06-17 at 15 09 16" src="https://user-images.githubusercontent.com/8318592/122394000-2942ba80-cf7e-11eb-9272-c9bbfffbcab5.png">

2021-06-17 12:11 UTC, Betrozov requested changes
if use tab navigation we can go to the disabled select but should not
<img width="212" alt="Screenshot 2021-06-17 at 15 09 16" src="https://user-images.githubusercontent.com/8318592/122394000-2942ba80-cf7e-11eb-9272-c9bbfffbcab5.png">

2021-06-17 12:23 UTC, Betrozov approved these changes

2021-06-17 14:23 UTC, platon-rov approved these changes

2021-06-17 14:45 UTC, Seamoo13 approved these changes

2021-06-18 20:30 UTC, InnaAtanasova approved these changes

2021-06-22 08:24 UTC, merged