fix(platform): condensed as well added for content density in select component
SAP/fundamental-ngx pull request #5726
Opened 2021-06-21 11:22 UTC by sKudum

#### Please provide a link to the associated issue.
Closes SAP/fundamental-ngx #5650 

#### Please provide a brief summary of this pull request.

Condensed as well added for content density along with cozy and compact in select component to stay in sync with core changes.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [n/a] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-06-22 08:30 UTC, olshansky commented on libs/platform/src/lib/components/form/select/commons/base-select.ts
> +        // } else
Looks like it could be removed

2021-06-22 08:35 UTC, kavya-b commented on libs/platform/src/lib/components/form/select/commons/base-select.ts
> +    isCompact: boolean;
should be private

2021-06-22 08:35 UTC, kavya-b commented on libs/platform/src/lib/components/form/select/commons/base-select.ts
>  } from '@fundamental-ngx/core';
i think we should be importing from the split libs now

2021-06-22 08:46 UTC, N1XUS requested changes
Please update imports from fundamental-ngx/core to import from splitted libraries

2021-06-22 11:23 UTC, sKudum commented on libs/platform/src/lib/components/form/select/commons/base-select.ts
> +    isCompact: boolean;
Can't be private used in html.

2021-06-22 11:51 UTC, N1XUS approved these changes

2021-06-22 13:17 UTC, DeepakSap14 approved these changes

2021-06-22 15:33 UTC, Seamoo13 commented
- [ ] compact example is not showing as compact
**actual:**
![2021-06-22](https://user-images.githubusercontent.com/47522152/122953404-5b418b80-d387-11eb-9015-45dae926d938.png)
**expected:**
![2021-06-22_1](https://user-images.githubusercontent.com/47522152/122953422-609ed600-d387-11eb-8ad7-99aa5bd5e9c9.png)

2021-06-22 15:36 UTC, Seamoo13 commented
unit test failed
![2021-06-22_2](https://user-images.githubusercontent.com/47522152/122955442-c93a8280-d388-11eb-9d58-4fe07848e3c2.png)

2021-06-22 20:19 UTC, InnaAtanasova requested changes
<img width="224" alt="Screen Shot 2021-06-22 at 4 16 05 PM" src="https://user-images.githubusercontent.com/39598672/122993360-36441d00-d375-11eb-9663-fbfb1bbacea1.png">

In this case I don't think we should have Cozy and Compact examples in the docs because they are misleading the user. They are both the same. You either need to hardcode the compact mode for the Compact example or remove it.
Also the PR title is misleading. There's no `condensed` state for Select component. I believe Table and prob only 1 other component have this state. For all other components it's cozy and compact.

2021-06-22 20:19 UTC, InnaAtanasova commented on libs/platform/src/lib/components/form/select/commons/base-select.ts
> +     * content Density of element. 'cozy' | 'compact'| 'condensed'
I don't think this component has `condensed` content density. It should be only cozy and compact.

2021-06-23 12:14 UTC, sKudum commented
Hi  @Seamoo13 ,
    1).Compact examples are getting displayed now for default set values.
    2). Test case issue is fixed as well.


Hi @InnaAtanasova ,

   1). Title as well as descriptions are updated.
   2).Compact examples are also reflecting properly when the default set values.

2021-06-23 12:31 UTC, Seamoo13 approved these changes

2021-06-23 15:00 UTC, droshev submitted a review, later dismissed
@sKudum since we have the content density switcher, I don't think it is worth keeping the compact example.
![Screen Shot 2021-06-23 at 11 00 02 AM](https://user-images.githubusercontent.com/4380815/123120286-30e8e000-d412-11eb-8aed-ece8123c3294.png)

2021-06-23 15:24 UTC, sKudum commented
> @sKudum since we have the content density switcher, I don't think it is worth keeping the compact example.
> ![Screen Shot 2021-06-23 at 11 00 02 AM](https://user-images.githubusercontent.com/4380815/123120286-30e8e000-d412-11eb-8aed-ece8123c3294.png)

Hi @droshev ,

    QA team wanted to have these examples with respect to test cases so I did not removed it.

2021-06-25 06:35 UTC, puru-hk commented
> > @sKudum since we have the content density switcher, I don't think it is worth keeping the compact example.
> > ![Screen Shot 2021-06-23 at 11 00 02 AM](https://user-images.githubusercontent.com/4380815/123120286-30e8e000-d412-11eb-8aed-ece8123c3294.png)
> 
> Hi @droshev ,
> 
> ```
> QA team @puru-hk  wanted to have these examples with respect to test cases( contentDensity is set to compact explicitly in this example).so I did not removed it.
> ```

Not Understand clearly why we need to remove the test cases. Need more clarity on this.

2021-06-25 13:52 UTC, droshev commented
@sKudum if you want to keep the condensed then you can do something similar like core button size examples

2021-06-25 14:20 UTC, sKudum commented
> @sKudum if you want to keep the condensed then you can do something similar like core button size examples

Hi @droshev ,
  Added a comment as shown below for compact examples.
<img width="1094" alt="2021-06-25_19-45-55" src="https://user-images.githubusercontent.com/53487468/123438374-40248500-d5ee-11eb-9397-d2e94c89507f.png">

Hope this will help to avoid confusion to user.


_Don't see any information on condensed in core-button though._

2021-06-25 14:57 UTC, dimamarksman commented on libs/platform/src/lib/components/form/select/commons/base-select.ts
> +            this._subscriptions.add(this._contentDensityService._contentDensityListener.subscribe(density => {
every time when we set new `contentDensity` value new subscription will be created (even in case if we already might have one set previously)

2021-07-01 18:32 UTC, dimamarksman approved these changes

2021-07-02 06:15 UTC, sKudum commented
Hi @droshev ,

 We are planing to proceed with merge as all approvals are there , please do let me know in case any other review comments on it. So that I can address them too.

Thank You

2021-07-02 08:59 UTC, merged