docs(core): reduce the size of the notification group example of notification component.
SAP/fundamental-ngx pull request #5736
Opened 2021-06-22 13:01 UTC by manu-kr

#### Please provide a link to the associated issue.
Closes SAP/fundamental-ngx https://github.com/SAP/fundamental-ngx/issues/5648

#### Please provide a brief summary of this pull request.
Reduce the size by removing the unwanted space for notification group example of notification component.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [NA] update `README.md`
- [NA] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-06-22 13:07 UTC, N1XUS commented
I we change height to 350, this happens:
![image](https://user-images.githubusercontent.com/6586561/122929621-d600ab80-d373-11eb-98c3-cf959fdd67a3.png)

I think 700 was initially done to keep everything from the notification group inside demo container

2021-06-22 13:43 UTC, platon-rov approved these changes

2021-06-22 18:15 UTC, mikerodonnell89 requested changes
Let's just remove the min-height altogether

2021-06-22 19:51 UTC, InnaAtanasova commented
> Let's just remove the min-height altogether

This will force the Popover body to appear always above the button. 

<img width="1329" alt="Screen Shot 2021-06-22 at 3 50 10 PM" src="https://user-images.githubusercontent.com/39598672/122990116-93d66a80-d371-11eb-9d32-68ab9e7b9c4b.png">

2021-06-22 19:52 UTC, InnaAtanasova commented
I don't see value in this PR but if you want to reduce the height of the docs container you should make it 500px so it fits the Notification Group example without covering the `Show Code` button

2021-06-25 06:34 UTC, manu-kr commented
> I don't see value in this PR but if you want to reduce the height of the docs container you should make it 500px so it fits the Notification Group example without covering the `Show Code` button.

> Modified.

2021-06-25 20:34 UTC, InnaAtanasova approved these changes

2021-06-28 07:21 UTC, puru-hk commented
Looks fine

2021-06-28 07:21 UTC, puru-hk approved these changes

2021-06-30 17:39 UTC, mikerodonnell89 approved these changes
Looks good now with 500px

2021-07-01 08:50 UTC, merged