test(e2e): add e2e tests for input group component
SAP/fundamental-ngx pull request #5744
Opened 2021-06-23 11:50 UTC by nikvalor

#### Please provide a link to the associated issue.
Closes SAP/fundamental-ngx#5743

#### Please provide a brief summary of this pull request.
add e2e tests for input group (core) component

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-06-23 13:40 UTC, Seamoo13 requested changes

2021-06-23 13:40 UTC, Seamoo13 commented on e2e/wdio/core/tests/input-group.e2e-spec.ts
> +            expect(isEnabled(inputFields, 18)).toBe(false);
please add message for failure

2021-06-23 13:40 UTC, Seamoo13 commented on e2e/wdio/core/pages/input-group.po.ts
> +    contentPage = '#page-content';
contentPage duplicates root

2021-06-23 13:40 UTC, Seamoo13 commented on e2e/wdio/core/pages/input-group.po.ts
> +        waitForPresent(this.contentPage);
maybe use this.title  (it's saved on CoreBaseComponentPo) - will wait for page title to be present

2021-07-01 08:17 UTC, Seamoo13 approved these changes

2021-07-01 12:48 UTC, maxym-valor approved these changes

2021-07-08 19:23 UTC, InnaAtanasova approved these changes

2021-07-12 10:46 UTC, merged