fix(core): fix slider handle edge position
SAP/fundamental-ngx pull request #5761
Opened 2021-06-24 08:15 UTC by Smiranin

#### Please provide a link to the associated issue.
Closes SAP/fundamental-ngx#5529

#### Please provide a brief summary of this pull request.
Added wrapper for slider handle to prevent getting out of the strip edges of slider track. (look related issue)
Also fixed position of "before element" of handle for rtl.

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-06-24 11:23 UTC, dimamarksman commented
I think this fix should be added in the `fundamental-styles` itself. 
@InnaAtanasova what do you think?

2021-06-25 11:53 UTC, dimamarksman commented
I'm not even sure that it's a slider's problem at all. 
Slider's consumer should take into account that a container, that contains the slider, shouldn't use `overflow hidden`

2021-06-25 20:29 UTC, InnaAtanasova commented
> I'm not sure where the fix should be done, here or in the `fundamental-styles` itself.
> @InnaAtanasova what do you think?

This should def be handled in fundamental-styles and then tested in fund-ngx.
@Smiranin please open a PR in Fundamental-styles first.

2021-07-07 21:16 UTC, InnaAtanasova approved these changes

2021-07-08 05:32 UTC, dimamarksman commented
Looks good,
the only minor thing that focus outline is cut

![image](https://user-images.githubusercontent.com/3263744/124867409-e8353900-df72-11eb-889f-2d0674d8c6c1.png)

2021-07-08 05:32 UTC, dimamarksman approved these changes
Looks good,
the only minor thing that focus outline is cut

![image](https://user-images.githubusercontent.com/3263744/124867409-e8353900-df72-11eb-889f-2d0674d8c6c1.png)

2021-07-08 19:32 UTC, InnaAtanasova commented
Please check the failing tests

2021-07-14 20:10 UTC, mikerodonnell89 approved these changes

2021-07-15 10:43 UTC, Betrozov requested changes

2021-07-15 10:43 UTC, Betrozov commented on libs/core/src/lib/slider/slider.component.ts
> +    cozy: boolean = null;
```suggestion
    cozy = false;
```

2021-07-15 12:28 UTC, Betrozov approved these changes

2021-07-16 14:36 UTC, merged