fix(core): provide screen reader access for inline help
SAP/fundamental-ngx pull request #5863
Opened 2021-07-02 13:35 UTC by sKudum

#### Please provide a link to the associated issue.
Closes #4219 

#### Please provide a brief summary of this pull request.
screen reader will read the content in inline help on focus using mouse or tab.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [n/a] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [n/a] Documentation Examples
- [n/a] Stackblitz works for all examples

2021-07-02 17:42 UTC, InnaAtanasova approved these changes

2021-07-02 17:46 UTC, InnaAtanasova commented on libs/core/src/lib/inline-help/inline-help.directive.ts
> +    triggers: string[] = ['mouseenter', 'mouseleave', 'focus', 'focusout'];
shouldn't it be `focusin` instead of `focus` ?

2021-07-08 11:39 UTC, Betrozov requested changes
please remove package-lock.json

2021-07-08 16:39 UTC, aberikashvili approved these changes
LGTM

2021-07-09 08:13 UTC, Betrozov approved these changes

2021-07-09 11:42 UTC, Seamoo13 commented
tested using chrome screen reader extension. for me everything works ok. But I cannot test using JAWS. @puru-hk could you also take a look?

2021-07-09 11:43 UTC, Seamoo13 approved these changes

2021-07-09 11:57 UTC, puru-hk commented
Tested in Jaws 2021 it is working as expected.

2021-07-09 11:58 UTC, puru-hk approved these changes

2021-07-14 12:23 UTC, merged