docs(core): adding tabbable to the cards with list
SAP/fundamental-ngx pull request #5885
Opened 2021-07-05 14:18 UTC by Lokanathan-k

#### Please provide a link to the associated issue.
Closes: https://github.com/SAP/fundamental-ngx/issues/5776

#### Please provide a brief summary of this pull request.

adding tab index to handle the tab key accessibility from card body to card item

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [NA] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [NA] update `README.md`
- [NA] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-07-06 09:25 UTC, platon-rov commented
For some reason when you're getting on the card list first item arrow down navigation works only after 2nd click - could you please fix it if it's related to the card or create an appropriate ticket if it's the list-item issue?

2021-07-06 16:26 UTC, mikerodonnell89 requested changes
I think it would be better to deal with this in the library's code rather than in the example documentation so the developer doesn't have to type this every time.  Is there a reason it has to happen here in the examples?

2021-07-07 08:58 UTC, Lokanathan-k commented
> I think it would be better to deal with this in the library's code rather than in the example documentation so the developer doesn't have to type this every time. Is there a reason it has to happen here in the examples?

the reason is, the card component body container can have any type of component inside, it could be list, or avatar or any other component, so it will be easier if this can be handled by user.

2021-07-07 14:59 UTC, InnaAtanasova commented on apps/docs/src/app/core/component-docs/card/examples/card-compact-example.component.html
> +            <li fd-list-item tabindex="0">
I don't think you are supposed to do this. Check List implementation.

2021-07-07 15:01 UTC, InnaAtanasova commented
> > I think it would be better to deal with this in the library's code rather than in the example documentation so the developer doesn't have to type this every time. Is there a reason it has to happen here in the examples?
> 
> the reason is, the card component body container can have any type of component inside, it could be list, or avatar or any other component, so it will be easier if this can be handled by user.

@mikerodonnell89 has a point here. This is a problem coming from List component. You can observe the behaviour there, too.  The fix should be done in the component (List) not in the documentation of Card component.

2021-07-12 20:02 UTC, InnaAtanasova commented
Please open this PR again when you address the comments. Thanks

2021-07-12 20:02 UTC, closed without merging