docs(platform): update cozy button example in sizes section
SAP/fundamental-ngx pull request #5921
Opened 2021-07-09 10:57 UTC by sKudum

#### Please provide a link to the associated issue.
Closes #5752 

#### Please provide a brief summary of this pull request.
When we change the content density from the central select to compact then the normal button should not become compact. 

The normal example has explicit contentDensity input set to cozy in order to be valid as an example.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [n/a] Run npm run build-pack-library and test in external application

Documentation checklist:
- [n/a] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-07-09 11:10 UTC, Lokanathan-k approved these changes
LGTM

2021-07-09 14:41 UTC, InnaAtanasova approved these changes

2021-07-12 02:31 UTC, droshev requested changes
This is not addressing the issue at all.

You can easily see what I mean by add one core and one platform button in an angular application (without using the content density service)

2021-07-12 08:20 UTC, sKudum commented
> This is not addressing the issue at all.
> 
> You can easily see what I mean by add one core and one platform button in an angular application (without using the content density service)

Hi @droshev ,

 Issue [#5877 ](https://github.com/SAP/fundamental-ngx/issues/5877) has this content density issue in angular applications is raised already and PR [#5936 ](https://github.com/SAP/fundamental-ngx/pull/5936) address the issue.


Where as in current PR changes are done as per the description given in the issue #5752 

<img width="668" alt="2021-07-12_13-48-36" src="https://user-images.githubusercontent.com/53487468/125254259-ea531b00-e317-11eb-8de9-f113411c8f14.png">


Both issues are pointing to different issues as per description given.


Thank You.

2021-07-13 12:29 UTC, olshansky approved these changes

2021-07-14 15:35 UTC, droshev approved these changes

2021-07-15 12:00 UTC, Betrozov approved these changes

2021-07-15 13:42 UTC, merged