fix(core): fix multi-input bugs
SAP/fundamental-ngx pull request #5959
Opened 2021-07-13 13:45 UTC by N1XUS

#### Please provide a link to the associated issue.
Closes #5789

#### Please provide a brief summary of this pull request.
* Selecting a new item by clicking it anywhere other than the checkbox should close the popover (popover should stay open if the checkbox is clicked)
* cmd/ctrl+A to select all tokens then you must press delete twice to delete - should only happen once
* Multi-input should autocomplete like combobox
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- n/a update `README.md`
- [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-07-16 18:21 UTC, InnaAtanasova commented on libs/core/src/lib/multi-input/multi-input.component.ts
> +    handleSelect(checked: any, value: any, resetSearch = true, event?: MouseEvent): void {
missing prefix

2021-07-16 18:22 UTC, InnaAtanasova commented on libs/core/src/lib/token/tokenizer.component.ts
> +    removeSelectedTokens(): void {
missing typedocs for the method

2021-07-16 18:22 UTC, InnaAtanasova commented on libs/core/src/lib/token/tokenizer.component.ts
> +    private _tokensSelected(): boolean {
typedocs missinf

2021-07-19 09:36 UTC, Betrozov requested changes

2021-07-19 09:36 UTC, Betrozov commented on apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-example/multi-input-example.component.html
> +    [placeholder]="'Search here...'"
```suggestion
    placeholder="Search here..."
```

2021-07-19 10:10 UTC, Betrozov approved these changes

2021-07-19 21:34 UTC, InnaAtanasova approved these changes

2021-07-20 14:41 UTC, merged