fix(platform): correct forms validation error message
SAP/fundamental-ngx pull request #5972
Opened 2021-07-14 10:38 UTC by OleksiyDrozdov

#### Please provide a link to the associated issue.
Closes [5326](https://app.zenhub.com/workspaces/fundamental-library-60761c0894e25c0011e828b4/issues/sap/fundamental-ngx/5326) [5651](https://app.zenhub.com/workspaces/fundamental-library-60761c0894e25c0011e828b4/issues/sap/fundamental-ngx/5651)

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [n/a] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [n/a] Documentation Examples
- [x] Stackblitz works for all examples

2021-07-14 11:35 UTC, platon-rov approved these changes

2021-07-14 18:32 UTC, N1XUS approved these changes

2021-07-15 12:04 UTC, Betrozov approved these changes

2021-07-15 18:02 UTC, InnaAtanasova approved these changes

2021-07-19 07:17 UTC, puru-hk commented
Looks fine

2021-07-19 07:17 UTC, puru-hk approved these changes

2021-07-19 11:09 UTC, dimamarksman requested changes
input event as a trigger makes the error message blinking every time I type something

![chrome-capture](https://user-images.githubusercontent.com/3263744/126151269-b6c765a7-ed07-4b26-8f80-53a80d2bd0c6.gif)

2021-07-19 13:31 UTC, dimamarksman approved these changes

2021-07-20 07:16 UTC, merged