test(e2e): add e2e tests for table component
SAP/fundamental-ngx pull request #5993
Opened 2021-07-15 09:51 UTC by nikvalor

#### Please provide a link to the associated issue.
Closes SAP/fundamental-ngx#5909

#### Please provide a brief summary of this pull request.
add e2e tests for table(core) component

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-07-15 10:29 UTC, maxym-valor commented on e2e/wdio/core/tests/table.e2e-spec.ts
> +            setValue(dialogContent + inputGroup, 'date');
use your test variable dateTestText instead just string 'date', will be easier to read code wthout needed to find this variable in fixtures

2021-07-15 10:30 UTC, maxym-valor requested changes

2021-07-15 10:30 UTC, maxym-valor commented on e2e/wdio/core/tests/table.e2e-spec.ts
> +            setValue(dialogContent + inputGroup, 'date');
use your test variable dateTestText instead just string 'date', will be easier to read code wthout needed to find this variable in fixtures

2021-07-16 08:27 UTC, Seamoo13 requested changes
please add additional cases:
- clear search
- toggle loading
- search in custom table config
- sort in custom table config
- cancel btn in custom table config
- table sort
- table filter

also please go through recent bugs related to table core and check that your tests cover them (if possible to cover)
![2021-07-16_3](https://user-images.githubusercontent.com/47522152/125917323-801e1607-8ae9-484c-b630-0f0e7fc5acc8.png)
![2021-07-16_2](https://user-images.githubusercontent.com/47522152/125917330-f218c01a-8a62-47d9-900a-58ce55da6fb8.png)
![2021-07-16_1](https://user-images.githubusercontent.com/47522152/125917333-4c9021c9-44ad-4d2d-8ff8-6291224dc3a2.png)

2021-07-16 08:27 UTC, Seamoo13 commented on e2e/wdio/core/tests/table.e2e-spec.ts
> +                expect(getAttributeByName(tableSemanticExample + tableRow, 'aria-selected', i)).toBe('true');
please add message for failure

2021-07-16 08:27 UTC, Seamoo13 commented on e2e/wdio/core/tests/table.e2e-spec.ts
> +                expect(getAttributeByName(tablePopinExample + tableRow, 'aria-selected', i)).toBe('true');
please add message for failure

2021-07-16 08:27 UTC, Seamoo13 commented on e2e/wdio/core/tests/table.e2e-spec.ts
> +            for (let i = 20; i < checkboxLength; i++) {
why 20? not obvious for debugging/reading. Maybe you can make a var with a name that will make it easy to understand?

2021-07-16 08:27 UTC, Seamoo13 commented on e2e/wdio/core/tests/table.e2e-spec.ts
> +                tablePage.getScreenshotFolder())).toBeLessThan(5, `element item state mismatch`);
maybe better to get initial row count, add new item, get new row count and check last row has the provided data?
screenshot is ok, but not many people are able to update them.

2021-07-22 10:30 UTC, maxym-valor approved these changes

2021-08-11 10:11 UTC, Seamoo13 approved these changes

2021-08-13 18:55 UTC, InnaAtanasova approved these changes

2021-08-16 00:02 UTC, merged