fix(core): remove css from fixed-card-layout component, use correct class names
SAP/fundamental-ngx pull request #6009
Opened 2021-07-16 12:22 UTC by DeepakSap14

#### Please provide a link to the associated issue.
Part of https://github.com/SAP/fundamental-ngx/issues/5025

#### Please provide a brief summary of this pull request.
This PR removes the styles present in Ngx for fixed-card-layout component.
some class name was changed during moving these styles to fundamental-styles repo, so for those correct class names has been used.

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [NA] update `README.md`
- [NA] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-07-16 14:24 UTC, kavya-b approved these changes

2021-07-16 17:59 UTC, InnaAtanasova requested changes
<img width="415" alt="Screen Shot 2021-07-16 at 1 55 13 PM" src="https://user-images.githubusercontent.com/39598672/125989592-e6a9d2b3-7740-44a5-b46a-5370e9579387.png">
<img width="382" alt="Screen Shot 2021-07-16 at 1 55 06 PM" src="https://user-images.githubusercontent.com/39598672/125989596-736b5c4a-1565-41a3-8015-7bc97a158262.png">

There's leaking of styling from `fixed-card-layout` component to all children components because of the use of the universal selector. Table, for example, should not have `break-all` rule for word-break. Please address this. Can be a separate PR but this PR won't be merged without first fixing it.

2021-07-19 09:51 UTC, Betrozov approved these changes

2021-07-21 14:25 UTC, dimamarksman approved these changes

2021-07-22 15:05 UTC, InnaAtanasova approved these changes

2021-07-27 07:34 UTC, puru-hk commented
Even after the disabling the drag and drop example. Able to see the drag and drop Icon.
![drag and drop screenshot](https://user-images.githubusercontent.com/32538291/127114618-2712e704-671b-4e8f-b188-d3d197b64ca6.jpg)

2021-07-30 11:40 UTC, puru-hk commented
Looks fine

2021-07-30 11:40 UTC, puru-hk approved these changes

2021-08-02 08:48 UTC, merged