fix(platform): grouping & frozen columns table layout fix
SAP/fundamental-ngx pull request #6043
Opened 2021-07-20 13:58 UTC by platon-rov

#### Please provide a link to the associated issue.

Closes #5623.

#### Please provide a brief summary of this pull request.

Table layout fixed to support grouping & frozen columns.

Note: Text overflow in the frozen columns will be fixed in scope of #5692, see the screenshot below.

<img width="342" alt="Screenshot 2021-07-20 at 16 57 04" src="https://user-images.githubusercontent.com/20265336/126336723-82841b73-43c7-46f4-ab7d-a5dd078639a5.png">

#### Please check whether the PR fulfills the following requirements

- [X] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [X] tests for the changes that have been done
- [X] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [X] Run npm run build-pack-library and test in external application

Documentation checklist:
- [n/a] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [X] Documentation Examples
- [X] Stackblitz works for all examples

2021-07-20 14:27 UTC, olshansky approved these changes

2021-07-21 12:49 UTC, dimamarksman requested changes
![chrome-capture (1)](https://user-images.githubusercontent.com/3263744/126491035-fdbd9015-5d4a-4fea-afe8-04c2cf2d9f61.gif)

2021-07-21 14:20 UTC, dimamarksman commented
Also I've noticed if we have a horizontal scroll the column resize line is getting shifted away

![image](https://user-images.githubusercontent.com/3263744/126504382-1fcf5e19-f24d-4b67-863c-b3af93e7a70f.png)

2021-07-23 17:01 UTC, KevinOkamoto approved these changes

2021-07-23 18:01 UTC, Smiranin commented on libs/platform/src/lib/components/table/table.component.scss
> +            border-left: var(--sapList_BorderWidth, 0.0625rem) solid var(--sapList_BorderColor, #e4e4e4);
You are using the same value 4 times. May be you create scss variable for border value?

2021-07-28 09:30 UTC, Smiranin approved these changes

2021-07-28 12:14 UTC, dimamarksman approved these changes

2021-07-28 12:15 UTC, merged