docs(platform): add ariba labels to those component doc pages
SAP/fundamental-ngx pull request #6051
Opened 2021-07-21 11:51 UTC by droshev

add ariba labels to those component doc pages

2021-07-21 11:52 UTC, platon-rov approved these changes

2021-07-21 11:53 UTC, dimamarksman approved these changes

2021-07-21 11:54 UTC, olshansky approved these changes

2021-07-21 12:04 UTC, sKudum approved these changes

2021-07-21 12:11 UTC, N1XUS approved these changes

2021-07-21 19:00 UTC, InnaAtanasova requested changes
Please use fund-ngx components

2021-07-21 19:00 UTC, InnaAtanasova commented on apps/docs/src/app/platform/component-docs/platform-page-footer/platform-page-footer-header/platform-page-footer-header.component.html
> +    <span title="Fiori 3 Themeable Component" class="fd-info-label fd-info-label--accent-color-3">themeable</span>
We have Fund-ngx components for this:
```
<fd-info-label label="Info Label" [color]="8" title="SAP Ariba Design"></fd-info-label>
<fd-info-label label="Info Label" [color]="3" title="themeable"></fd-info-label>
```

2021-07-27 14:14 UTC, droshev commented on apps/docs/src/app/platform/component-docs/platform-page-footer/platform-page-footer-header/platform-page-footer-header.component.html
> +<div class="fd-info-labels">
no idea  😄  , it had taken it from another platform example. It has been removed now

2021-07-27 14:14 UTC, droshev commented on apps/docs/src/app/platform/component-docs/platform-page-footer/platform-page-footer-header/platform-page-footer-header.component.html
> +    <span title="Fiori 3 Themeable Component" class="fd-info-label fd-info-label--accent-color-3">themeable</span>
done

2021-07-29 18:20 UTC, InnaAtanasova approved these changes

2021-07-29 18:20 UTC, InnaAtanasova commented
🚀

2021-07-30 19:00 UTC, merged