fix(core): adding extended example and adding extended label to the component
SAP/fundamental-ngx pull request #6061
Opened 2021-07-22 08:52 UTC by Lokanathan-k

#### Please provide a link to the associated issue.
Closes: https://github.com/SAP/fundamental-ngx/issues/3111, https://github.com/SAP/fundamental-ngx/issues/3112

#### Please provide a brief summary of this pull request.

adding extened example and adding extended label to the component

#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [] Run npm run build-pack-library and test in external application

Documentation checklist:
- [NA] update `README.md`
- [NA] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-07-22 14:05 UTC, platon-rov commented
Table (platform) component wrapped in the busy indicator and and `Loading` label is read even if there is no loading state.

2021-07-22 15:55 UTC, InnaAtanasova requested changes
Please provide a more meaningful name for the PR. It doesn't mention for which component the changes are.

2021-07-22 15:55 UTC, InnaAtanasova commented on libs/core/src/lib/busy-indicator/busy-indicator.component.html
> +        }"
not to correct approach for dynamic classes

2021-07-22 16:07 UTC, InnaAtanasova commented
<img width="1050" alt="Screen Shot 2021-07-22 at 12 04 13 PM" src="https://user-images.githubusercontent.com/39598672/126671272-d7bd2462-a8d7-426e-81ec-7d01d9a64b88.png">

Where did you see this in the specs?

In the specs we have extended busy indicator which is displayed inside a message toast.
Message Toast should come with functionality to open and dismiss them. It shouldn't be "static" like:
<img width="1086" alt="Screen Shot 2021-07-22 at 12 07 13 PM" src="https://user-images.githubusercontent.com/39598672/126671694-939cea1e-deeb-46ff-af54-880ac0a4f677.png">

2021-07-23 20:50 UTC, InnaAtanasova commented on libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.component.ts
> +    extended: boolean;
missing typedocs

2021-07-23 20:53 UTC, InnaAtanasova requested changes
Please check the examples with Message Toast in fund-ngx and use a similar one here to showcase extended busy indicator.

2021-07-23 20:53 UTC, InnaAtanasova commented on libs/core/src/lib/busy-indicator/busy-indicator.component.html
> +        }"
please fix this, too

2021-07-28 10:24 UTC, platon-rov commented
Please change title to something more meaningful like `fix(core): extended example, label for the busy indicator` thank you.

2021-07-28 16:34 UTC, Lokanathan-k commented
> This pull request **introduces 1 alert** when merging [76937a7](https://github.com/SAP/fundamental-ngx/commit/76937a780733be1a6056e1aa3defc1ecb05bfba1) into [e30a19b](https://github.com/SAP/fundamental-ngx/commit/e30a19b32dd60815f8593b0ad0b369fb8106fdde) - [view on LGTM.com](https://lgtm.com/projects/g/SAP/fundamental-ngx/rev/pr-6e9a6a362a26ab58ec6127c7172637f9dba6de13)
> 
> **new alerts:**
> 
> * 1 for Unused variable, import, function or class

> fixed

2021-07-29 18:18 UTC, InnaAtanasova requested changes

2021-07-29 18:18 UTC, InnaAtanasova commented on libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.ts
> +    extended: boolean;
I don't get the logic. Why are you adding an `extended` property? If you want an extended busy indicator you add the `fd-busy-indicator-extended` directive. What happens if `extended` is false? It doesn't apply the class. Isn't it the same as just omitting the directive?

2021-07-29 18:18 UTC, InnaAtanasova commented on libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.ts
> +                currentClass + ' fd-busy-indicator-extended fd-busy-indicator-extended--message-toast'
Isn't there a way to just add an additional class to the parent element?

2021-07-29 18:18 UTC, InnaAtanasova commented on libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.spec.ts
> +        expect(fixture.nativeElement.classList.contains('fd-message-toast')).toBe(true);
I don't see a test for `fd-busy-indicator-extended fd-busy-indicator-extended--message-toast` classes. This is what this directive is adding, isn't it?

2021-07-30 11:14 UTC, kavya-b commented on apps/docs/src/app/core/component-docs/busy-indicator/busy-indicator-docs.component.html
> +    Busy Indicator With message toast
```suggestion
    Busy Indicator with Message Toast
```

2021-07-30 11:14 UTC, kavya-b commented on apps/docs/src/app/core/component-docs/busy-indicator/busy-indicator-docs.component.html
> +<fd-docs-section-title id="label" componentName="BusyIndicator"> Busy Indicator With label </fd-docs-section-title>
```suggestion
<fd-docs-section-title id="label" componentName="busy-indicator"> Busy Indicator with label </fd-docs-section-title>
```

2021-07-30 11:14 UTC, kavya-b commented on apps/docs/src/app/core/component-docs/busy-indicator/busy-indicator-docs.component.html
> +    Busy Indicator can be displayed with label to on loading the content. To add the label use
```suggestion
    Busy Indicator can be displayed with label when loading the content. To add the label use
```

2021-07-30 11:14 UTC, kavya-b commented on libs/core/src/lib/busy-indicator/busy-indicator.module.ts
> +    exports: [BusyIndicatorComponent, BusyIndicatorExtendedDirective],
maybe we should also expose the directive in the API tab of documentation?

2021-08-03 09:27 UTC, platon-rov commented on libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.ts
> +    appendCssToParent(): void {
If it's a hidden (not exposed) method - the name should start with `_`.

2021-08-03 09:28 UTC, platon-rov commented on libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.ts
> +    appendCssToParent(): void {
Same for other places.

2021-08-03 10:58 UTC, platon-rov approved these changes

2021-08-03 12:12 UTC, kavya-b commented on libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.ts
> +    _appendCssToParent(): void {
this can also be private

2021-08-03 12:12 UTC, kavya-b commented on libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.ts
> +    elementRef(): ElementRef<HTMLElement> {
ordering of methods should be 1. lifecycle methods, 2. public, 3. private. So this should go before `_appendCssToParent`

2021-08-03 12:12 UTC, kavya-b commented on libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.ts
> +    ngAfterContentInit(): void {
not yet resolved for `ngAfterContentInit`.

2021-08-03 12:12 UTC, kavya-b commented on libs/core/src/lib/busy-indicator/busy-indicator.component.ts
> +    constructor(private _elementRef: ElementRef) {}
not yet fixed

2021-08-03 12:12 UTC, kavya-b commented on apps/docs/src/app/core/component-docs/busy-indicator/busy-indicator-docs.component.html
> +    <code>[labelValue]</code> string property.
```suggestion
    <code>[label]</code> string property.
```

2021-08-03 12:56 UTC, dimamarksman commented on libs/core/src/lib/busy-indicator/busy-indicator.component.html
> +    <span *ngIf="label" class="fd-busy-indicator-extended__label">{{ label }}</span>
in the styles we say that the `label` can be used only within wrapper class `extended`

![image](https://user-images.githubusercontent.com/3263744/128017328-5140cfab-5915-405b-9f7e-7516dc9bb427.png)

Here we just add label without adding a wrapper class

2021-08-03 12:56 UTC, dimamarksman commented on libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.ts
> +        const hasLabel = this.elementRef().nativeElement.firstElementChild.getAttribute('label');
Can we use contentChild to refer to the component instance?
That will guarantee that we are trying to access the valid field

2021-08-03 20:30 UTC, mikerodonnell89 requested changes
Using Google's screenreader, nothing is read when the busy indicator is focused.  And there is no "alternative text" (tooltip?) so I do not think the issues stated in #3111 have been resolved

2021-08-04 08:51 UTC, Betrozov requested changes

2021-08-04 08:51 UTC, Betrozov commented on libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.ts
> +            }
```suggestion
            const { classList } = this.elementRef().nativeElement.parentElement;
            classList.add('fd-busy-indicator-extended');
            if (classList.contains(messageToastClass)) {
                classList.add('fd-busy-indicator-extended--message-toast');
            }
```

2021-08-04 09:32 UTC, dimamarksman commented on apps/docs/src/app/core/component-docs/busy-indicator/examples/busy-indicator-label-example.component.html
> +<div style="text-align: center" fd-busy-indicator-extended>
```suggestion
<div fd-busy-indicator-extended>
```

2021-08-04 10:11 UTC, Lokanathan-k commented
> Using Google's screenreader, nothing is read when the busy indicator is focused. And there is no "alternative text" (tooltip?) so I do not think the issues stated in #3111 have been resolved

![9b5543fc-8522-4dae-8bbf-76ad8384ffe0](https://user-images.githubusercontent.com/53534379/128163917-1ecf5dd3-8a45-4959-9545-0367bc0c0c85.jpg)
![ad534741-ccfc-4b06-a0bf-18c704a7f89a](https://user-images.githubusercontent.com/53534379/128163947-45bb2828-9911-4b3e-bdee-e5158fb42e81.jpg)


fixed

2021-08-04 12:09 UTC, platon-rov approved these changes

2021-08-04 12:22 UTC, dimamarksman approved these changes

2021-08-04 14:36 UTC, kavya-b approved these changes

2021-08-04 18:56 UTC, Betrozov approved these changes

2021-08-04 19:53 UTC, mikerodonnell89 approved these changes

2021-08-05 05:31 UTC, Lokanathan-k commented
@puru-hk @Sanjay-1312 on testing the component found the extend busy indicator does-not read the content and found the issue needs to be fixed as part of the issue(https://github.com/SAP/fundamental-ngx/issues/5802). message toast component.

2021-08-05 05:32 UTC, puru-hk commented
Expect message toast screen reader issue all the other issues is addressed.

2021-08-05 05:32 UTC, puru-hk approved these changes

2021-08-05 13:34 UTC, InnaAtanasova approved these changes

2021-08-06 07:35 UTC, merged