fix(core): remove style from ngx to reuse the style from fundamental-style lib for file uploader component
SAP/fundamental-ngx pull request #6194
Opened 2021-08-02 08:06 UTC by manu-kr

#### Please provide a link to the associated issue.
Part of #5025

#### Please provide a brief summary of this pull request.
PR change contains remove style from ngx to reuse the style from fundamental-style lib for file uploader component.
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [NA] update `README.md`
- [NA] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [x] Documentation Examples
- [x] Stackblitz works for all examples

2021-08-02 08:47 UTC, Lokanathan-k approved these changes
LGTM

2021-08-02 09:24 UTC, kavya-b approved these changes

2021-08-02 10:05 UTC, N1XUS approved these changes

2021-08-03 14:36 UTC, KevinOkamoto approved these changes

2021-08-03 21:50 UTC, mikerodonnell89 approved these changes

2021-08-03 21:58 UTC, mikerodonnell89 requested changes
I initially approved because this PR is technically is doing what the linked issue says, but I'm wondering if we need to be applying the `is-error` class to the input element when the component's `state` value changes to `error`?  For example the input stays the same if I try to upload a 1kb file in the "min file size" example. Perhaps that is out of the scope of this PR

2021-08-04 12:29 UTC, manu-kr commented
> I initially approved because this PR is technically is doing what the linked issue says, but I'm wondering if we need to be applying the `is-error` class to the input element when the component's `state` value changes to `error`? For example the input stays the same if I try to upload a 1kb file in the "min file size" example. Perhaps that is out of the scope of this PR

> This is out of scope for this PR. Can we create new issue for this.

2021-08-04 20:35 UTC, mikerodonnell89 approved these changes

2021-08-05 07:27 UTC, merged