test(e2e): fix failed tests for prod mode(core/platform)
SAP/fundamental-ngx pull request #6230
Opened 2021-08-04 09:09 UTC by nikvalor

#### Please provide a link to the associated issue.
Closes none

#### Please provide a brief summary of this pull request.
unskip failed tests for prod mode for core and platform
#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-08-04 09:33 UTC, Seamoo13 requested changes

2021-08-04 09:33 UTC, Seamoo13 commented on e2e/wdio/core/tests/combobox.e2e-spec.ts
> +    fit('verify disable input field', () => {
remove `f`

2021-08-04 09:33 UTC, Seamoo13 commented on e2e/wdio/core/tests/object-status.e2e-spec.ts
> +        it('should check object status is large', () => {
think you can just leave it skipped for now since the assertion is skipped (`xit`)

2021-08-04 09:33 UTC, Seamoo13 commented on e2e/wdio/core/tests/slider.e2e-spec.ts
>          it('should check tick marks', () => {
if you comment out the assertion, no need to leave scrollintoview, just skip the test case `xit`

2021-08-04 09:33 UTC, Seamoo13 commented on e2e/wdio/core/tests/slider.e2e-spec.ts
>          it('should check range slider is disabled', () => {
same as above

2021-08-04 09:33 UTC, Seamoo13 commented on e2e/wdio/core/tests/slider.e2e-spec.ts
> +        it('should check cozy property', () => {
same as above

2021-08-04 09:33 UTC, Seamoo13 commented on e2e/wdio/core/tests/slider.e2e-spec.ts
> +        it('should check ability to disable slider', () => {
same.. clicking is pointless if there's no assertion. just skip and we'll look harder later

2021-08-04 09:33 UTC, Seamoo13 commented on e2e/wdio/core/tests/card.e2e-spec.ts
> +            expect(getAttributeByName(compactCardAttr, 'class')).toBe(compactAttr);
we have a method getElementClass(selector, index);

2021-08-04 14:37 UTC, Seamoo13 approved these changes

2021-08-05 07:17 UTC, maxym-valor approved these changes

2021-08-05 07:18 UTC, N1XUS approved these changes

2021-08-06 03:01 UTC, merged