fix(platform): wizard-generator, skip notification about save progress if nothing change
SAP/fundamental-ngx pull request #6335
Opened 2021-08-13 14:34 UTC by Betrozov

#### Please provide a link to the associated issue.
Closes https://github.com/SAP/fundamental-ngx/issues/6279

#### Please provide a brief summary of this pull request.
Added skip of notification about save progress if nothing change
#### Please check whether the PR fulfills the following requirements

- [X] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [X] tests for the changes that have been done
- [X] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [X] Run npm run build-pack-library and test in external application

Documentation checklist:
- [X] update `README.md`
- [X] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [X] Documentation Examples
- [X] Stackblitz works for all examples

2021-08-14 19:31 UTC, N1XUS commented on libs/platform/src/lib/components/wizard-generator/wizard-generator.service.ts
> +            component.forms.some((item) => Object.values(item.form.value).some((x) => x !== undefined && x !== ''))
I think this might not work appropriately due to the ability to set a default value. Maybe check for dirty or touched instead?

2021-08-17 08:49 UTC, dimamarksman commented on libs/platform/src/lib/components/wizard-generator/wizard-generator.service.ts
> +        return ![...this.stepsComponents].some(([_, component]) => component.forms.some((item) => !item.form.pristine));
can we avoid `!` and use `every()` instead of `some()`?

2021-08-17 22:18 UTC, mikerodonnell89 requested changes
If I open the "wizard generator in dialog" example and immediately click cancel I still see the message

2021-08-18 13:36 UTC, Betrozov commented
> If I open the "wizard generator in dialog" example and immediately click cancel I still see the message

Hi @mikerodonnell89 
I tried to reproduce what did you say but I cannot successfully reproduce it, in my case, it just closed without any messages.
Could you test it again and if you still can reproduce it please add some extra info (browser, browser version, ....)
Thanks

2021-08-18 14:54 UTC, dimamarksman approved these changes

2021-08-19 03:40 UTC, mikerodonnell89 commented
> > If I open the "wizard generator in dialog" example and immediately click cancel I still see the message
> 
> Hi @mikerodonnell89
> I tried to reproduce what did you say but I cannot successfully reproduce it, in my case, it just closed without any messages.
> Could you test it again and if you still can reproduce it please add some extra info (browser, browser version, ....)
> Thanks

Apologies, I must've been testing at the wrong URL.  Approved

2021-08-19 03:40 UTC, mikerodonnell89 approved these changes

2021-08-19 09:34 UTC, maxym-valor commented
@Betrozov

1) Open https://fundamental-ngx.netlify.app/#/platform/wizard-generator#responsive-paddings-in-dialog
2) Click Open wizard in dialog
3) Click Cancel
This works correct, no question if you did nothing

BUT if:

1) Open https://fundamental-ngx.netlify.app/#/platform/wizard-generator#responsive-paddings-in-dialog
2) Click Open wizard in dialog
3) select any type in drop-down
4) click Next
5) on second step click 'Cancel'
Expected result: dialog with the question 'Are you sure you want to discard your progress?'
Actual result: no dialog, but should be, because you did actions on first step
But if you enter anything on second step and click 'Cancel' - will be dialog. Needs improvement

2021-08-20 12:19 UTC, merged