[WIP]test(e2e): add e2e tests for page footer platform
SAP/fundamental-ngx pull request #6353
Opened 2021-08-17 09:28 UTC by puru-hk

#### Please provide a link to the associated issue.
Closes

#### Please provide a brief summary of this pull request.

#### Please check whether the PR fulfills the following requirements

- [ ] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application

Documentation checklist:
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ ] Documentation Examples
- [ ] Stackblitz works for all examples

2021-08-17 10:49 UTC, Seamoo13 commented
please get a passing Travis build before requesting reviews

2021-08-18 08:15 UTC, Seamoo13 requested changes

2021-08-18 08:15 UTC, Seamoo13 commented on e2e/wdio/platform/tests/page-footer.e2e-spec.ts
> +            expect(getText(pagefootertext, 2)).toEqual('1992-2021 @copyright all right reserved.', 'Text is not matching Index2');
when the assertion is clear (expect to equal 'this specific text') then you don't need to add a failure message. We only do that if the assertion is true/false (expect to be true) to add clarity as to what should be happening.

2021-08-18 08:15 UTC, Seamoo13 commented on e2e/wdio/platform/tests/page-footer.e2e-spec.ts
> +    describe('Check visual regression basic', function() {
please add a skip, as discussed on the previous week's call, we have temporarily skipped visual regression cases until we get a new tool up, due to instability and amount of time QA spends daily on updating screenshots in multiple PRs. to do this, just rename the `describe` to `xdescribe`

2021-08-18 08:15 UTC, Seamoo13 commented on e2e/wdio/platform/tests/page-footer.e2e-spec.ts
> +});
just a general note, when the test spec is so small, you can organize it 2 ways which are a little better for reading.

way 1.

describe(x test suite)..
describe('main checks')..
it..
it..
it..
describe('visual regression and RTL)..
it..
it..



way 2.

describe(x test suite)..
it..
it..
it..
it..

2021-08-18 08:15 UTC, Seamoo13 commented on e2e/wdio/platform/tests/page-footer.e2e-spec.ts
> +describe('PageFooter test suite:', function() {
page footer is 2 words

2021-08-18 08:15 UTC, Seamoo13 commented on e2e/wdio/platform/tests/page-footer.e2e-spec.ts
> +        it('should check pagefooter text', () => {
page footer is 2 words

2021-08-18 08:15 UTC, Seamoo13 commented on e2e/wdio/platform/tests/page-footer.e2e-spec.ts
> +        it('verify clickable links ', () => {
this sounds like you are only checking a certain set of links. please rename to 'verify links are clickable'

2021-08-18 08:15 UTC, Seamoo13 commented on e2e/wdio/platform/pages/page-footer.po.ts
> +        waitForPresent(this.title);
please also add `waitForElDisplayed(this.root);` here

2021-08-18 08:17 UTC, Seamoo13 commented
also need to add url to the wdio-cron.config.js file or the cron job will not run tests here

2021-08-19 07:12 UTC, maxym-valor commented
pls, fix tabulation for iterations. How it should be: 
![image](https://user-images.githubusercontent.com/83698366/130024448-5d2a0515-8f8b-4fb7-a1aa-e3ba05b03053.png)

2021-08-19 07:14 UTC, maxym-valor commented on e2e/wdio/platform/tests/page-footer.e2e-spec.ts
> +                expect(isElementClickable(pageFooterClickableLink, i)).toBe(true, 'link with index ${i} not clickable');
error message will not work as you wish, if you want to use template literal - quotes should be ``, not ''

2021-08-19 07:14 UTC, maxym-valor commented on e2e/wdio/platform/tests/page-footer.e2e-spec.ts
> +    getText,
remove unused method

2021-08-19 07:18 UTC, maxym-valor commented on e2e/wdio/platform/pages/page-footer.po.ts
> +    }
why did you remove `waitForPresent(this.title);` ?

2021-08-19 08:47 UTC, maxym-valor commented on e2e/wdio/platform/tests/page-footer.e2e-spec.ts
> +                expect(isElementClickable(pageFooterClickableLink, i)).toBe(true, "link with index ${i} not clickable");
wrong quotes again 😁
not "" and not '', should be ``
` expect(isElementClickable(pageFooterClickableLink, i)).toBe(true, `link with index ${i} not clickable`);`

2021-08-19 15:16 UTC, Seamoo13 approved these changes
Approved, but still need to make the formatting/spacing correction described by Max.

2021-08-20 07:14 UTC, maxym-valor approved these changes

2021-08-23 05:43 UTC, Smiranin approved these changes

2021-08-24 14:56 UTC, merged