fix(platform): tab order in safari
SAP/fundamental-ngx pull request #6386
Opened 2021-08-25 16:07 UTC by genereg1

#### Please provide a link to the associated issue.
Closes https://github.com/SAP/fundamental-ngx/issues/5541

#### Please provide a brief summary of this pull request.
#### Please check whether the PR fulfills the following requirements

- [x] the commit message follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application

Documentation checklist:
- [n/a] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [n/a] Documentation Examples
- [x] Stackblitz works for all examples

2021-08-31 11:50 UTC, Betrozov approved these changes

2021-08-31 17:13 UTC, mikerodonnell89 requested changes
Seeing some strange behavior here (seems to be introduced by this PR).  If I refresh the page and immediately click in to the first combobox and type "a" - the combobox popover body opens but no letter appears in the input. Happening in all browsers.  I can start typing into the combobox by clicking back in to the input and typing, after this first issue happens.

2021-09-01 16:11 UTC, genereg1 commented
> Seeing some strange behavior here (seems to be introduced by this PR). If I refresh the page and immediately click in to the first combobox and type "a" - the combobox popover body opens but no letter appears in the input. Happening in all browsers. I can start typing into the combobox by clicking back in to the input and typing, after this first issue happens.

@mikerodonnell89 I agree with your point. Seems it's an issue, but it's not introduced by this PR the same issue reproduces in main branch. Probably we need to create another ticket to solve this issue

2021-09-06 11:55 UTC, genereg1 commented
> > Seeing some strange behavior here (seems to be introduced by this PR). If I refresh the page and immediately click in to the first combobox and type "a" - the combobox popover body opens but no letter appears in the input. Happening in all browsers. I can start typing into the combobox by clicking back in to the input and typing, after this first issue happens.
> 
> @mikerodonnell89 I agree with your point. Seems it's an issue, but it's not introduced by this PR the same issue reproduces in main branch. Probably we need to create another ticket to solve this issue

Already fixed by https://github.com/SAP/fundamental-ngx/pull/6382

2021-09-07 19:25 UTC, mikerodonnell89 approved these changes

2021-09-08 08:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/fundamental-ngx?pullRequest=6386) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/fundamental-ngx?pullRequest=6386) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/fundamental-ngx?pullRequest=6386) it.</sub>

2021-09-08 09:16 UTC, merged