fix(platform): fix wizard generator related issues
SAP/fundamental-ngx pull request #6489
Opened 2021-09-09 10:22 UTC by N1XUS

## Related Issue.
Closes #6488 #6487 #6245

## Description

fix object rendering on summary page
fix overriding layout of form field
fix hiding navigation buttons for wizard generator
added example with object rendering on summary page
added example of external navigation buttons

#### Please check whether the PR fulfills the following requirements

##### During Implementation
1. Visual Testing:
- [n/a] visual misalignments/updates
- [n/a] check Light/Dark/HCB/HCW themes
- [n/a] RTL/LTR - proper rendering and labeling
- [n/a] responsiveness(resize)
- [n/a] Content Density (Cozy/Compact/(Condensed))
- [n/a] States - hover/disabled/focused/active/on click/selected/selected hover/press state
- [n/a] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
- [n/a] Mouse vs. Keyboard support
- [n/a] Text Truncation
2. API and functional correctness
- [x] check for console logs (warnings, errors)
- [x] API boundary values
- [x] different combinations of components - free style
- [x] change the API values during testing
3. Documentation and Example validations
- [ ] missing API documentation or it is not understandable
- [ ] poor examples
- [x] Stackblitz works for all examples
4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality
- [x] the commit message(s) follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application
- [x] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

##### PR Review
- [ ] visual misalignments/updates
- [ ] check Light/Dark/HCB/HCW themes
- [ ] RTL/LTR - proper rendering and labeling
- [ ] responsiveness(resize)
- [ ] Content Density (Cozy/Compact/(Condensed))
- [ ] States - hover/disabled/focused/active/on click/selected/selected hover/press state
- [ ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
- [ ] Mouse vs. Keyboard support
- [ ] Text Truncation
2. API and functional correctness
- [ ] check for console logs (warnings, errors)
- [ ] API boundary values
- [ ] different combinations of components - free style
- [ ] change the API values during testing
3. Documentation and Example validations
- [ ] missing API documentation or it is not understandable
- [ ] poor examples
- [ ] Stackblitz works for all examples
4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

2021-09-09 14:20 UTC, platon-rov requested changes

2021-09-09 14:32 UTC, N1XUS commented on libs/platform/src/lib/wizard-generator/components/wizard-summary-step/wizard-summary-section/wizard-summary-section.component.ts
> +    async ngOnInit(): Promise<void> {
Yes, it's intended. This component don't have additional hooks, so it should be fine

2021-09-09 16:28 UTC, platon-rov approved these changes
Please fix Travis

2021-09-09 16:32 UTC, puru-hk commented
@N1XUS Could you please fix this issue #6474. This issue also related to wizard generator

2021-09-09 16:52 UTC, InnaAtanasova approved these changes

2021-09-09 18:11 UTC, N1XUS commented
> Please fix Travis



> @N1XUS Could you please fix this issue #6474. This issue also related to wizard generator

@puru-hk I'm not able to reproduce the issue on this branch by reproducing the steps in the video from the issue itself. Can you confirm that it's reproducible on your side?

2021-09-10 01:53 UTC, puru-hk commented
> > Please fix Travis
> 
> > @N1XUS Could you please fix this issue #6474. This issue also related to wizard generator
> 
> @puru-hk I'm not able to reproduce the issue on this branch by reproducing the steps in the video from the issue itself. Can you confirm that it's reproducible on your side?

Yes re-verified it is working fine now.

2021-09-10 09:31 UTC, dimamarksman commented on libs/platform/src/lib/wizard-generator/components/wizard-generator/wizard-generator.component.html
> +        [hidden]="!wizardCreated"
what the sense is to have `[hidden]="!wizardCreated"` and parent with `*ngIf="wizardCreated"`?

2021-09-10 09:47 UTC, dimamarksman approved these changes

2021-09-10 11:13 UTC, merged