feat(platform): search field add missing examples and refresh mode
SAP/fundamental-ngx pull request #6694
Opened 2021-09-21 18:25 UTC by genereg1

## Related Issue.
Closes https://github.com/SAP/fundamental-ngx/issues/4233
Closes https://github.com/sap/fundamental-ngx/issues/4237

## Description

- added Search Field Mobile example 
- added Refresh button behaviour 

## Screenshots
> **NOTE:** If you've made any style changes, please provide appropriate screenshots (before and after) to help reviewers.

### Before:

### After:

#### Please check whether the PR fulfills the following requirements

##### During Implementation
1. Visual Testing:
- [x] visual misalignments/updates
- [x] check Light/Dark/HCB/HCW themes
- [x] RTL/LTR - proper rendering and labeling
- [x] responsiveness(resize)
- [x] Content Density (Cozy/Compact/(Condensed))
- [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
- [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
- [x] Mouse vs. Keyboard support
- [x] Text Truncation
2. API and functional correctness
- [x] check for console logs (warnings, errors)
- [x] API boundary values
- [x] different combinations of components - free style
- [x] change the API values during testing
3. Documentation and Example validations
- [x] missing API documentation or it is not understandable
- [x] poor examples
- [x] Stackblitz works for all examples
4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality
- [x] the commit message(s) follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [x] tests for the changes that have been done
- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [x] Run npm run build-pack-library and test in external application
- [n/a] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

##### PR Review
- [x] visual misalignments/updates
- [x] check Light/Dark/HCB/HCW themes
- [x] RTL/LTR - proper rendering and labeling
- [x] responsiveness(resize)
- [x] Content Density (Cozy/Compact/(Condensed))
- [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
- [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
- [x] Mouse vs. Keyboard support
- [x] Text Truncation
2. API and functional correctness
- [x] check for console logs (warnings, errors)
- [x] API boundary values
- [x] different combinations of components - free style
- [x] change the API values during testing
3. Documentation and Example validations
- [x] missing API documentation or it is not understandable
- [x] poor examples
- [x] Stackblitz works for all examples
4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

2021-09-23 09:15 UTC, Betrozov requested changes

2021-09-23 09:15 UTC, Betrozov commented on apps/docs/src/app/platform/component-docs/platform-search-field/platform-search-field-examples/platform-search-field-mobile/platform-search-field-mobile-example.component.ts
> +    ngOnInit(): void {
you do not need ngOnInit
please remove it

2021-09-23 09:15 UTC, Betrozov commented on libs/platform/src/lib/search-field/search-field-mobile/search-field-mobile.component.ts
> +    } = null;
please create interface for it

2021-09-23 09:15 UTC, Betrozov commented on libs/platform/src/lib/search-field/search-field.component.ts
> +                    }
```suggestion
                    if (this.clearId === target.id && !this.isSearchDone) {
                        this._isFocused = false;
                    }
```

2021-09-23 13:12 UTC, platon-rov requested changes
1. Dialog doesn't open on input focus.
2. In dialog focus trapped on the input, cannot go anywhere.
3. Dialog doesn't close with `Escape`.
4. Refresh button disappears when input in focus, so cannot tab into it.
5. Cannot tab into any buttons in the input like Clear, Search.
6. When having option select in dialog, then pressing Refresh the Search button disappears.

2021-09-23 13:12 UTC, platon-rov commented on libs/platform/src/lib/search-field/search-field-mobile/search-field-mobile.component.ts
> +    ngOnInit(): void {
TypeDoc.

2021-09-23 13:12 UTC, platon-rov commented on libs/platform/src/lib/search-field/search-field.component.ts
> +    @Output()
TypeDoc.

2021-09-23 13:12 UTC, platon-rov commented on libs/platform/src/lib/search-field/search-field.component.ts
> +    isSearchDone = false;
Let's organise fields like `public` then `private`.

2021-09-24 17:17 UTC, platon-rov requested changes
It should probably be `feat(platform)`

2021-09-24 17:17 UTC, platon-rov commented on apps/docs/src/app/platform/component-docs/platform-search-field/platform-search-field.module.ts
> +    providers: [{ provide: MOBILE_MODE_CONFIG, useValue: SEARCH_FIELD_MOBILE_CONFIG, multi: true }],
We're not providing config in the components' modules. It should be provided in Docs modules.

2021-09-27 10:06 UTC, platon-rov requested changes

2021-09-27 10:06 UTC, platon-rov commented on libs/platform/src/lib/search-field/search-field.component.ts
>      @Input()
Let make this component implementing `SearchFieldMobileInterface`.

2021-09-27 10:06 UTC, platon-rov commented on libs/platform/src/lib/search-field/public_api.ts
> +export * from './search-field-mobile/search-field-mobile.module';
Please also export `search-field-mobile.interface.ts`.

2021-09-29 08:24 UTC, Betrozov approved these changes

2021-09-30 10:48 UTC, platon-rov approved these changes

2021-10-26 10:18 UTC, merged