feat(platform): wizard generator summary edit button logic
SAP/fundamental-ngx pull request #6698
Opened 2021-09-22 13:50 UTC by N1XUS

## Related Issue.
Closes #6592 

## Description
Changed logic of steps navigation if user comes from Summary step (clicks on Edit button).
Added new directive to create custom "Review" button.

#### Please check whether the PR fulfills the following requirements

##### During Implementation
1. Visual Testing:
- [x] visual misalignments/updates
- [x] check Light/Dark/HCB/HCW themes
- [x] RTL/LTR - proper rendering and labeling
- [x] responsiveness(resize)
- [x] Content Density (Cozy/Compact/(Condensed))
- [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
- [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
- [x] Mouse vs. Keyboard support
- [x] Text Truncation
2. API and functional correctness
- [x] check for console logs (warnings, errors)
- [x] API boundary values
- [x] different combinations of components - free style
- [x] change the API values during testing
3. Documentation and Example validations
- [x] missing API documentation or it is not understandable
- [x] poor examples
- [x] Stackblitz works for all examples
4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality
- [ ] the commit message(s) follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

##### PR Review
- [ ] visual misalignments/updates
- [ ] check Light/Dark/HCB/HCW themes
- [ ] RTL/LTR - proper rendering and labeling
- [ ] responsiveness(resize)
- [ ] Content Density (Cozy/Compact/(Condensed))
- [ ] States - hover/disabled/focused/active/on click/selected/selected hover/press state
- [ ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
- [ ] Mouse vs. Keyboard support
- [ ] Text Truncation
2. API and functional correctness
- [ ] check for console logs (warnings, errors)
- [ ] API boundary values
- [ ] different combinations of components - free style
- [ ] change the API values during testing
3. Documentation and Example validations
- [ ] missing API documentation or it is not understandable
- [ ] poor examples
- [ ] Stackblitz works for all examples
4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

2021-09-22 19:11 UTC, N1XUS commented
Travis failing unit test is related to #6696

2021-09-23 09:23 UTC, Betrozov requested changes

2021-09-23 09:23 UTC, Betrozov commented on libs/core/src/lib/wizard/wizard.component.ts
> +                step.content?.nextStep.canHide &&
```suggestion
                step.content?.nextStep?.canHide &&
```

2021-09-23 09:23 UTC, Betrozov commented on libs/platform/src/lib/wizard-generator/components/wizard-body/wizard-body.component.ts
> +        console.log(stepIndex);
please remove

2021-09-23 09:23 UTC, Betrozov commented on libs/platform/src/lib/wizard-generator/components/wizard-generator/wizard-generator.component.ts
> +    customSummaryStepTemplate: TemplateRef<any>;
please try to avoid using any

2021-09-23 09:23 UTC, Betrozov commented on libs/platform/src/lib/wizard-generator/components/wizard-generator/wizard-generator.component.ts
> +    reviewButtonTemplate: TemplateRef<any>;
same here

2021-09-23 14:22 UTC, platon-rov requested changes
Great work, some minor items.

2021-09-23 14:22 UTC, platon-rov commented on libs/platform/src/lib/wizard-generator/components/wizard-body/wizard-body.component.ts
> +        console.log(this);
please remove.

2021-09-23 14:41 UTC, Betrozov approved these changes

2021-09-23 16:07 UTC, platon-rov approved these changes

2021-09-24 15:16 UTC, merged