docs(core): add tabindex in icon examples components
SAP/fundamental-ngx pull request #6709
Opened 2021-09-23 11:42 UTC by OleksiyDrozdov

## Related Issue.
Closes SAP/fundamental-ngx/[#6195](https://github.com/SAP/fundamental-ngx/issues/6195)

#### Please check whether the PR fulfills the following requirements

##### During Implementation
1. Visual Testing:
- [x] visual misalignments/updates
- [n/a] check Light/Dark/HCB/HCW themes
- [x] RTL/LTR - proper rendering and labeling
- [x] responsiveness(resize)
- [n/a] Content Density (Cozy/Compact/(Condensed))
- [n/a] States - hover/disabled/focused/active/on click/selected/selected hover/press state
- [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
- [x] Mouse vs. Keyboard support
- [n/a] Text Truncation
2. API and functional correctness
- [x] check for console logs (warnings, errors)
- [n/a] API boundary values
- [n/a] different combinations of components - free style
- [n/a] change the API values during testing
3. Documentation and Example validations
- [n/a] missing API documentation or it is not understandable
- [n/a] poor examples
- [n/a] Stackblitz works for all examples
4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality
- [ ] the commit message(s) follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [ ] tests for the changes that have been done
- [ ] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [ ] Run npm run build-pack-library and test in external application
- [ ] update `README.md`
- [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

##### PR Review
- [ ] visual misalignments/updates
- [ ] check Light/Dark/HCB/HCW themes
- [ ] RTL/LTR - proper rendering and labeling
- [ ] responsiveness(resize)
- [ ] Content Density (Cozy/Compact/(Condensed))
- [ ] States - hover/disabled/focused/active/on click/selected/selected hover/press state
- [ ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
- [ ] Mouse vs. Keyboard support
- [ ] Text Truncation
2. API and functional correctness
- [ ] check for console logs (warnings, errors)
- [ ] API boundary values
- [ ] different combinations of components - free style
- [ ] change the API values during testing
3. Documentation and Example validations
- [ ] missing API documentation or it is not understandable
- [ ] poor examples
- [ ] Stackblitz works for all examples
4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

2021-09-24 16:38 UTC, InnaAtanasova requested changes
This is a documentation PR. Please update the title accordingly.

2021-09-27 15:23 UTC, Smiranin approved these changes

2021-09-29 08:21 UTC, Betrozov approved these changes

2021-10-01 18:20 UTC, InnaAtanasova approved these changes

2021-10-05 07:57 UTC, puru-hk commented
Hello Colleagues 

Issue 1: Fixed.

Issue 2: Fixed.

Retest Details:

https://deploy-preview-6709--fundamental-ngx.netlify.app/#/core/icon
JAWS 2021

2021-10-05 07:58 UTC, puru-hk approved these changes

2021-10-05 10:30 UTC, merged