fix(platform): extend MatchingStrategy
SAP/fundamental-ngx pull request #6768
Opened 2021-09-29 12:49 UTC by Betrozov

## Related Issue.
Closes https://github.com/sap/fundamental-ngx/issues/3529

## Description

Extended MatchingStrategy
Added STARTS_WITH_PER_TERM matching strategy, set to use by default for combobox, multi-combobox, multi-input platform components

#### Please check whether the PR fulfills the following requirements

##### During Implementation
1. Visual Testing:
- [n/a] visual misalignments/updates
- [n/a] check Light/Dark/HCB/HCW themes
- [n/a] RTL/LTR - proper rendering and labeling
- [n/a] responsiveness(resize)
- [n/a] Content Density (Cozy/Compact/(Condensed))
- [n/a] States - hover/disabled/focused/active/on click/selected/selected hover/press state
- [n/a] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
- [n/a] Mouse vs. Keyboard support
- [n/a] Text Truncation
2. API and functional correctness
- [n/a] check for console logs (warnings, errors)
- [n/a] API boundary values
- [n/a] different combinations of components - free style
- [n/a] change the API values during testing
3. Documentation and Example validations
- [n/a] missing API documentation or it is not understandable
- [n/a] poor examples
- [n/a] Stackblitz works for all examples
4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality
- [X] the commit message(s) follows the guideline:
https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
- [X] tests for the changes that have been done
- [X] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
- [n/a] Run npm run build-pack-library and test in external application
- [n/a] update `README.md`
- [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

##### PR Review
- [ ] visual misalignments/updates
- [ ] check Light/Dark/HCB/HCW themes
- [ ] RTL/LTR - proper rendering and labeling
- [ ] responsiveness(resize)
- [ ] Content Density (Cozy/Compact/(Condensed))
- [ ] States - hover/disabled/focused/active/on click/selected/selected hover/press state
- [ ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
- [ ] Mouse vs. Keyboard support
- [ ] Text Truncation
2. API and functional correctness
- [ ] check for console logs (warnings, errors)
- [ ] API boundary values
- [ ] different combinations of components - free style
- [ ] change the API values during testing
3. Documentation and Example validations
- [ ] missing API documentation or it is not understandable
- [ ] poor examples
- [ ] Stackblitz works for all examples
4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

2021-09-30 16:21 UTC, platon-rov requested changes
great work! one small note

2021-09-30 16:21 UTC, platon-rov commented on libs/platform/src/lib/shared/domain/base-data-provider.ts
> +            const reqexp = new RegExp(`(\\s|^)${pattern}`, 'gi');
I saw this regexp 3 times so let's create a function where we will be testing for matching to this regexp.

2021-10-05 06:39 UTC, platon-rov approved these changes

2021-10-05 09:26 UTC, manu-kr approved these changes

2021-10-05 14:21 UTC, Seamoo13 commented
- [ ] 1. bug: when you type in a combobox OR multi-combobox, the matching result text is altered to replace searched text with `$2` 

**STR:**
1. go to a combobox or multi-combobox
2. click on the input field
3. start typing the name of an item (i.e. 'ap' for apple)
4. check the dropdown result
**results:** result name altered with `$2`
**Expected:** no `$2`

https://user-images.githubusercontent.com/47522152/136041127-54210c2a-9dc4-46f9-9efa-e7f745d05336.mp4

![2021-10-05_10](https://user-images.githubusercontent.com/47522152/136041080-bc76056a-403e-4f81-86ef-fdc143e7e53a.png)
![2021-10-05_9](https://user-images.githubusercontent.com/47522152/136041086-afb5e134-70df-4a94-850f-9ccf15a45dc7.png)

2021-10-06 12:09 UTC, merged