test(e2e): add e2e test for wizard-generator
SAP/fundamental-ngx pull request #7049
Opened 2021-10-29 14:32 UTC by maxym-valor

## Related Issue(s)

closes none

## Description

Added e2e tests for wizard-generator component

## Screenshots

> **NOTE:** If you've made any style changes, please provide appropriate screenshots (before and after) to help reviewers.

### Before:

### After:

#### Please check whether the PR fulfills the following requirements

##### During Implementation

1. Visual Testing:

-   [n/a] visual misalignments/updates
-   [n/a] check Light/Dark/HCB/HCW themes
-   [n/a] RTL/LTR - proper rendering and labeling
-   [n/a] responsiveness(resize)
-   [n/a] Content Density (Cozy/Compact/(Condensed))
-   [n/a] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [n/a] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [n/a] Mouse vs. Keyboard support
-   [n/a] Text Truncation

2. API and functional correctness

-   [n/a] check for console logs (warnings, errors)
-   [n/a] API boundary values
-   [n/a] different combinations of components - free style
-   [n/a] change the API values during testing

3. Documentation and Example validations

-   [n/a] missing API documentation or it is not understandable
-   [n/a] poor examples
-   [n/a] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [x] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [n/a] Run npm run build-pack-library and test in external application
-   [n/a] update `README.md`
-   [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

##### PR Review

-   [n/a] visual misalignments/updates
-   [n/a] check Light/Dark/HCB/HCW themes
-   [n/a] RTL/LTR - proper rendering and labeling
-   [n/a] responsiveness(resize)
-   [n/a] Content Density (Cozy/Compact/(Condensed))
-   [n/a] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [n/a] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [n/a] Mouse vs. Keyboard support
-   [n/a] Text Truncation

2. API and functional correctness

-   [n/a] check for console logs (warnings, errors)
-   [n/a] API boundary values
-   [n/a] different combinations of components - free style
-   [n/a] change the API values during testing

3. Documentation and Example validations

-   [n/a] missing API documentation or it is not understandable
-   [n/a] poor examples
-   [n/a] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

2021-11-01 09:58 UTC, Seamoo13 requested changes
also need to add spec path in platform suite in both config files (wdio.conf.js and wdio-cron.conf.js)

2021-11-01 09:58 UTC, Seamoo13 commented on e2e/wdio/platform/tests/wizard-generator.e2e-spec.ts
> +            expect(getText(dialog + formLabel, 0)).toBe(productType, 'value is not equal entered value');
might be better to use a loop to not repeat yourself over and over
for(i = 0.....) {
expect(getText(dialog + formLabel, i)).toBe(assertionArr[i]);
}

2021-11-01 09:58 UTC, Seamoo13 commented on e2e/wdio/platform/tests/wizard-generator.e2e-spec.ts
> +    function checkBasicWay(selector: string): void {
better to use many simple functions than 1 large complex one. Here you are asserting each step, is step 1 fails the erst of the function won't run. I suggest doing like this:
completeStepOne(); -- where you simply perform the actions, no assertions
completeStepTwo()
..completeStep3..
..summary..

then write test cases like this:
describe(x example .....
it('should check first step'),....
completeStepOne(..);   --- again, this method is just actions
expect(....)...;   --- assertions after actions
}
it(step 2)..
completStepOne()
click(nextStepButton);
completeStepTwo()
expect...

this way we will instantly know which step has failed, functions will (hopefully) be easier to read, and only doing assertions for what we are checking and all assertions will be at the end so if they fail there won't be skipped code.

2021-11-01 09:58 UTC, Seamoo13 commented on e2e/wdio/platform/tests/wizard-generator.e2e-spec.ts
> +    function checkBasicWay(selector: string): void {
also, you may want to look into using a switch case instead of 'if' here

2021-11-01 09:58 UTC, Seamoo13 commented on e2e/wdio/platform/fixtures/testData/wizard-generator.ts
> +export const cardDetails2 = '4343 4343 4343 4343';
please have empty row at end of files

2021-11-01 09:58 UTC, Seamoo13 commented on e2e/wdio/platform/tests/wizard-generator.e2e-spec.ts
> +        it('should check required fields validation', () => {
could also break this one down into a couple test cases so we will know better if all validation or 1 validation broken

it should check step 1 validation
...
it should check step 2 validation
completeStepOne()
click(nextBtn)
..add invalid text
assert..
...

2021-11-01 09:58 UTC, Seamoo13 commented on e2e/wdio/platform/tests/wizard-generator.e2e-spec.ts
> +    function checkValidationRequiredFields(selector: string): void {
1. better to break this into separate methods 
2. need to add validation message check as well (for example on step 2 if you click on the field after error class applied, popup with text appears - need to assert message and message text
![2021-11-01](https://user-images.githubusercontent.com/47522152/139654494-4cb19287-2499-4417-b9fc-584b9218601a.png)

2021-11-04 13:53 UTC, platon-rov approved these changes

2021-11-04 14:46 UTC, Seamoo13 approved these changes

2021-11-05 08:54 UTC, platon-rov approved these changes

2021-11-05 09:16 UTC, nikvalor approved these changes

2021-11-05 19:40 UTC, InnaAtanasova approved these changes

2021-11-05 20:15 UTC, merged