fix(core): static dialog nobackdrop position fix
SAP/fundamental-ngx pull request #7072
Opened 2021-11-01 15:44 UTC by dmitry-stepanenko

## Related Issue(s)
Closes #5286

## Description
added centering for the dialog without backdrop

## Screenshots

### Before:

### After:
![image](https://user-images.githubusercontent.com/33101123/139699145-1cf80c75-05f1-469b-9a12-005d547da10c.png)

#### Please check whether the PR fulfills the following requirements

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [n/a] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [n/a] API boundary values
-   [n/a] different combinations of components - free style
-   [n/a] change the API values during testing

3. Documentation and Example validations

-   [n/a] missing API documentation or it is not understandable
-   [n/a] poor examples
-   [n/a] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [n/a] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [n/a] Run npm run build-pack-library and test in external application
-   [n/a] update `README.md`
-   [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

##### PR Review

-   [ ] visual misalignments/updates
-   [ ] check Light/Dark/HCB/HCW themes
-   [ ] RTL/LTR - proper rendering and labeling
-   [ ] responsiveness(resize)
-   [ ] Content Density (Cozy/Compact/(Condensed))
-   [ ] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [ ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [ ] Mouse vs. Keyboard support
-   [ ] Text Truncation

2. API and functional correctness

-   [ ] check for console logs (warnings, errors)
-   [ ] API boundary values
-   [ ] different combinations of components - free style
-   [ ] change the API values during testing

3. Documentation and Example validations

-   [ ] missing API documentation or it is not understandable
-   [ ] poor examples
-   [ ] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

2021-11-01 15:49 UTC, dmitry-stepanenko commented
waiting for https://github.com/SAP/fundamental-styles/pull/2877

2021-11-05 18:09 UTC, InnaAtanasova approved these changes

2021-11-09 17:26 UTC, mikerodonnell89 requested changes
Still broken for me on the preview

![Screen Shot 2021-11-09 at 10 26 15 AM](https://user-images.githubusercontent.com/2471874/140974069-f4c059bc-60fa-401d-b2a2-573f441e1ba6.png)

2021-11-16 16:48 UTC, mikerodonnell89 approved these changes
Looks like the netlify deploy preview is simply not working and it is working for the github one so I'll approve this

2021-11-19 16:59 UTC, Betrozov approved these changes

2021-11-22 17:43 UTC, merged