chore(core,platform): styles version bump
SAP/fundamental-ngx pull request #7171
Opened 2021-11-11 14:44 UTC by platon-rov

Fundamental Styles version bump to get fixes & features.

2021-11-11 14:47 UTC, genereg1 approved these changes

2021-11-12 10:17 UTC, droshev requested changes
@platon-rov when you bump like that do you check the breaking changes (e.g. checkbox)?
if there are we need to bring them

2021-11-12 10:24 UTC, platon-rov commented
> @platon-rov when you bump like that do you check the breaking changes (e.g. checkbox)? if there are we need to bring them

agree, my miss, sorry. But shouldn't we change [minor] version in case of breaking change as we do in ngx?

2021-11-17 21:34 UTC, InnaAtanasova approved these changes

2021-11-18 11:01 UTC, merged