chore(core,platform): styles version bump, pagination breaking changes handling
SAP/fundamental-ngx pull request #7233
Opened 2021-11-23 13:10 UTC by platon-rov

## Related Issue(s)

DXP

## Description

Fundamental styles version bump & pagination component breaking changes handling.

## Screenshots

### Before:

![image](https://user-images.githubusercontent.com/20265336/143029809-b77dfa52-a7e5-41ef-a4a2-46b756e96d4c.png)

### After:

![image](https://user-images.githubusercontent.com/20265336/143029843-23764f0d-73c8-4097-8c51-bae08be7923f.png)

See pagination component docs for more.

2021-11-23 20:22 UTC, mikerodonnell89 commented on libs/core/src/lib/pagination/pagination.component.ts
> +    get currentShowing(): CurrentShowing {
this should be hidden from the docs I think

2021-11-24 12:22 UTC, Betrozov approved these changes

2021-11-29 12:21 UTC, N1XUS approved these changes

2021-11-29 15:10 UTC, mikerodonnell89 approved these changes

2021-11-29 23:10 UTC, droshev requested changes
on mobile https://deploy-preview-7233--fundamental-ngx.netlify.app/#/core/pagination#mobile the field doesn't allow entering 2-digit number (e.g. 11)

2021-11-30 15:45 UTC, droshev approved these changes

2021-12-01 10:21 UTC, puru-hk commented
Looks fine

2021-12-01 10:21 UTC, puru-hk approved these changes

2021-12-02 12:56 UTC, merged