fix(core): fix split-button accessibility
SAP/fundamental-ngx pull request #7239
Opened 2021-11-24 12:22 UTC by dimamarksman

## Related Issue(s)

closes https://github.com/SAP/fundamental-ngx/issues/6210

## Description

This PR fixes core split-button accessibility

## Screenshots

### Before:

### After:

#### Please check whether the PR fulfills the following requirements

##### During Implementation

1. Visual Testing:

-   [ ] visual misalignments/updates
-   [ ] check Light/Dark/HCB/HCW themes
-   [ ] RTL/LTR - proper rendering and labeling
-   [ ] responsiveness(resize)
-   [ ] Content Density (Cozy/Compact/(Condensed))
-   [ ] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [ ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [ ] Mouse vs. Keyboard support
-   [ ] Text Truncation

2. API and functional correctness

-   [ ] check for console logs (warnings, errors)
-   [ ] API boundary values
-   [ ] different combinations of components - free style
-   [ ] change the API values during testing

3. Documentation and Example validations

-   [ ] missing API documentation or it is not understandable
-   [ ] poor examples
-   [ ] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [ ] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [ ] tests for the changes that have been done
-   [ ] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [ ] Run npm run build-pack-library and test in external application
-   [ ] update `README.md`
-   [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

##### PR Review

-   [ ] visual misalignments/updates
-   [ ] check Light/Dark/HCB/HCW themes
-   [ ] RTL/LTR - proper rendering and labeling
-   [ ] responsiveness(resize)
-   [ ] Content Density (Cozy/Compact/(Condensed))
-   [ ] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [ ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [ ] Mouse vs. Keyboard support
-   [ ] Text Truncation

2. API and functional correctness

-   [ ] check for console logs (warnings, errors)
-   [ ] API boundary values
-   [ ] different combinations of components - free style
-   [ ] change the API values during testing

3. Documentation and Example validations

-   [ ] missing API documentation or it is not understandable
-   [ ] poor examples
-   [ ] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

2021-11-24 12:29 UTC, Betrozov requested changes

2021-11-24 12:29 UTC, Betrozov commented on libs/core/src/lib/split-button/split-button.component.html
> +    aria-label="Split button"
i18n?

2021-11-25 10:04 UTC, platon-rov commented on libs/core/src/lib/button/button.component.ts
> +            'ariaLabel ? ariaLabel : specialButtonType.includes(fdType) ? label != null ? label + ", " + fdType : glyph != undefined || glyph != null ? fdType + ", " + glyph.split("-").join(" ") : ti
Could you please make it more readable?

2021-11-25 14:17 UTC, dimamarksman commented on libs/core/src/lib/button/button.component.ts
> +            'ariaLabel ? ariaLabel : specialButtonType.includes(fdType) ? label != null ? label + ", " + fdType : glyph != undefined || glyph != null ? fdType + ", " + glyph.split("-").join(" ") : ti
moved it to a getter

2021-11-26 15:38 UTC, platon-rov approved these changes

2021-11-29 09:55 UTC, Betrozov approved these changes

2021-11-30 07:22 UTC, Sanjay-1312 commented
Hello Colleagues,

Issue 1: Fixed.

Issue 2: Fixed.

Issue 3: Fixed.

Retest Details:
https://deploy-preview-7239--fundamental-ngx.netlify.app/#/core/split-button
JAWS 2021

2021-11-30 07:25 UTC, puru-hk approved these changes

2021-11-30 10:19 UTC, merged