fix(core): dynamic page a11y
SAP/fundamental-ngx pull request #7345
Opened 2021-12-10 14:45 UTC by genereg1

## Related Issue(s)

closes https://github.com/SAP/fundamental-ngx/issues/5576

## Description

## Screenshots

### Before:

### After:

#### Please check whether the PR fulfills the following requirements

##### During Implementation

1. Visual Testing:

-   [ ] visual misalignments/updates
-   [ ] check Light/Dark/HCB/HCW themes
-   [ ] RTL/LTR - proper rendering and labeling
-   [ ] responsiveness(resize)
-   [ ] Content Density (Cozy/Compact/(Condensed))
-   [ ] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [ ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [ ] Mouse vs. Keyboard support
-   [ ] Text Truncation

2. API and functional correctness

-   [ ] check for console logs (warnings, errors)
-   [ ] API boundary values
-   [ ] different combinations of components - free style
-   [ ] change the API values during testing

3. Documentation and Example validations

-   [ ] missing API documentation or it is not understandable
-   [ ] poor examples
-   [ ] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [ ] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [ ] tests for the changes that have been done
-   [ ] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [ ] Run npm run build-pack-library and test in external application
-   [ ] update `README.md`
-   [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

2021-12-16 11:51 UTC, dimamarksman commented on libs/core/src/lib/breadcrumb/breadcrumb.interface.ts
> +export interface BreadcrumbInterface {
Let's BreadcrumbComponent implement this

2021-12-16 11:51 UTC, dimamarksman commented on libs/core/src/lib/breadcrumb/breadcrumb-item.directive.ts
> +            const isNextElementLink = nextElement && nextElement.hasAttribute('href');
As for me nextElementSibling.children looks not flexible enough.

Maybe it's better to listen for this event from breadcrumb component and move focus to this item if needed?
The item itself just has to implement .focus() method.
Moreover breadcrumb can rely on [FocusKeyManger service](https://material.angular.io/cdk/a11y/overview#focuskeymanager)

2021-12-17 11:58 UTC, Betrozov requested changes

2021-12-17 11:58 UTC, Betrozov commented on libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.html
> +    <div *ngIf="_leftColumnSeparator" class="fd-flexible-column-layout__separator" aria-label="separator">
please add internationalization for `aria-label`

2021-12-17 11:58 UTC, Betrozov commented on libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.html
> +            [title]="_leftColumnSeparator === 'left' ? 'Expand' : 'Collapse'"
same for `title`

2021-12-17 11:58 UTC, Betrozov commented on libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.html
> +    <div *ngIf="_rightColumnSeparator" class="fd-flexible-column-layout__separator" aria-label="separator">
same

2021-12-17 11:58 UTC, Betrozov commented on libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.html
> +            [title]="_rightColumnSeparator === 'left' ? 'Expand' : 'Collapse'"
same

2021-12-20 11:17 UTC, dimamarksman requested changes

2021-12-20 11:17 UTC, dimamarksman commented on libs/core/src/lib/breadcrumb/breadcrumb.component.ts
> +        @Optional() private _dynamicPageService: DynamicPageService,
Breadcrumb component shouldn't know anything about DynamicPage

2021-12-21 17:01 UTC, Betrozov requested changes

2021-12-21 17:01 UTC, Betrozov commented on libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.html
> +            i18n-title="coreFlexibleColumnLayount.Left.Separator.Toogle|Left title attribute"
please use `@Input` for internationalization
please pay attention to this issue
https://github.com/SAP/fundamental-ngx/issues/6436

2021-12-21 17:01 UTC, Betrozov commented on libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.html
> +            i18n-title="coreFlexibleColumnLayount.Right.Separator.Toogle|Right title attribute"
same

2021-12-23 14:38 UTC, genereg1 commented
> Focusing order is broken when open a dynamic page https://deploy-preview-7345--fundamental-ngx.netlify.app/#/core/dynamic-page#basic
> 
>  Screen.Recording.2021-12-23.at.16.06.13.mov

@platon-rov 
It's intended behavior. For now, you can navigate through Breadcrumbs by arrow keys according to the doc where it says that tab navigation should be reduced. Therefore Tab key on Breadcrumbs in Dynamic Page just switches to another UI element. I added `[arrowNavigation]` property to Breadcrumbs it handles how you prefer to navigate through Breadcrumbs by Tab or Arrow keys

2021-12-29 12:26 UTC, Betrozov approved these changes

2021-12-29 12:52 UTC, dmitry-stepanenko approved these changes

2022-01-13 11:32 UTC, platon-rov approved these changes

2022-03-30 04:54 UTC, Veerakarthick commented
Hello Colleague,

Retest has been taken results are below:

Issue1: Fixed
Issue2: Fixed
Issue3:
Observed Behavior:
On navigating to the tabs, an additional information ‘tab’ is read at first on entering the tabstrip section. Also, the tutor message provided to change the tab is not precise. i.e. it reads to change the selection use ctrl+page down but the tabs cannot be switched using the provided shortcut key. Therefore, the information read is not precise.
The speech output is:
�Tab� ��
Tab 1 �Tab� �selected� ��
1 of 3
To switch pages, press Control+PageDown.
Tab 2 �Tab�
2 of 3
To switch pages, press Control+PageDown.

Issue4: Fixed
Issue5: Fixed
Issue6: Fixed
Issue7: Fixed
Issue8: Fixed
Issue9: Fixed
Issue10: Fixed

Retest environment:
URL:https://deploy-preview-7345--fundamental-ngx.netlify.app/#/core/dynamic-page[](https://user-images.githubusercontent.com/37998745/160749392-4812ced4-5a8c-4a69-85c4-d351606ba2e2.png)
Screen reader: Jaws 2021.2111.13 ILM
Browser: Version 99.0.4844.84 (Official Build) (64-bit)

Regards,
Karthikeyan.c

image

2022-06-15 11:08 UTC, Karthickc1994 commented
Hello Colleague,

Retest has been taken results are below:

Issue1: Fixed
Issue2: Fixed
Issue3:
Observed Behavior:
On navigating to the tabs, an additional information ‘tab’ is read at first on entering the tabstrip section. Also, the tutor message provided to change the tab is not precise. i.e. it reads to change the selection use ctrl+page down but the tabs cannot be switched using the provided shortcut key. Therefore, the information read is not precise.
The speech output is:
�Tab� ��
Tab 1 �Tab� �selected� ��
1 of 3
To switch pages, press Control+PageDown.
Tab 2 �Tab�
2 of 3
To switch pages, press Control+PageDown.

screen shot:
![image](https://user-images.githubusercontent.com/105037808/173813225-6c8a68f2-1463-4d04-966e-4fdcbf8f4fe6.png)

Issue4: Fixed
Issue5: Fixed
Issue6: Fixed
Issue7: Fixed
Issue8: Fixed
Issue9: Fixed
Issue10: Fixed

Retest environment:
URL:https://fundamental-ngx-gh--pr7345-fix-dynamic-page-a11-45ql36g8.web.app/fundamental-ngx#/core/dynamic-page
Browser: chrome Version 102.0.5005.115 (Official Build) (64-bit)
screen reader: Jaws2022.2204.20ILM

Regards,
Karthikeyan.c

2022-06-16 08:52 UTC, Karthickc1994 commented
Hello Colleague,

The reported issue in CASE 3  is belongs to combination is a known JAWS bug in Chrome issue.
Enter into a tablist JAWS narrates: To switch pages, press Control+PageDown https://github.com/FreedomScientific/VFO-standards-support/issues/337

so this PR will be closed with technology exception.
 
Regards,
Karthikeyan.c

2022-06-16 09:58 UTC, genereg1 commented
> Hello Colleague,
> 
> The reported issue in CASE 3 is belongs to combination is a known JAWS bug in Chrome issue. Enter into a tablist JAWS narrates: To switch pages, press Control+PageDown [FreedomScientific/VFO-standards-support#337](https://github.com/FreedomScientific/VFO-standards-support/issues/337)
> 
> so this PR will be closed with technology exception.
> 
> Regards, Karthikeyan.c

Hello Kartrick,
Does it mean this PR is verified and we can merge it?

2022-08-17 22:22 UTC, merged