fix(core): action-sheet, fix i11y issues
SAP/fundamental-ngx pull request #7390
Opened 2021-12-16 15:22 UTC by Betrozov

## Related Issue

closes https://github.com/sap/fundamental-ngx/issues/6211

## Description

Fixed Action Sheet i11y issues

#### Please check whether the PR fulfills the following requirements

##### During Implementation

1. Visual Testing:

-   [n/a] visual misalignments/updates
-   [n/a] check Light/Dark/HCB/HCW themes
-   [n/a] RTL/LTR - proper rendering and labeling
-   [n/a] responsiveness(resize)
-   [n/a] Content Density (Cozy/Compact/(Condensed))
-   [n/a] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [n/a] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [n/a] Mouse vs. Keyboard support
-   [n/a] Text Truncation

2. API and functional correctness

-   [n/a] check for console logs (warnings, errors)
-   [n/a] API boundary values
-   [n/a] different combinations of components - free style
-   [n/a] change the API values during testing

3. Documentation and Example validations

-   [n/a] missing API documentation or it is not understandable
-   [n/a] poor examples
-   [n/a] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [n/a] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [n/a] Run npm run build-pack-library and test in external application
-   [v] update `README.md`
-   [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

2021-12-17 15:34 UTC, InnaAtanasova commented on apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-mobile/action-sheet-mobile-example.component.html
> +            <button fd-button glyph="settings" title="Open Action Sheet Mobile" aria-haspopup="menu"></button>
Great work! I was looking at this documentation: https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html

and you need `aria-controls` for the button and an id for the menu it controls. You will need an `id` for the button as well, as you will need it for the `aria-labelledby` attr of the ul.

2021-12-23 12:34 UTC, platon-rov approved these changes

2021-12-28 17:11 UTC, dmitry-stepanenko approved these changes

2021-12-29 09:05 UTC, dimamarksman requested changes
Looks good.
I've noticed that closing a menu by Escape key leads to focus loss.

2021-12-29 09:05 UTC, dimamarksman commented on libs/core/src/lib/action-sheet/action-sheet-item/action-sheet-item.component.ts
> +        '[attr.role]': "'none'"
```suggestion
        role: 'none'
```

2021-12-29 09:05 UTC, dimamarksman commented on libs/core/src/lib/action-sheet/action-sheet-item/action-sheet-item.component.ts
> +    /** Indicate if items should be in compact or compare mode. */
```suggestion
    /** Indicate if items should be in compact mode. */
```

2021-12-29 13:21 UTC, dimamarksman approved these changes

2022-01-31 10:29 UTC, Veerakarthick commented
Hello Colleague,

Retest has been taken below are the details.

Issue1: Fixed
Issue2: Fixed
Issue3: Fixed
Issue4: Fixed
Issue5: Fixed
Issue6:Fixed.

Retest Environment:
URL: https://deploy-preview-7390--fundamental-ngx.netlify.app/assets/typedoc/core/classes/actionsheetitemcomponent
Browser: Chrome Version 96.0.4664.110 (Official Build) (64-bit)
Screen reader: Jaws2021.2111.13ILM


Regards,
Karthikeyan.c

2022-01-31 10:30 UTC, Veerakarthick commented
Hello Colleague,

Retest has been taken below are the details.

Issue1: Fixed
Issue2: Fixed
Issue3: Fixed
Issue4: Fixed
Issue5: Fixed
Issue6:Fixed.

Retest Environment:
URL: https://deploy-preview-7390--fundamental-ngx.netlify.app/assets/typedoc/core/classes/actionsheetitemcomponent
Browser: Chrome Version 96.0.4664.110 (Official Build) (64-bit)
Screen reader: Jaws2021.2111.13ILM


Regards,
Karthikeyan.c

2022-03-04 10:12 UTC, merged