test(e2e): add additional test cases
SAP/fundamental-ngx pull request #7430
Opened 2021-12-24 14:57 UTC by nikvalor

## Related Issue(s)

closes none

## Description

Added additional test cases for file uploader, table, search, button
## Screenshots

### Before:

### After:

#### Please check whether the PR fulfills the following requirements

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [x] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [n/a] Run npm run build-pack-library and test in external application
-   [n/a] update `README.md`
-   [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

2021-12-24 15:44 UTC, Seamoo13 requested changes

2021-12-24 15:44 UTC, Seamoo13 commented on e2e/wdio/core/tests/file-uploader.e2e-spec.ts
> +    fit('verify compact input smaller than basic', () => {
remove fit

2021-12-28 11:31 UTC, Seamoo13 approved these changes

2021-12-28 12:37 UTC, maxym-valor approved these changes

2021-12-29 12:38 UTC, Betrozov approved these changes

2021-12-30 11:27 UTC, merged