feat(platform): ability to add rows to table
SAP/fundamental-ngx pull request #7579
Opened 2022-01-20 12:22 UTC by N1XUS

## Related Issue(s)

closes #7422 

## Description
Added ability to add new rows to the platform table. Added default controls which can be overriten with custom templates.
## Screenshots
![image](https://user-images.githubusercontent.com/6586561/150337579-dfd3fac1-2f65-4e54-a3f4-8c9d68672336.png)

#### Please check whether the PR fulfills the following requirements

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [x] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [ ] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [ ] tests for the changes that have been done
-   [ ] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [ ] Run npm run build-pack-library and test in external application
-   [ ] update `README.md`
-   [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

2022-01-21 18:16 UTC, InnaAtanasova approved these changes

2022-01-21 18:16 UTC, InnaAtanasova commented on libs/platform/src/lib/table/components/table-column/table-column.component.ts
> +    @ContentChild(FdpEditableCellDef)
typedocs

2022-01-24 09:48 UTC, platon-rov approved these changes

2022-01-25 21:03 UTC, mikerodonnell89 requested changes
1. If I click "Create" then immediately "Cancel", the save/cancel buttons are still visible, I think they should be hidden 
2. If I create a new row and save it, then create another new row and save it, that first one I created disappears from the table

2022-01-26 09:27 UTC, N1XUS commented
> 1. If I click "Create" then immediately "Cancel", the save/cancel buttons are still visible, I think they should be hidden
> 2. If I create a new row and save it, then create another new row and save it, that first one I created disappears from the table
> 3. Any way to make cells required / disabling "Save" button if required fields missing?

Hey Mike. Your comments has been addressed

2022-01-26 20:31 UTC, mikerodonnell89 requested changes
One more thing I just noticed in this example is searching for something that turns up 0 rows, then resetting the search, the table remains empty

2022-01-27 08:40 UTC, N1XUS commented
@mikerodonnell89 data source has been updated. Please re-check

2022-01-28 11:52 UTC, droshev approved these changes

2022-01-28 13:54 UTC, merged