chore: rename experimental modules
SAP/fundamental-ngx pull request #7585
Opened 2022-01-21 07:23 UTC by N1XUS

## Related Issue(s)

closes #7582 

## Description
Removed `Experimental` prefix from fn modules and components.

##### PR Quality

-   [ ] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [ ] tests for the changes that have been done
-   [ ] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [ ] Run npm run build-pack-library and test in external application
-   [ ] update `README.md`
-   [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

2022-01-21 12:20 UTC, dmitry-stepanenko requested changes
@N1XUS please update component generation schematics. Also it's needed to update header components in all existing fn docs
![image](https://user-images.githubusercontent.com/33101123/150526059-7d17b215-1d1f-4ddd-9589-eaf93518d17a.png)

2022-01-21 18:01 UTC, InnaAtanasova approved these changes

2022-01-22 02:26 UTC, droshev approved these changes

2022-01-24 09:14 UTC, platon-rov approved these changes

2022-01-24 09:18 UTC, dmitry-stepanenko approved these changes

2022-01-25 17:00 UTC, mikerodonnell89 approved these changes

2022-01-25 19:53 UTC, merged