feat(core,platform): date & datetime picker - ability to process input value on blur
SAP/fundamental-ngx pull request #7599
Opened 2022-01-24 16:47 UTC by dmitry-stepanenko

## Related Issue(s)

closes #7525 

## Description
Currently 

## Screenshots

### Before:

### After:

#### Please check whether the PR fulfills the following requirements

##### During Implementation

1. Visual Testing:

-   [ ] visual misalignments/updates
-   [ ] check Light/Dark/HCB/HCW themes
-   [ ] RTL/LTR - proper rendering and labeling
-   [ ] responsiveness(resize)
-   [ ] Content Density (Cozy/Compact/(Condensed))
-   [ ] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [ ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [ ] Mouse vs. Keyboard support
-   [ ] Text Truncation

2. API and functional correctness

-   [ ] check for console logs (warnings, errors)
-   [ ] API boundary values
-   [ ] different combinations of components - free style
-   [ ] change the API values during testing

3. Documentation and Example validations

-   [ ] missing API documentation or it is not understandable
-   [ ] poor examples
-   [ ] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [ ] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [ ] tests for the changes that have been done
-   [ ] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [ ] Run npm run build-pack-library and test in external application
-   [ ] update `README.md`
-   [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

2022-01-25 15:13 UTC, mikerodonnell89 requested changes
Need to remove this text from `date-picker-docs.component.html`: ```The value for the input only changes the model on blur or an enter/return keystroke.```

2022-01-25 15:23 UTC, mikerodonnell89 commented on apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-update-on-blur-example.component.ts
> +        <div>Selected Date: {{ date?.toDateString() || 'null' }}</div> `,
Should show the full date + time here

2022-01-25 15:24 UTC, mikerodonnell89 requested changes
Left a couple comments

2022-01-26 09:32 UTC, dmitry-stepanenko commented
@mikerodonnell89 done

2022-01-27 12:51 UTC, platon-rov approved these changes

2022-01-27 12:51 UTC, platon-rov commented on libs/core/src/lib/date-picker/date-picker.component.ts
> +    processInputOnBlur = false;
Let's use `coerceBoolenProperty` from sdk here.

2022-01-27 12:51 UTC, platon-rov commented on libs/core/src/lib/datetime-picker/datetime-picker.component.ts
> +    processInputOnBlur = false;
coercion.

2022-01-28 13:19 UTC, dmitry-stepanenko commented
@platon-rov done

2022-02-01 18:17 UTC, mikerodonnell89 approved these changes

2022-02-03 03:06 UTC, merged