feat(core): shift selection
SAP/fundamental-ngx pull request #7652
Opened 2022-01-31 09:40 UTC by dmitry-stepanenko

## Related Issue(s)

closes https://github.com/SAP/fundamental-ngx/issues/7622
closes https://github.com/SAP/fundamental-ngx/issues/7650

## Description
- An ability to select ranges is not implemented in multi-select. 
- An ability to select ranges is not reflected in core-table examples. Also "indeterminate" state is not applied, when some rows are selected.

Part of #7618

## Screenshots

### Before:

### After:

#### Please check whether the PR fulfills the following requirements

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [n/a] different combinations of components - free style
-   [n/a] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [n/a] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [x] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [n/a] Run npm run build-pack-library and test in external application
-   [n/a] update `README.md`
-   [n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

2022-01-31 21:34 UTC, InnaAtanasova commented on apps/docs/src/app/core/component-docs/table/examples/table-checkboxes-example.component.html
> +                    (ngModelChange)="selectMaster($event, 'cozy')"
Please change `master` to `main`. Thank you

2022-01-31 21:36 UTC, InnaAtanasova commented on libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
> +    @Input()
Please add typedocs

2022-01-31 21:37 UTC, InnaAtanasova reviewed
Just 2 minor comments, but o.w. great job

2022-02-01 16:42 UTC, N1XUS approved these changes

2022-02-01 17:40 UTC, mikerodonnell89 requested changes
Nice work with the shift feature, but this PR has broken a piece of platform's multi-combobox, I cannot click the check mark for the items in the dropdown to select them

2022-02-02 07:53 UTC, dmitry-stepanenko commented
@mikerodonnell89 thank you, fixed

2022-02-03 10:49 UTC, platon-rov approved these changes

2022-02-04 18:29 UTC, InnaAtanasova approved these changes

2022-02-08 14:04 UTC, aberikashvili approved these changes
LGTM

2022-02-08 17:40 UTC, mikerodonnell89 requested changes
@dmitry-stepanenko I apologize for being so nit-picky but the functionality has changed for platform multi-combobox, previously when clicking the checkbox, the popover would stay open, it would only close if you clicked the label.  Now clicking the checkbox also closes the popover

2022-02-14 11:03 UTC, merged