Feat/fn list
SAP/fundamental-ngx pull request #7767
Opened 2022-02-16 22:04 UTC by g-cheishvili

## Related Issue(s)

Part of #7670 

## Description

Implemented Fiori next list component. Intentionally did not wrote unit tests and also there is mixin extension in ListItemComponent class, that will need to be replaced with recommended approach, once we recommend how to deal with such scenario.

## Screenshots
### Before:

### After:
![image](https://user-images.githubusercontent.com/28543391/154365158-313cc81c-13ac-4475-b95a-1865e9fbeb3c.png)

#### Please check whether the PR fulfills the following requirements

##### During Implementation

1. Visual Testing:

-   [ ] visual misalignments/updates
-   [ ] check Light/Dark/HCB/HCW themes
-   [ ] RTL/LTR - proper rendering and labeling
-   [ ] responsiveness(resize)
-   [ ] Content Density (Cozy/Compact/(Condensed))
-   [ ] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [ ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [ ] Mouse vs. Keyboard support
-   [ ] Text Truncation

2. API and functional correctness

-   [ ] check for console logs (warnings, errors)
-   [ ] API boundary values
-   [ ] different combinations of components - free style
-   [ ] change the API values during testing

3. Documentation and Example validations

-   [ ] missing API documentation or it is not understandable
-   [ ] poor examples
-   [ ] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [ ] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [ ] tests for the changes that have been done
-   [ ] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [ ] Run npm run build-pack-library and test in external application
-   [ ] update `README.md`
-   [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

2022-02-18 17:31 UTC, mikerodonnell89 requested changes
The readonly list items aren't working, should render as a grey list item with no hover interactions https://fundamental-styles.netlify.app/?path=/docs/btp-fn-components-list--byline&globals=fioriVersion:fioriNext#list

2022-02-18 17:33 UTC, mikerodonnell89 commented
I really like the fnDisabled directive. In a separate PR, we should add a "Utilities" section to the side nav, documentation on how to use the disabled/readonly directives, which demonstrates buttons to turn on and off the disabling like this

```
<ul fn-list>
    <li fn-list-item [fnDisabled]="isInfoBarDisabled" infoBar>
        <span *fnListItemTitle> Disabled info bar </span>
    </li>
</ul>

<button fd-button (click)="isInfoBarDisabled = !isInfoBarDisabled">Toggle info bar disabled</button>
```

and some examples on other components such as button etc.

2022-02-18 17:35 UTC, InnaAtanasova commented on libs/fn/src/lib/cdk/mixins/CombineBehaviors.ts
> +// import { Constructor } from '../interfaces/Constructor';
if this file is not used maybe remove it?

2022-02-18 17:40 UTC, InnaAtanasova commented
<img width="1222" alt="Screen Shot 2022-02-18 at 12 39 33 PM" src="https://user-images.githubusercontent.com/39598672/154734254-520b4cfe-5ffc-4fd9-b8b9-ff3ac7cea204.png">

disabled item is focussable

2022-02-18 17:43 UTC, g-cheishvili commented
> 

That happens on netlify deploy, it not up to date. look [here](https://fundamental-ngx-gh--pr7767-feat-fn-list-kbhl2j6r.web.app/fundamental-ngx#/fn/list)

2022-02-18 18:41 UTC, mikerodonnell89 commented
> > The readonly list items aren't working, should render as a grey list item with no hover interactions https://fundamental-styles.netlify.app/?path=/docs/btp-fn-components-list--byline&globals=fioriVersion:fioriNext#list
> 
> seems like only infoBar has readonly support. is that how it should be or styles is missing something?

You are correct, my bad, but let's make this line an infobar as well so that the fnReadonly directive actually does something

2022-02-21 12:45 UTC, g-cheishvili commented
Go away stale bot

2022-02-21 17:36 UTC, mikerodonnell89 approved these changes

2022-02-21 18:11 UTC, merged