fix(core): file uploader disabled visual state
SAP/fundamental-ngx pull request #7814
Opened 2022-02-28 11:20 UTC by platon-rov

## Related Issue(s)

Closes #7664.

## Description

Visual representation of the disabled state for the file uploader component.

## Screenshots

### Before:

<img width="296" alt="image" src="https://user-images.githubusercontent.com/20265336/155974494-f0c63c8e-e6c8-4897-9b20-fae09d23a82c.png">

### After:

<img width="269" alt="image" src="https://user-images.githubusercontent.com/20265336/155974724-3f454fb1-96ff-49e6-ba90-fe1b1f719f31.png">

2022-02-28 11:56 UTC, dmitry-stepanenko approved these changes

2022-02-28 13:42 UTC, genereg1 approved these changes

2022-03-01 19:07 UTC, InnaAtanasova requested changes
Please add an example in the docs. This will help us detect problems in the future with this state.

2022-03-01 20:02 UTC, g-cheishvili approved these changes

2022-03-04 19:16 UTC, InnaAtanasova approved these changes

2022-03-07 20:52 UTC, merged