fix(platform): value help dialog search
SAP/fundamental-ngx pull request #8022
Opened 2022-04-25 14:27 UTC by platon-rov

## Related Issue(s)

Closes #7908.

## Description

Previously search button was used only to focus search field input, now by clicking on it search is performed by the value in the search field input without any other filter values. Button "Go" still performs search by all of the filters, including search, nothing changed here.

2022-04-25 17:19 UTC, mikerodonnell89 reviewed
The linked issue in the description seems only semi-related. Also should the input clear after a search is performed? I don't think that is typical UX behavior

2022-04-25 21:14 UTC, InnaAtanasova commented on libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.ts
> +                    console.log(data);
Maybe not needed? :)

2022-04-26 10:36 UTC, g-cheishvili requested changes
Clicking enter, when you are focused on search input, refreshes grid, but for some reason it does not search for anything and after refresh input is cleaned

2022-05-02 12:01 UTC, dmitry-stepanenko approved these changes

2022-05-03 12:46 UTC, g-cheishvili approved these changes

2022-05-03 12:47 UTC, g-cheishvili commented
@platon-rov please check failing unit tests

2022-05-03 19:21 UTC, mikerodonnell89 approved these changes

2022-05-04 11:44 UTC, merged