feat(core): grid list horizon, styles breaking changes adoption
SAP/fundamental-ngx pull request #8039
Opened 2022-04-29 10:57 UTC by platon-rov

## Related Issue(s)

Closes none.

## Description

Grid List Horizon support, breaking changes adoption.

## Screenshots

### Before:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/20265336/165931153-3d9ffe82-85cc-4921-9c0e-632c55e0c70d.png">

### After:

<img width="324" alt="image" src="https://user-images.githubusercontent.com/20265336/165931075-18a8788a-e8c9-4bd2-81ad-ec84dcf33a3f.png">

## BREAKING CHANGE

* Grid List Item body markup changed, see wiki
* The whole item with link is clickable now, it might cause issues in a single selection mode but selection event emitted first.

2022-04-29 17:25 UTC, InnaAtanasova approved these changes

2022-04-29 17:29 UTC, InnaAtanasova requested changes
Sorry, approved by accident :) 
<img width="819" alt="Screen Shot 2022-04-29 at 1 27 14 PM" src="https://user-images.githubusercontent.com/39598672/165993912-9e4d70e6-8589-4060-931b-9b7504115b97.png">

You can't have this in Fundamental-ngx. You need to convert these to directives.

Why is `[innerText]` used in these cases? Can't we avoid it? I believe there are security problems using this approach???

2022-05-16 18:45 UTC, g-cheishvili commented
Git Log is messed up. probably you force-pushed into target branch and now it shows enormous amount of changes. Needs your intervention @platon-rov

2022-05-18 12:30 UTC, platon-rov commented
`[BLOCKED]` by https://github.com/SAP/fundamental-styles/pull/3430

2022-05-27 18:01 UTC, InnaAtanasova approved these changes

2022-05-28 15:42 UTC, merged