fix(core): fixed list item focus
SAP/fundamental-ngx pull request #8271
Opened 2022-06-23 17:55 UTC by Lukakatche

## Related Issue(s)

fixes list items focusing twice if there is a checkbox or a radio button in it

## Description

added a check to give checkboxes and radio buttons tabindex of -1 if nothing is passed via input.

#### Please check whether the PR fulfills the following requirements

##### During Implementation

1. Visual Testing:

-   [n/a] visual misalignments/updates
-   [n/a] check Light/Dark/HCB/HCW themes
-   [n/a] RTL/LTR - proper rendering and labeling
-   [n/a] responsiveness(resize)
-   [n/a] Content Density (Cozy/Compact/(Condensed))
-   [n/a] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [n/a] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [n/a] Mouse vs. Keyboard support
-   [n/a] Text Truncation

2. API and functional correctness

-   [n/a] check for console logs (warnings, errors)
-   [n/a] API boundary values
-   [n/a] different combinations of components - free style
-   [n/a] change the API values during testing

3. Documentation and Example validations

-   [n/a] missing API documentation or it is not understandable
-   [n/a] poor examples
-   [n/a] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [ ] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [ ] tests for the changes that have been done
-   [ ] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [ ] Run npm run build-pack-library and test in external application
-   [ ] update `README.md`
-   [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

2022-06-24 08:06 UTC, dmitry-stepanenko requested changes
this doesn't really work for either checkbox or radio

https://user-images.githubusercontent.com/33101123/175492115-dc87de35-ad35-40d9-bdc2-61215074375f.mp4

2022-06-24 10:25 UTC, Karthickc1994 commented
Hello Colleague,

Retest has been taken with the below environment and results are below.

The reported issue is fixed.

Retest Environment: 
URL: https://deploy-preview-8271--fundamental-ngx.netlify.app/
Browser; chrome Version 103.0.5060.53 (Official Build) (64-bit)
Screen Reader: JAWs 2022.2204.20 ILM

Regards,
Karthikeyan.c

2022-06-24 10:44 UTC, dmitry-stepanenko approved these changes

2022-06-28 10:04 UTC, g-cheishvili requested changes

2022-06-28 10:04 UTC, g-cheishvili commented on libs/core/src/lib/list/list-item/list-item.component.ts
> +        }
It would be more reliable if we made setter for radio and checkbox and in the setter modified tabIndex and tabIndexValue

2022-08-02 19:45 UTC, mikerodonnell89 commented
Closing in favor of https://github.com/SAP/fundamental-ngx/pull/8497

2022-08-02 19:45 UTC, closed without merging