fix(core): fixed card layout issues, growing card feature
SAP/fundamental-ngx pull request #8323
Opened 2022-07-05 16:30 UTC by platon-rov

## Related Issue(s)

Relates to DXP.

## Description

Fixed Card Layout component 
* edge use cases fixes, 
* code optimisations, 
* growing cards processing feature.

## Screenshots

### Before:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/20265336/177374234-1899cb6a-c287-4764-bf09-51da6e13a4e9.png">

### After:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/20265336/177372827-2fa87c0e-0352-4257-9935-423ddf66acac.png">

2022-07-05 17:47 UTC, mikerodonnell89 requested changes
The "show/hide" buttons in the example are no longer working - guessing a result of changes to lifecycle methods

2022-07-05 17:47 UTC, mikerodonnell89 commented on apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.html
> +    <fd-fixed-card-layout (cardDraggedDropped)="cardDraggedDropped($event)" [disableDragDrop]="true">
Does it still need `(cardDraggedDropped)="cardDraggedDropped($event)"` if `[disableDragDrop]="true"`?

2022-07-11 13:50 UTC, g-cheishvili commented
> 

It does same for me too

2022-07-11 14:01 UTC, g-cheishvili reviewed
When I managed to resize it, it worked as expected. So I approve it, because goal is reached

2022-07-11 14:01 UTC, g-cheishvili commented on libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts
> +const REM_IN_PX = 16;
I we want to be more precise about it, we should get document's font-size computed value

2022-07-11 14:02 UTC, g-cheishvili commented
Please fix merge conflicts

2022-07-11 14:20 UTC, InnaAtanasova approved these changes

2022-07-11 16:15 UTC, g-cheishvili approved these changes

2022-07-12 14:53 UTC, mikerodonnell89 approved these changes

2022-07-13 08:52 UTC, merged