feat(core, platform): datepicker today button
SAP/fundamental-ngx pull request #8394
Opened 2022-07-19 18:41 UTC by shrvr

## Related Issue(s)

closes #8362 

## Description

Added Today Selection Button in the footer selects today's date in the system or user-preferred timezone and closes the DatePicker popover.

`Important:`
For date range it sets start and end both to today's date.

2022-07-19 19:56 UTC, mikerodonnell89 requested changes
Looks pretty good so far! Left a couple comments

2022-07-19 19:56 UTC, mikerodonnell89 commented on libs/core/src/lib/date-picker/date-picker.component.html
> +        <div fd-bar barDesign="footer">
I think it should be conditional, so we will need an `*ngIf` here, and a boolean input in `date-picker.component.ts`, something like `showTodayButton`? Probably default to false as well.  So in addition, another example showing the new input in action

2022-07-19 19:56 UTC, mikerodonnell89 commented on libs/core/src/lib/date-picker/date-picker.component.ts
> +        const todayDateRange: DateRange<D> = { start: todayDate, end: todayDate };
It is not necessary to create both these variables here, since we'll only end up using one of them

2022-07-20 14:22 UTC, mikerodonnell89 requested changes
We should have a unit test for the new function

2022-07-20 14:22 UTC, mikerodonnell89 commented on libs/core/src/lib/date-picker/date-picker.component.html
> +                    <button fd-button label="Today" (click)="onTodayButtonClick()"></button>
We should (for now) provide an input for the label value that defaults to "Today" so the developer can pass their own strings in different languages etc

2022-07-21 09:36 UTC, platon-rov commented on libs/core/src/lib/date-picker/date-picker.component.ts
> +    @Input()
typedoc

2022-07-21 09:36 UTC, platon-rov commented on libs/core/src/lib/date-picker/date-picker.component.ts
> +    onTodayButtonClick(): void {
typedoc

2022-07-25 13:04 UTC, g-cheishvili approved these changes
looks good to me

2022-07-25 14:03 UTC, mikerodonnell89 approved these changes

2022-07-28 13:21 UTC, platon-rov approved these changes

2022-07-30 02:05 UTC, merged