feat(core): tabs migration
SAP/fundamental-ngx pull request #8501
Opened 2022-08-03 12:26 UTC by N1XUS

## Related Issue(s)

closes #8367 

## Description
Migrated Core Tabs component to use Overflow Layout

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [x] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [x] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [x] Run npm run build-pack-library and test in external application
-   [x] update `README.md`
-   [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

2022-08-04 13:15 UTC, platon-rov reviewed
nice!

2022-08-04 13:15 UTC, platon-rov commented on libs/core/src/lib/overflow-layout/directives/overflow-layout-popover-content.directive.ts
> +                .withHorizontalOrientation('ltr');
no rtf support?

2022-08-04 13:15 UTC, platon-rov commented on libs/core/src/lib/tabs/tab-list.component.html
> +                        <!--                        <ng-container *ngTemplateOutlet="tab.templateRef"></ng-container>-->
probably forgot to remove.

2022-08-04 13:15 UTC, platon-rov commented on libs/core/src/lib/tabs/tab-list.component.ts
> +    @Output()
typedocs.

2022-08-04 13:44 UTC, platon-rov reviewed
seems like these issues were present before so I'm not sure, we can fix it in separate pr probably

<img width="287" alt="Screenshot 2022-08-04 at 15 39 42" src="https://user-images.githubusercontent.com/20265336/182861928-e52a3246-6d72-4380-9072-482f8e0d27d4.png">

<img width="416" alt="Screenshot 2022-08-04 at 15 40 20" src="https://user-images.githubusercontent.com/20265336/182861940-1126ebc1-e920-49ab-936c-2a890cd14e4a.png">

2022-08-04 13:56 UTC, N1XUS commented
> seems like these issues were present before so I'm not sure, we can fix it in separate pr probably
> 
> <img alt="Screenshot 2022-08-04 at 15 39 42" width="287" src="https://user-images.githubusercontent.com/20265336/182861928-e52a3246-6d72-4380-9072-482f8e0d27d4.png">
> 
> <img alt="Screenshot 2022-08-04 at 15 40 20" width="416" src="https://user-images.githubusercontent.com/20265336/182861940-1126ebc1-e920-49ab-936c-2a890cd14e4a.png">

first one could be a separate issue
Second one: it's a tab-nav which does not include overflow functionality since it behaves as a directive.

2022-08-05 09:58 UTC, platon-rov approved these changes

2022-08-08 13:47 UTC, g-cheishvili requested changes

2022-08-09 15:03 UTC, g-cheishvili approved these changes

2022-08-09 19:32 UTC, mikerodonnell89 submitted a review, later dismissed
Keyboard arrow support has changed, previously it was on keydown and holding the arrow would quickly focus through the all of the tabs. Now it is on keyup and doesn't move through them. Is this intentional? Just feels a little sluggish now. Maybe a question not for us but for the designers

2022-08-11 13:11 UTC, merged