feat(core): table keyboard navigation
SAP/fundamental-ngx pull request #8635
Opened 2022-09-02 10:09 UTC by N1XUS

## Related Issue(s)

relates #8469 

## Description
Changed core table keyboard navigation. Extended documentation with explanation of the keys that are used for the navigation inside table's elements.

#### Please check whether the PR fulfills the following requirements

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [x] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [ ] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [ ] tests for the changes that have been done
-   [ ] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [ ] Run npm run build-pack-library and test in external application
-   [ ] update `README.md`
-   [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

2022-09-02 10:32 UTC, platon-rov approved these changes

2022-09-02 10:32 UTC, platon-rov commented on libs/core/src/lib/table/directives/table-body.directive.ts
> +        console.log('Table body focus');
not needed.

2022-09-02 10:32 UTC, platon-rov commented on apps/docs/src/app/core/component-docs/table/table-docs.component.html
> +        focusable element outside the table.
Please mention that if both cells & rows are focusable then only the rows will get focus.

2022-09-02 15:56 UTC, mikerodonnell89 reviewed
This probably isn't the focus outline style we want, but I think we are going against Fiori specs with this clickable header so I'm not really sure what to do here

![Screen Shot 2022-09-02 at 9 54 34 AM](https://user-images.githubusercontent.com/2471874/188192515-c099d906-3922-415c-b6c2-f427655aec5c.png)

2022-09-02 15:57 UTC, mikerodonnell89 commented
I think in the interactive rows and cells example, the clickable cells should be navigable via keyboard

2022-09-02 16:01 UTC, mikerodonnell89 reviewed
Should these get tab focus?

![Screen Shot 2022-09-02 at 10 01 03 AM](https://user-images.githubusercontent.com/2471874/188193615-b897613e-6dca-4f93-bec5-88359f5d06b4.png)

2022-09-02 16:01 UTC, mikerodonnell89 requested changes
Nice work! Just a couple comments above that are more like questions than change requests

2022-09-05 05:43 UTC, N1XUS commented
> This probably isn't the focus outline style we want, but I think we are going against Fiori specs with this clickable header so I'm not really sure what to do here
> 
> ![Screen Shot 2022-09-02 at 9 54 34 AM](https://user-images.githubusercontent.com/2471874/188192515-c099d906-3922-415c-b6c2-f427655aec5c.png)

This is actually non-navigatable table. Tab works there because there's tabbable elements such as links and some element with tabindex. I'll update the example to make it navigatable.

As to the wrong focus outline: we can introduce new class regarding sortable table header element, but I think it's outside the scope of this task.

2022-09-05 05:47 UTC, N1XUS commented
> Should these get tab focus? Only focusable via keyboard at the moment
> 
> ![Screen Shot 2022-09-02 at 10 01 03 AM](https://user-images.githubusercontent.com/2471874/188193615-b897613e-6dca-4f93-bec5-88359f5d06b4.png)

By default, any focusable element inside a table with focusable cells will not receive a focus on tab key. This is done in order for users not to tap on Tab key for 200 times if there's a large table. Instead, the process of table navigation is done in such logic:
When user focuses on the cell, we search for the first focusable element inside, and try to set focus to it. If not, set focus on the whole row. After that, if the cell contains more than one focusable element, users can use Tab key to navigate through those elements inside that cell. Navigation between cells happens with arrow keys. Pressing tab while focusing cell, or inner focusable element there, where there's no more focusable items will shift the focus from the entire table to the next focusable element. Pretty much how W3C recommends keyboard navigation for the tables.

2022-09-05 11:34 UTC, g-cheishvili approved these changes
Nice, I like it!

2022-09-06 18:39 UTC, mikerodonnell89 approved these changes
Thanks for your answers @N1XUS

2022-09-07 08:39 UTC, merged