fix(platform): update items on new event
SAP/fundamental-ngx pull request #8650
Opened 2022-09-06 06:10 UTC by N1XUS

## Related Issue(s)

closes #8629 

## Description
- Updated logic of setting rendered items to reflect new items coming from dataSource;
- Refactored component names and few input properties;
- Added missing imports/exports to the list module

#### Please check whether the PR fulfills the following requirements

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [x] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [ ] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [ ] tests for the changes that have been done
-   [ ] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [ ] Run npm run build-pack-library and test in external application
-   [ ] update `README.md`
-   [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

2022-09-07 21:12 UTC, mikerodonnell89 requested changes
A couple comments, see above

2022-09-07 21:12 UTC, mikerodonnell89 commented on libs/platform/src/lib/list/list.component.ts
> -    grpheaderTitle?: string;
Considering this is a breaking change, maybe leave the old input and have it work as a getter for the new value?

2022-09-07 21:12 UTC, mikerodonnell89 commented on libs/platform/src/lib/list/list.component.ts
> +export class ListGroupHeaderComponent extends BaseListItem implements OnInit {
Renaming these components I think is also a breaking change, for example if someone is querying for contentchildren, I do agree that it should be named this new way but I think we will need to document it in the breaking changes

2022-09-14 17:14 UTC, InnaAtanasova approved these changes

2022-09-14 20:56 UTC, mikerodonnell89 approved these changes

2022-09-15 09:09 UTC, merged