fix(core,platform): remove platform highlighting and account for lt and gt in highlight pipe
SAP/fundamental-ngx pull request #8658
Opened 2022-09-08 21:33 UTC by mikerodonnell89

fixes #8631 and #8651 

Removes platform's redundant highlighting pipes, and the core highlighting pipe now accounts for `<` and `>` which were not being rendered (see linked issue/pr above for more details)

2022-09-08 22:12 UTC, g-cheishvili commented on libs/core/src/lib/utils/pipes/search-highlight.pipe.ts
> +        value = value.replace(/</g, '&lt;');
Since we use lodash anyways, why not [utilize it escape](https://lodash.com/docs/#escape)?

2022-09-09 06:20 UTC, skaquib123 commented
@mikerodonnell89 I don't think we can use innerHTML as it will convert any unicode to HTML tag.
 dataSource = [
        { name: 'Apple<hello>', type: 'Fruits' },
        { name: 'Banana&gt', type: 'Fruits' },
        { name: 'Pineapple', type: 'Fruits' }
        ];
for datasource even if we use replace functionality it will print as shown in picture below.
<img width="918" alt="image" src="https://user-images.githubusercontent.com/110972289/189284317-a2776609-ecdf-437c-9d2c-7e3fe64bd114.png">

2022-09-09 13:55 UTC, mikerodonnell89 commented
> @mikerodonnell89 I don't think we can use innerHTML as it will convert any unicode to HTML tag. dataSource = [ { name: `Apple<hello>`, type: 'Fruits' }, { name: 'Banana&gt', type: 'Fruits' }, { name: 'Pineapple', type: 'Fruits' } ]; for datasource even if we use replace functionality it will print as shown in picture below. <img alt="image" width="918" src="https://user-images.githubusercontent.com/110972289/189284317-a2776609-ecdf-437c-9d2c-7e3fe64bd114.png">

In this case we need to refactor the pipe such that it does not require the components to use innerHTML. I think we could programmatically assign font-weight style

2022-09-12 17:07 UTC, g-cheishvili requested changes

2022-09-12 17:07 UTC, g-cheishvili commented on libs/core/src/lib/utils/pipes/search-highlight.pipe.ts
> +import _ from 'lodash-es';
```suggestion
import escape from 'lodash-es/escape'
```

2022-09-12 17:07 UTC, g-cheishvili commented on libs/core/src/lib/utils/pipes/search-highlight.pipe.ts
> +        value = _.escape(value);
```suggestion
        value = escape(value);
```

2022-09-12 17:07 UTC, g-cheishvili commented on libs/core/src/lib/utils/pipes/search-highlight.pipe.ts
> +            const testStr: string = _.escape(args.trim().toLowerCase());
```suggestion
            const testStr: string = escape(args.trim().toLowerCase());
```

2022-09-15 12:56 UTC, platon-rov approved these changes

2022-09-16 19:08 UTC, InnaAtanasova approved these changes

2022-09-19 09:33 UTC, g-cheishvili approved these changes

2022-09-28 10:33 UTC, merged