fix(core): multi input focusing
SAP/fundamental-ngx pull request #8686
Opened 2022-09-14 11:55 UTC by platon-rov

## Related Issue(s)

Closes https://github.com/SAP/fundamental-ngx/issues/8398

## Description

Core multi-input focusing issue.

## Screenshots

### Before:

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/20265336/190146927-fc29744e-21fd-448b-9444-d7af69c64319.png">

### After:

<img width="922" alt="image" src="https://user-images.githubusercontent.com/20265336/190146999-8d900b5f-948b-4283-824b-0c2211ae05a0.png">

2022-09-14 12:55 UTC, N1XUS approved these changes

2022-09-14 18:52 UTC, mikerodonnell89 requested changes

2022-09-14 18:52 UTC, mikerodonnell89 commented on libs/core/src/lib/input-group/input-group.component.html
> +                (keydown.enter)="$event.preventDefault()"
This prevents the popover list from opening on enter press, I don't think we want that do we?

2022-09-19 09:25 UTC, g-cheishvili approved these changes

2022-09-20 16:54 UTC, mikerodonnell89 approved these changes

2022-09-21 13:43 UTC, merged