fix(core): remove list focus trap
SAP/fundamental-ngx pull request #8690
Opened 2022-09-14 19:43 UTC by shrvr

## Related Issue(s)

closes #8687 

## Description

Removed list focus trap on tab key.

2022-09-14 22:42 UTC, mikerodonnell89 approved these changes
This works well and addresses the issue with FocusKeyManager losing sight of its active item when tab/shift+tab is used

2022-09-15 12:39 UTC, platon-rov requested changes
Before the action list fix pr (https://github.com/SAP/fundamental-ngx/pull/8458) we had only the first item in list focusable with tab and nov every item has tab stop.

2022-09-15 13:34 UTC, shrvr commented
> Before the action list fix pr (#8458) we had only the first item in list focusable with tab and nov every item has tab stop.

So to Navigate within the list,  should only arrow keys be used? Because for action sheet the navigation is by both Tab and arrow keys, and both share Keyboard Service.
Or I can add one more argument to `setKeyboardService ` to enable or disable tab key listening.

2022-09-15 18:43 UTC, mikerodonnell89 requested changes
I think refactoring the onKeyDown function of `keyboard-support.service.ts` to this should do it: 

```
    /** @hidden */
    onKeyDown(event: KeyboardEvent): void {
        this._keyManager.onKeydown(event);
        if (KeyUtil.isKeyCode(event, TAB) && this._focusTrapOnTab) {
            event.preventDefault();
            hasModifierKey(event, 'shiftKey') ? this.keyManager.setPreviousItemActive() : this.keyManager.setNextItemActive();
        }
    }
```

2022-09-15 18:46 UTC, mikerodonnell89 requested changes

2022-09-15 18:46 UTC, mikerodonnell89 commented on libs/core/src/lib/utils/services/keyboard-support/keyboard-support.service.ts
>      onKeyDown(event: KeyboardEvent): void {
I think try refactoring this function to 

```suggestion
    /** @hidden */
    onKeyDown(event: KeyboardEvent): void {
        this._keyManager.onKeydown(event);
        if (KeyUtil.isKeyCode(event, TAB) && this._focusTrapOnTab) {
            event.preventDefault();
            hasModifierKey(event, 'shiftKey') ? this.keyManager.setPreviousItemActive() : this.keyManager.setNextItemActive();
        }
    }
```

2022-09-15 21:11 UTC, mikerodonnell89 approved these changes

2022-09-16 12:11 UTC, platon-rov approved these changes

2022-09-16 14:27 UTC, merged