fix(core): improve onTouched handling in core components and add docs
SAP/fundamental-ngx pull request #8730
Opened 2022-09-22 17:45 UTC by mikerodonnell89

fixes #8677

A user of the library recently pointed out that the step input sets onTouched to true too early, and after combing through the library, I found this was the case with many components. According to the Angular documentation, onTouched for a control should be set to true after the control is blurred, not when it is first focused. For us with complex controls that means using focusout as blur only works on the parent element, while focusout works for child elements and bubbles.

2022-09-22 20:58 UTC, platon-rov approved these changes

2022-09-23 14:20 UTC, InnaAtanasova approved these changes

2022-09-26 10:13 UTC, g-cheishvili requested changes

2022-09-26 10:13 UTC, g-cheishvili commented on libs/core/src/lib/date-picker/date-picker.component.html
> +                (blur)="onTouched(); handleInputChange($any($event.target).value, false)"
create function `onBlur` and do `onTouched(); handleInputChange($any($event.target).value, false)`. Doing this on HTML side is not beautiful :D

2022-09-27 22:10 UTC, merged