fix(core): Add keyboard support for mobile mode in menu
SAP/fundamental-ngx pull request #8752
Opened 2022-09-28 18:19 UTC by shrvr

## Related Issue(s)

part of #8557 

## Description

Solves [this](https://github.com/SAP/fundamental-ngx/issues/8557#issuecomment-1220624224): Added  keyboard support for mobile mode in menu.

2022-09-29 08:46 UTC, platon-rov reviewed
two more items here

* when press "back" button being in 2nd level, you get to the 3rd level, press "back" again - you go somewhere, like you pressed on a link

https://user-images.githubusercontent.com/20265336/192984558-0dcbe080-0c70-4dc2-b4a6-74524c89af06.mov

* when you use right arrow key to get deeper to the 3rd level, then when you press left to get back to 2nd level - focus is lost

https://user-images.githubusercontent.com/20265336/192984824-76f595e1-5f13-417b-8b91-1d444bd43052.mov

2022-10-04 17:11 UTC, mikerodonnell89 requested changes

2022-10-04 17:11 UTC, mikerodonnell89 commented on libs/core/src/lib/menu/menu-mobile/menu-mobile.component.ts
> +        setTimeout(() => {
I do not think this setTimeout is needed (can just use `activeNode?.focus();`)

2022-10-04 17:14 UTC, mikerodonnell89 commented
Using setTimeout here is giving off some code smells. It would be better to wait for the presence of the desired element, or to use events, something along those lines

2022-10-06 10:16 UTC, platon-rov commented on libs/core/src/lib/menu/services/menu.service.ts
> +                console.log('left arrow: focused node: ', this.focusedNode);
please remove log.

2022-10-21 15:53 UTC, shrvr commented
Current Issue (Help Needed for):

https://user-images.githubusercontent.com/65063487/197236672-432eb490-7220-4bc1-b594-4ce3ca677489.mp4

When we come back to Main Menu It focuses first item instead the item which we lastly visited.
In this case, it focused 'Fruits'  instead 'Milk Products' when we come back to main menu at last.

2022-10-24 16:27 UTC, mikerodonnell89 commented
Can we have a variable to store the previously focused item's index when moving between submenus?

2022-10-28 19:16 UTC, shrvr commented
> Can we have a variable to store the previously focused item's index when moving between submenus?

Menu-service is keeping track of the `activepath` when we travel through submenus. There is already `focusedNode` that we can focus when we go backward. 
Issue is when we come back to main menu, it focuses first menu item. The `focus `function of menu-item is called one extra time when we come back to main menu.

2022-10-31 16:43 UTC, mikerodonnell89 approved these changes

2022-11-01 02:01 UTC, merged