fix(platform): fix broken two-columns options in select
SAP/fundamental-ngx pull request #8805
Opened 2022-10-07 18:07 UTC by shrvr

## Related Issue(s)

closes #8801 

## Description

Platform: Fixed broken two-columns options in select.

## Screenshots

### Before:
![image](https://user-images.githubusercontent.com/65063487/194621747-23e5d683-e8ea-4564-91f0-70d3920cdfc7.png)

### After:
![image](https://user-images.githubusercontent.com/65063487/194621740-46d1b9cb-eef0-4f06-8d17-81b4d73de84c.png)

#### Please check whether the PR fulfills the following requirements

##### During Implementation

1. Visual Testing:

-   [ ] visual misalignments/updates
-   [ ] check Light/Dark/HCB/HCW themes
-   [ ] RTL/LTR - proper rendering and labeling
-   [ ] responsiveness(resize)
-   [ ] Content Density (Cozy/Compact/(Condensed))
-   [ ] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [ ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [ ] Mouse vs. Keyboard support
-   [ ] Text Truncation

2. API and functional correctness

-   [ ] check for console logs (warnings, errors)
-   [ ] API boundary values
-   [ ] different combinations of components - free style
-   [ ] change the API values during testing

3. Documentation and Example validations

-   [ ] missing API documentation or it is not understandable
-   [ ] poor examples
-   [ ] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [ ] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [ ] tests for the changes that have been done
-   [ ] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [ ] Run npm run build-pack-library and test in external application
-   [ ] update `README.md`
-   [ ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

2022-10-20 08:45 UTC, platon-rov commented on libs/platform/src/lib/form/select/select/select.component.html
> +        <span fd-list-title id="primary-title" [innerHTML]="optionItem.label"></span>
Having multiple same IDs is a bad practice.

2022-10-24 17:45 UTC, InnaAtanasova requested changes

2022-10-24 17:45 UTC, InnaAtanasova commented on libs/platform/src/lib/form/select/select/select.component.ts
> +            }
I don't like this solution. We don't need to use `querySelector` and we can add this css to the component itself OR better fix it in the fund-styles

2022-10-28 09:23 UTC, platon-rov approved these changes

2022-10-28 16:03 UTC, InnaAtanasova approved these changes

2022-10-29 02:11 UTC, merged