Fix/8602 table drag and drop
SAP/fundamental-ngx pull request #8830
Opened 2022-10-12 08:06 UTC by skaquib123

## Related Issue(s)

closes #8602 

## Description

-Able to draw before and after a row. It is not going inside.
-Able to draw last row to first row and vice versa.

## Screenshots

### Before:
![2022-10-12_12-48-46 (1)](https://user-images.githubusercontent.com/110972289/195276105-67c9aff6-e3be-4676-aa3e-3ae7e8ec1f59.gif)

### After:
![2022-10-12_12-52-05 (1)](https://user-images.githubusercontent.com/110972289/195276837-61458496-1c2b-458c-af41-5a3950108d06.gif)

#### Please check whether the PR fulfills the following requirements

##### During Implementation

1. Visual Testing:

-   [x] visual misalignments/updates
-   [x] check Light/Dark/HCB/HCW themes
-   [x] RTL/LTR - proper rendering and labeling
-   [x] responsiveness(resize)
-   [x] Content Density (Cozy/Compact/(Condensed))
-   [x] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [x] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] Mouse vs. Keyboard support
-   [x] Text Truncation

2. API and functional correctness

-   [x] check for console logs (warnings, errors)
-   [x] API boundary values
-   [x] different combinations of components - free style
-   [x] change the API values during testing

3. Documentation and Example validations

-   [x] missing API documentation or it is not understandable
-   [x] poor examples
-   [x] Stackblitz works for all examples

4. Accessibility testing
5. Browser Testing - Edge, Safari, Chrome, Firefox

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md
-   [x] tests for the changes that have been done
-   [x] all items on the PR Review Checklist are addressed :
        https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checklist
-   [x] Run npm run build-pack-library and test in external application
-   [x] update `README.md`
-   [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

2022-10-28 09:19 UTC, platon-rov reviewed
Although this is nice to have feature, it may be better to have both modes - place before/after and place inside, so we have to somehow distinct between those two.

2022-10-31 08:21 UTC, fkolar commented
> Although this is nice to have feature, it may be better to have both modes - place before/after and place inside, so we have to somehow distinct between those two.

I agree. Let's move to this direction and maybe to unblock anybody who is using it and needs this so badly, plus currently see this as blocker or defect (that you can't simply drag now at all  - as now its limited).

 Let's take this as a part I. and the D&D "into & out" address  in the next PR. I am sure there will be other cases as well

2022-10-31 08:33 UTC, fkolar requested changes

2022-10-31 08:33 UTC, fkolar commented on libs/platform/src/lib/table/table.component.spec.ts
My only comment to this PR, would be add more unit tests and clearly validate before and after, first to last, last to first, last in between, first in between works correctly. I don't see any added tests here.

2022-11-01 16:15 UTC, mikerodonnell89 reviewed
Not unique to this PR, but when I drag Laptops here, why does Screens get expanded?

https://user-images.githubusercontent.com/2471874/199282575-181e23aa-0997-4608-ba4b-7f2efe709d33.mov

2022-11-02 03:50 UTC, skaquib123 commented
@mikerodonnell89 That feature was already existing that of dropped row will get expanded so i did not change it. Let me know if that also need to be changed.

2022-11-08 20:24 UTC, mikerodonnell89 commented
I am now only seeing changes to a test file

2022-11-09 02:44 UTC, skaquib123 commented
Hi @mikerodonnell89 ,  Can you please check in the commits and let me know if you can see?
link:
[https://github.com/SAP/fundamental-ngx/pull/8830/commits/6a4df64dd428900140fb17f806e0287b0aa41416](url)

2022-11-10 12:14 UTC, merged