fix(core): combobox: set value to null on clear button
SAP/fundamental-ngx pull request #8863
Opened 2022-10-17 22:13 UTC by shrvr

## Related Issue(s)

closes #8858 

## Description

Set value to null on clear button in Combobox.

2022-10-18 06:49 UTC, desaroxx commented on libs/core/src/lib/combobox/combobox.component.ts
> +
before the regression the old behaviour was to set the value to `null` as soon as the label aka searchTerm is not an exact match to any items in the dropdown list.


https://user-images.githubusercontent.com/1498400/196356169-5881990b-e7a0-4f77-b025-5b0a16d5f4e1.mp4

2022-10-18 18:23 UTC, mikerodonnell89 requested changes

2022-10-18 18:23 UTC, mikerodonnell89 commented on libs/core/src/lib/combobox/combobox.component.ts
> +            const value = this._getOptionObjectByDisplayedValue(this.inputText);
If we want to communicate by object, we don't want to just get the object by the displayed value. Take a look at the reactive example, which uses these two values:
```
        { displayedValue: 'Apple', value: 'AppleValue' },
        { displayedValue: 'Apple', value: 'AppleValue2' },
```
Now we can no longer select the option with AppleValue2. You'll see this is working on main

2022-10-24 19:19 UTC, mikerodonnell89 approved these changes

2022-10-26 16:47 UTC, InnaAtanasova approved these changes

2022-10-28 20:53 UTC, merged