fix(core): select custom width & refactoring
SAP/fundamental-ngx pull request #9008
Opened 2022-11-28 10:24 UTC by platon-rov

## Related Issue(s)

Closes https://github.com/SAP/fundamental-ngx/issues/8995
Refers to `dxp/backlog/issues/720`

## Description

Select component fixes & refactoring to be able to set custom width easily.

**Before**
```CSS
.my-custom-select {
  width: 500px;
}

::ng-deep .fd-select .fd-popover-custom {
  min-width: 100%;
}
```

**After**
```CSS
.my-custom-select {
  width: 500px;
}
```

## Screenshots

No visual changes.

2022-11-28 20:37 UTC, InnaAtanasova approved these changes

2022-11-28 22:04 UTC, g-cheishvili requested changes
Please add documentation entries for deprecations

2022-11-29 12:56 UTC, platon-rov commented
> Please add documentation entries for deprecations

I'm not sure that we post info about CSS classes being used in our components, it's more fund-styles way.

2022-11-29 19:11 UTC, mikerodonnell89 commented on libs/core/src/lib/select/select.component.html
> +    <!-- @deprecated class fd-popover-custom-list -->
```suggestion
    <!-- @deprecated leaving class fd-popover-custom-list to support backwards compatibility-->
```

2022-11-29 19:46 UTC, mikerodonnell89 requested changes
I think we should also change `option.component.html` to

```
<span fd-list-title>
    <ng-content></ng-content>
</span>
```

Which correctly matches the fundamental-styles API and fixes this text centering issue which becomes more apparent when using a custom width:
<img width="757" alt="Screen Shot 2022-11-29 at 12 36 58 PM" src="https://user-images.githubusercontent.com/2471874/204632888-1f75e076-4c55-4510-a487-cf1c6ebd1721.png">

2022-12-01 15:23 UTC, mikerodonnell89 approved these changes

2022-12-05 19:57 UTC, g-cheishvili approved these changes

2022-12-05 20:30 UTC, merged