fix(core,platform): button toggled state
SAP/fundamental-ngx pull request #9010
Opened 2022-11-28 15:39 UTC by platon-rov

## Related Issue(s)

Closes none.

## Description

## Screenshots

No visual changes.

## BREAKING CHANGE:
* using of `toggled` input property instead of `aria-selected` attribute is now required

2022-11-28 20:38 UTC, InnaAtanasova approved these changes

2022-11-28 22:03 UTC, g-cheishvili requested changes

2022-11-28 22:03 UTC, g-cheishvili commented on libs/platform/src/lib/button/button.component.ts
> +     */
Please add documentation entry like it is for Content Density, so that user sees it right when they arrive at the docs page

2022-11-28 22:03 UTC, g-cheishvili commented on libs/platform/src/lib/button/button.component.ts
> +     * propagate aria-pressed for accessiblity to the native HTML button
Documentation entry

2022-11-29 19:01 UTC, mikerodonnell89 approved these changes

2022-12-05 12:14 UTC, g-cheishvili approved these changes

2022-12-06 15:14 UTC, merged