[WIP] core multicombobox & cdk package
SAP/fundamental-ngx pull request #9176
Opened 2023-01-04 12:52 UTC by N1XUS

2023-01-04 15:31 UTC, g-cheishvili commented
`fn` is there, do you plan to rename those directives and services?

2023-01-04 15:36 UTC, N1XUS commented
> `fn` is there, do you plan to rename those directives and services?

As discussed, fn prefix will be changed. Just waited for the group call to decide.

2023-01-05 16:35 UTC, g-cheishvili commented
It would be great if we added warnings when old selectors are used. for example, the auto-complete directive now has 3 selectors `[fdkAutoComplete], [fdAutoComplete], [fd-auto-complete]` but had 2 previously, as I understand from now on, `fdk` one should be used. So when user uses old ones, we could throw some warnings in dev mode

2023-01-05 16:56 UTC, g-cheishvili commented
One thing to consider in the CVA topic is if the user already has a long inheritance chain, will they need to alter their chain in order to use `BaseCvaControl`? Or they will go into our source code, copy the `BaseCvaControl`, and paste into their code?

I think we should have one provider factory which will create that base class, user will import provider in their component's providers list and then inject it. No need for inheriting class

2023-01-05 16:59 UTC, g-cheishvili commented
In `Clicked Behavior` doc page, `FnClickedProvider` is mentioned

2023-01-05 17:04 UTC, g-cheishvili commented on libs/cdk/src/lib/README.md
> +    import { FundamentalNgxCDKModule } from '@fundamental-ngx/cx';
```suggestion
    import { FundamentalNgxCDKModule } from '@fundamental-ngx/cdk';
```

2023-01-05 17:05 UTC, g-cheishvili commented on libs/cdk/src/lib/README.md
> +    For example, to use Switchs, add the following import to your main application module.
Switches?

2023-01-05 17:07 UTC, g-cheishvili commented
In CDK documentation folders, `fn` is mentioned couple of times

2023-01-05 17:12 UTC, g-cheishvili commented
focus, tabbable and type-check pages do not work

2023-01-05 18:39 UTC, platon-rov reviewed
good job, some minor stuff

2023-01-05 18:39 UTC, platon-rov commented on libs/core/src/lib/multi-combobox/models/multi-combobox.interface.ts
> +export interface MultiComboboxInterface extends MobileMode {
if it's related to mobile let's name it accordingly, please.

2023-01-05 19:31 UTC, N1XUS commented
> One thing to consider in the CVA topic is if the user already has a long inheritance chain, will they need to alter their chain in order to use `BaseCvaControl`? Or they will go into our source code, copy the `BaseCvaControl`, and paste into their code?
> 
> I think we should have one provider factory which will create that base class, user will import provider in their component's providers list and then inject it. No need for inheriting class

Hello @g-cheishvili. Would love to see small example please

2023-01-06 10:27 UTC, N1XUS commented on libs/cdk/src/lib/forms/helpers/cva.ts
> +import { Type } from '@angular/core';
I actually had to remove this file since currently angular compiler will fail with such host directive declaration

2023-01-09 10:00 UTC, g-cheishvili commented
My changes need documentation amendments :/

2023-01-09 15:48 UTC, N1XUS commented on libs/cdk/src/lib/data-source/base/base-data-source.class.ts
> +    open(): Observable<T[]> {
As for `open`. In base abstract class, yes, it doesn't do much than applying pipe. But it's an abstract class, and inherited classes may contain additional logic (for example, some http requests or setting some additional configuration, etc.). Logically it still makes sense to keep the name `open`

2023-01-09 15:58 UTC, platon-rov commented on libs/cdk/src/lib/data-source/base/base-data-source.class.ts
> +    open(): Observable<T[]> {
Then it makes sense to do not `match()` in constructor (as every successor will do) if we want to configure anything in `open()` before matching.

2023-01-09 19:17 UTC, N1XUS commented on libs/cdk/src/lib/data-source/base/base-data-source.class.ts
> +    open(): Observable<T[]> {
That makes sense :)

2023-01-09 19:18 UTC, g-cheishvili commented
Selectable list documentation mentions `fdSelectableList`

2023-01-09 19:20 UTC, g-cheishvili commented
> Selectable list documentation mentions `fdSelectableList`

Same for `fnReadonly`

2023-01-09 19:25 UTC, g-cheishvili requested changes
Few minor documentation changes and it's ready I think

2023-01-10 14:28 UTC, g-cheishvili approved these changes

2023-01-11 09:25 UTC, merged