fix(core): date-picker respects closeOnDateChoose input now
SAP/fundamental-ngx pull request #9195
Opened 2023-01-09 22:15 UTC by g-cheishvili

## Related Issue(s)

closes #9060 

## Description

The calendar would alter date-range values, as a result, there was no way of knowing whether or not the user had finished selecting dates, and also date-picker was not respecting `closeOnDateChoose` input.

2023-01-11 09:54 UTC, N1XUS approved these changes

2023-01-11 17:49 UTC, mikerodonnell89 requested changes
I think we should try to mirror ui5's behavior with how the input is populated when selecting dates in a range. Here, after opening a range datepicker and clicking a date, the input displays "Invalid Date" for the end date, and if the user clicks outside the popover before selecting an end date, the end date is "null". UI5 does not update the selected date range until the user has selected a valid start and end date in the popover

2023-01-26 21:36 UTC, g-cheishvili commented
> 

We can do that in nearest future, now it just requires a lot of changes. Let's use it this way, especially if you consider the fact that input was there before, just it was not respected by the component itself, so it was a bug

2023-01-26 22:00 UTC, mikerodonnell89 approved these changes
We'll address my previous comment in another PR

2023-01-27 17:20 UTC, merged