fix(platform): include hidden columns also with the column selection
SAP/fundamental-ngx pull request #9757
Opened 2023-04-26 20:07 UTC by fkolar

## Related Issue(s)

closes #9520

## Description

This is additional fix to existing issue where we did not include hidden columns with the final selection. Updated `getTableColumns` to return conditional either all disableP13n = true or false, so we can easily merge column from dialog. 

##### PR Quality

-   [x] the commit message(s) follows the guideline:
        https://github.com/SAP/fundamental-ngx/blob/main/CONTRIBUTING.md

2023-04-27 16:14 UTC, mikerodonnell89 approved these changes
good catch

2023-04-27 17:47 UTC, InnaAtanasova approved these changes

2023-04-28 06:45 UTC, fkolar commented
@mikerodonnell89 @InnaAtanasova , can we merge? Or @droshev  can you give me merging privileges for the things that are approved

2023-04-28 14:39 UTC, mikerodonnell89 requested changes
e2e tests are failing, looks relevant this time

2023-05-01 10:54 UTC, g-cheishvili approved these changes

2023-05-04 07:06 UTC, fkolar commented
I will check.

2023-05-04 09:08 UTC, I543348 commented
> @mikerodonnell89: I need to wait for @Anusha, as its not just e2e, but we opened up a box with more problems. So before fixing this we need to clarify a few things e.g.:
> 
> Columns: ` [Name, Description, Price, Status, Action ]`
> 
> * Mark **Action** column as **disableP13n**,  and open up a p13n dialog and you want to move Column **Name** all the way to bottom (last column)
>   
>   * What should happen ? Because by putting the disableP13n column back, it will placed as last  as it originally was.  We have no way to understand that column **Name** needs to be really last column
> * Mark **Price** as **disableP13n**, the same as above ? you move any columns before or after the **Price**
>   
>   * How do you want to maintained the original position of this **Price** columns?
> 
> I don't think there is a solution, besides rolling back the change.

Thanks @fkolar , I think the columns positions should not be changed. please let me know if there is any clarifications required from my end. Thanks.

2023-05-05 07:21 UTC, fkolar commented
Closing PR, as we are going to roll back this requirements to its original state.

2023-05-05 07:21 UTC, closed without merging