wip: bug where scrollable popovers would not scroll
SAP/fundamental-ngx pull request #9924
Opened 2023-05-24 19:43 UTC by mikerodonnell89

fixes #9908 #9763 #9637

2023-05-26 12:01 UTC, N1XUS approved these changes

2023-05-26 12:02 UTC, N1XUS commented
@mikerodonnell89 please check failing e2e

2023-05-26 18:27 UTC, InnaAtanasova approved these changes

2023-05-29 13:23 UTC, g-cheishvili approved these changes

2023-05-29 14:22 UTC, g-cheishvili requested changes

2023-05-29 14:22 UTC, g-cheishvili commented on libs/core/src/lib/popover/popover-body/popover-body.component.html
> +    class="fd-popover__body"
<img width="330" alt="Screenshot 2023-05-29 at 18 21 22" src="https://github.com/SAP/fundamental-ngx/assets/28543391/197cf9fd-0c02-4746-97a6-05fd7c597e61">
Offset is lost now

2023-05-30 21:50 UTC, closed without merging